package lenses

import "github.com/sw6n297mn8-maker/mesh-spec/architecture/artifact-schemas:artifact_schemas"

multiTenancyAndIdentityArchitecture: artifact_schemas.#AnalyticalLens & {
id:     "lens-multi-tenancy-and-identity-architecture"
name:   "Multi-Tenancy e Arquitetura de Identidade"

purpose: "Orientar decisões sobre como projetar multi-tenancy e identidade — isolamento de dados, visibility models, org lifecycle e identity per bounded context."
status: "draft"

trigger: {
	conditions: [
		"a decisão envolve como organizações diferentes (fornecedores, construtoras, FIDC) coexistem na mesma plataforma com isolamento rigoroso de dados",
		"a decisão envolve quem pode ver o quê — modelo de visibilidade e permissões cross-organizacional",
		"a decisão envolve como um comprador acessa dados de performance de fornecedor sem ver dados do fornecedor com outros compradores",
		"a decisão envolve como FIDC acessa dados de risco da carteira sem ver operações internas de construtora ou dados sensíveis de fornecedor",
		"a decisão envolve como implementar tenant isolation no banco de dados, na API, e nos eventos",
		"a decisão envolve como modelar identidade (usuários, organizações, papéis, permissões) numa plataforma multisided",
		"a decisão envolve como dados fluem entre organizações de forma controlada — o que é compartilhado, o que é privado, e quem controla a decisão",
		"a decisão envolve como prevenir data leakage entre tenants e como detectar se isolation foi violado",
		"a decisão envolve como agentes IA operam com escopo de permissões correto sem acessar dados de outros tenants",
	]
	keywords: [
		"multi-tenancy", "tenant", "inquilino", "isolamento",
		"identity", "identidade", "IAM", "autenticação", "autorização",
		"permissão", "permission", "RBAC", "ABAC", "policy",
		"organização", "organization", "org", "workspace",
		"visibilidade", "visibility", "quem vê o quê", "access control",
		"data isolation", "isolamento de dados", "row-level security", "RLS",
		"cross-tenant", "vazamento", "leakage", "data leak",
		"compartilhamento", "sharing", "dados compartilhados",
		"papel", "role", "gestor", "admin", "operador", "viewer",
		"escopo", "scope", "contexto", "context boundary",
		"fornecedor vê", "construtora vê", "FIDC vê",
	]
	excludeWhen: [
		"a decisão é sobre criptografia, TLS, zero-trust networking — usar security-trust-infrastructure",
		"a decisão é sobre governança de agentes IA e human-in-the-loop — usar ai-agent-governance",
		"a decisão é sobre compliance regulatória e LGPD — usar regulatory-compliance-as-architecture",
		"a decisão é sobre UX por lado da plataforma (experiência, não acesso) — usar multi-sided-platform-ux",
		"a decisão é sobre design de API (endpoints, versioning) — usar api-design-as-product",
	]
	rationale: "A Mesh é uma plataforma B2B multisided onde fornecedores, construtoras e FIDC compartilham uma infraestrutura comum mas têm necessidades de isolamento radicalmente diferentes. Fornecedor A não pode ver operações de Fornecedor B — nem que existem. Construtora vê performance de seus fornecedores mas não vê operações desses fornecedores com outras construtoras. FIDC vê risco agregado da carteira mas não vê comunicação interna entre construtora e fornecedor. Cada participante tem uma 'janela' diferente sobre os mesmos dados subjacentes, e essa janela é definida por relacionamento (quem transaciona com quem), papel (gestor, operador, viewer), e contexto (operacional vs risco vs compliance). Errar esta arquitetura é existencial: um vazamento de dados entre tenants — fornecedor descobre taxa que outro fornecedor recebeu, construtora descobre operações de fornecedor com concorrente — destrói a confiança na rede e possivelmente gera consequência jurídica. Security-trust-infrastructure cobre criptografia e zero-trust. AAG cobre governança de agentes. MUX cobre experiência por lado. Esta lens cobre a arquitetura fundamental de como entidades coexistem com isolamento, como identidade e permissões são modeladas, e como dados fluem entre organizações de forma controlada."
}

concepts: [
	{
		id:         "mt-tenant-model"
		name:       "Modelo de Tenant: Como Organizações São Representadas e Isoladas"
		nature:     "theoretical"
		role:       "framework"
		definition: "Tenant é a unidade de isolamento organizacional na plataforma — tipicamente 1 tenant = 1 organização (empresa). 3 modelos de implementação: **(1) database-per-tenant** — cada tenant tem database separada. Isolamento máximo (impossível acessar dados de outro tenant por erro de query). Custo: N databases para N tenants. Operação: N backups, N migrations, N connection pools. Adequado para: poucas dezenas de tenants com requisitos rigorosos de isolamento (enterprise SaaS, financial institutions). **(2) schema-per-tenant** — database compartilhada, schema separado por tenant. Isolamento forte (schema boundary previne cross-access). Custo: moderado (1 database, N schemas). Operação: 1 backup, N migrations (ou shared migration with schema routing). **(3) shared-schema with row-level security (RLS)** — database compartilhada, schema compartilhado, cada row tem tenant_id. Isolamento por query filter (WHERE tenant_id = ?) ou RLS policy (PostgreSQL row-level security). Custo: mínimo (1 database, 1 schema). Risco: bug em query filter = vazamento cross-tenant. Mitigation: RLS policies no database level (enforced mesmo que application query esqueça WHERE). Bezos (Amazon, 2002): 'every service interface must be externalizable — no exceptions.' Applied to multi-tenancy: every data access must be tenant-scoped — no exceptions. If a query can return data from another tenant: architecture is broken. Conceito contemporâneo de 'tenant-aware architecture' (2023+): tenant context não é bolted-on (WHERE clause adicionado after-the-fact) — é primitiva arquitetural. Toda request carrega tenant context. Toda query é scoped. Todo evento carrega tenant_id. Todo log é tenant-tagged. Tenant context propagates through entire stack: API → service → database → event → log. Missing tenant context em qualquer camada = potential leakage."
		meshManifestation: "Na Mesh, o modelo de tenant é mais complexo que single-tenant-per-org porque a Mesh é multisided: (1) **fornecedor** é tenant — seus dados (documentos, conta bancária, histórico) são isolados. Fornecedor A não vê dados de Fornecedor B. (2) **construtora** é tenant — suas configurações (threshold, políticas, fornecedores qualificados) são isoladas. Construtora X não vê configurações de Construtora Y. (3) **FIDC** é tenant — sua carteira, relatórios, configurações de risco são isolados. FIDC 1 não vê carteira de FIDC 2. (4) **MAS**: operações de antecipação envolvem MÚLTIPLOS tenants — fornecedor (cedente) + construtora (sacado) + FIDC (cessionário). A operação não pertence a 1 tenant — pertence a uma RELAÇÃO entre tenants. Isso é fundamentalmente diferente de SaaS single-tenant onde cada dado pertence a exatamente 1 org. Na Mesh: dados pertencem a relações. Implementação recomendada para Mesh: **shared-schema com RLS + relationship-based access.** Razão: (a) database-per-tenant é inviável para centenas de fornecedores. (b) schema-per-tenant adiciona complexidade para dados que são inherently cross-schema (operações). (c) shared-schema com RLS: 1 database, 1 schema, PostgreSQL RLS policies enforcing isolation. Operações: acessíveis por todos os participantes da relação (fornecedor, construtora, FIDC) com views diferentes. RLS policy: 'user pode ver operação se user.org_id IN (operação.fornecedor_id, operação.construtora_id, operação.fidc_id).'"
		meshImplication: "Tenant architecture implementation: (1) **tenant_id em toda tabela** — tabelas que pertencem a 1 org (configurações, documentos, users): column org_id NOT NULL. Tabelas que pertencem a relação (operações, antecipações): columns fornecedor_id, construtora_id, fidc_id. (2) **PostgreSQL RLS** — policy per table: CREATE POLICY tenant_isolation ON operations USING (fornecedor_id = current_setting('app.current_org_id')::uuid OR construtora_id = current_setting('app.current_org_id')::uuid OR fidc_id = current_setting('app.current_org_id')::uuid). SET app.current_org_id no início de cada request. RLS é enforced no database — application bug que esquece WHERE clause: dados ainda protegidos. (3) **tenant context propagation** — middleware/interceptor no API layer: extract org_id from auth token → SET app.current_org_id → all queries within request are scoped. Evento: always includes source_org_id + related_org_ids. Log: always includes org_id. (4) **default deny** — se org_id não está set: query retorna zero rows (não todos). RLS default: deny. Explicit policy: allow. Fail-closed, not fail-open. (5) **cross-tenant queries** — para analytics e reporting que aggregam cross-tenant (e.g., FIDC portfolio): dedicated service account com explicit grant para cross-tenant read. NOT via application user context. Separate code path with explicit authorization. Audited. (6) **testing** — tenant isolation test: create data in tenant A, authenticate as tenant B, assert: zero rows returned. Automated. Run on every deploy. Failure: deploy blocked. Anti-pattern: application-level WHERE clause como único mecanismo de isolamento — 1 developer que esquece WHERE em 1 query = data leak. RLS é safety net no database level que application-level bugs cannot bypass."
		rationale: "Bezos 2002: every interface externalizable. Tenant-aware architecture 2023+. Na Mesh multisided, shared-schema com RLS + relationship-based access: isolamento forte (database-enforced) com flexibilidade para dados cross-tenant (operações envolvem 3 tenants). Data leak entre tenants em plataforma financeira: existencial."
	},
	{
		id:         "mt-visibility-model"
		name:       "Modelo de Visibilidade: Cada Participante Vê Janela Diferente sobre os Mesmos Dados"
		nature:     "theoretical"
		role:       "framework"
		definition: "Em plataforma multisided, o mesmo dado subjacente (uma operação de antecipação) é visível para múltiplos participantes, mas cada um vê uma projeção diferente — fields diferentes, context diferente, actions diferentes. Conceito de 'data projection by role' (2023+): dado base é o mesmo registro; o que cada participante vê é uma projeção (view) filtrada por: (a) quais fields são visíveis (fornecedor vê taxa aplicada a ele; não vê taxa aplicada a outros fornecedores). (b) quais registros são visíveis (construtora vê seus fornecedores; não vê fornecedores de outra construtora). (c) quais actions são possíveis (construtora aprova operação; fornecedor vê status mas não aprova). Conceito de 'relationship-based access control' (ReBAC, Google Zanzibar 2019): permissões derivadas de relações entre entidades, não de roles estáticos. 'User A pode ver Operação X porque User A pertence a Org B que é construtora na Operação X.' Relação (User→Org→Operação) determina permissão. Mais flexível e correto que RBAC puro para plataformas multisided. Conceito de 'information asymmetry by design' (2024+): em marketplaces e plataformas financeiras, informação assimétrica é feature, não bug. Fornecedor NÃO deve saber a taxa que outro fornecedor recebeu — isso preserva poder de precificação. Construtora NÃO deve saber que fornecedor opera com outras construtoras — preserva exclusividade percebida. FIDC NÃO deve ver comunicação operacional — preserva separação de papéis. A plataforma design a assimetria para benefício de todos."
		meshManifestation: "Na Mesh, visibilidade por participante para uma operação de antecipação: **Fornecedor (cedente) vê:** seus dados: valor do recebível, taxa aplicada a ELE, valor líquido, status da operação, ETA de depósito, histórico DELE. Não vê: taxa de outros fornecedores, quem mais fornece para esta construtora, score breakdown detalhado (vê zona: 'Bom', não feature weights), configurações da construtora (threshold, políticas). **Construtora (sacado) vê:** dados da relação: lista de seus fornecedores, status de operações de SEUS fornecedores, compliance de SEUS fornecedores, performance aggregate de SEUS fornecedores, configurações DELA (threshold, políticas). Não vê: operações de seus fornecedores com OUTRAS construtoras, taxa específica que fornecedor recebeu (vê range da carteira), dados bancários do fornecedor, fornecedores de outras construtoras. **FIDC (cessionário) vê:** dados da carteira: operações que compõe SUA carteira, score de cada operação, inadimplência, concentração, performance de safra, relatórios de risco. Não vê: comunicação entre construtora e fornecedor, detalhes operacionais internos da construtora, dados de fornecedores que não participam de operações no SEU FIDC, configurações internas de construtoras. **Mesh (plataforma) vê:** tudo — mas acessa apenas via serviços internos com auditoria. Nenhum humano da Mesh tem acesso direto a dados de participantes sem justificativa auditada."
		meshImplication: "Visibility implementation: (1) **API projections** — cada endpoint retorna projeção baseada em caller identity. GET /operations/{id}: se caller é fornecedor: retorna {id, valor, taxa, status, eta_deposito}. Se caller é construtora: retorna {id, fornecedor_nome, valor_total, status, score_zona}. Se caller é FIDC: retorna {id, fornecedor_anonimizado_ou_nome, construtora, valor, score, inadimplência_status}. Mesma rota, mesma operação, projeção diferente. (2) **field-level visibility rules** — configuration per entity type: operations.taxa: visible_to = [fornecedor_owner]. operations.score_details: visible_to = [construtora_owner, fidc_owner]. operations.bank_account: visible_to = [fornecedor_owner]. Rules stored as configuration, not hardcoded in each endpoint. (3) **relationship graph** — maintained: Fornecedor A → operates_with → Construtora X. Construtora X → funded_by → FIDC 1. Operação → involves → [Fornecedor A, Construtora X, FIDC 1]. Access derived from graph traversal: 'User belongs to Org → Org has relationship → relationship grants visibility.' (4) **event projections** — events published to different consumers carry different payloads. OperationApproved event → fornecedor subscriber: {operation_id, status, valor_liquido, eta}. Same event → FIDC subscriber: {operation_id, score, valor, sacado_id, taxa}. Event router: filters fields per subscriber org type. (5) **audit trail** — every data access logged: who (user_id, org_id), what (entity, fields accessed), when, from where (IP, service). Anomaly detection: user accessing unusually many records, user accessing records outside normal pattern → alert. (6) **information asymmetry preservation** — explicit rules: 'fornecedor A must NOT learn that Fornecedor B exists in same construtora.' API: list endpoints for construtora show only HER fornecedores. Fornecedor portal: shows only HIS construtoras. No cross-reference possible. Anti-pattern: API endpoint that returns all operations unfiltered, relying on frontend to hide fields — frontend is not security boundary. Backend API must return only visible data. If frontend is bypassed (API call direct): only visible data returned."
		dependsOn: ["mt-tenant-model"]
		crossDependsOn: [{
			lensId:    "lens-multi-sided-platform-ux"
			conceptId: "mux-per-side-experience"
			context:   "MUX define experiência por lado da plataforma (UX, density, features). MT visibility model define what data each side CAN see (access control, projections). MUX decides how to present; MT decides what to present. MUX says 'fornecedor mobile with simplified dashboard'; MT says 'fornecedor sees only: own operations, own taxa, own documents — nothing from other fornecedores or construtora internals.' MUX is experience design; MT is information boundary."
		}]
		rationale: "ReBAC Zanzibar 2019. Data projection by role 2023+. Information asymmetry by design 2024+. Na Mesh, cada participante tem janela diferente sobre mesmos dados. Janela definida por relação, não por role estático. Information asymmetry é feature que preserva poder de mercado de cada participante."
	},
	{
		id:         "mt-identity-and-authorization"
		name:       "Identidade e Autorização: Quem É, a Que Organização Pertence, e o Que Pode Fazer"
		nature:     "operational"
		role:       "framework"
		reviewCadence: "semi-annual"
		definition: "Identity model para B2B multisided: 3 camadas: **(1) User** — pessoa física (ou agente IA) com credenciais de autenticação. Attributes: email, auth method, MFA status. **(2) Organization (Org/Tenant)** — empresa. Attributes: CNPJ, tipo (fornecedor, construtora, FIDC, plataforma), status, configurações. Relationship: user belongs_to org (N:M — user pode pertencer a múltiplas orgs). **(3) Role within Org** — papel do user dentro da org. Determines: quais actions pode executar e quais dados pode ver. Conceito de 'organization-scoped roles' (2023+): roles são definidos POR organização, não globalmente. User A é 'gestor' na Construtora X e 'viewer' na Construtora Y (se pertence a ambas). Role determina actions (gestor pode aprovar; viewer pode ver mas não aprovar) e data scope (gestor vê tudo; operador vê apenas operações assignadas a ele). Roles para Mesh: **admin** — full access dentro da org. Gerencia users, configurações, integrações. **gestor** — operational decision-maker. Aprova operações, configura thresholds, revisa fornecedores. **operador** — day-to-day. Submete operações, upload documentos, executa tarefas. **viewer** — read-only. Consulta dashboards, relatórios. Não modifica. **auditor** — read-only com acesso ampliado. Para compliance, due diligence. Temporário ou permanente. Conceito de 'API key identity' (2024+): em B2B, integrações via API precisam de identidade não-humana. API key pertence a Org (não a user). Tem scoped permissions (read-only, write operations, admin). Rate-limited. Audited. Revogável."
		meshManifestation: "Na Mesh, identity model: **Entidades:** User (pessoa ou agente). Org (empresa — fornecedor, construtora, FIDC). Membership (user belongs_to org with role). API Key (non-human identity, belongs_to org). **Autenticação:** user autentica via: email+password+MFA (standard), SSO/SAML (enterprise — construtora e FIDC grandes), API key+secret (integrações). Resultado: auth token com claims: {user_id, org_id, org_type, role, permissions[]}. **Autorização:** per-request: (a) extract org_id + role from token. (b) check: does role have permission for this action on this resource? (c) check: does org have relationship that grants visibility to this resource? (d) if both pass: execute. If either fails: 403. **Example flow:** User 'João' autentica → token: {user: joão, org: construtora_x, role: gestor, permissions: [approve_operation, view_fornecedores, configure_threshold]}. João calls GET /operations → API: SET app.current_org_id = construtora_x → PostgreSQL RLS: returns only operations where construtora_id = construtora_x. João calls POST /operations/{id}/approve → API: check permission approve_operation in token → check operation.construtora_id = construtora_x → if yes: approve. João calls GET /operations of Construtora Y → RLS returns 0 rows (even though operations exist). Zero information about other construtoras leaked."
		meshImplication: "Identity implementation: (1) **auth token structure** — JWT with: sub (user_id), org (org_id), org_type (fornecedor|construtora|fidc|plataforma), role, permissions[], iat, exp. Short-lived (15min) with refresh token. Org_id is REQUIRED claim — no request without org context. (2) **multi-org users** — user pertence a 2+ orgs: must select active org at login or via org switcher. Token is per-org. Switching org = new token. Never: token with permissions from multiple orgs simultaneously (leakage vector). (3) **permission model** — RBAC for actions (role → permissions set). ReBAC for data (relationship graph → visibility). Combined: 'user with role gestor in construtora X can approve operations (RBAC) that belong to construtora X (ReBAC).' (4) **API key management** — per org: create, list, revoke API keys. Each key: name, permissions (subset of role), created_by, last_used, expiration. Rate limit per key. Audit: every API call with key logged. (5) **agent identity** — agentes IA (Claude Code, processing agents) operate with: service account identity, org-scoped (plataforma org or specific org), explicit permissions (never admin — principle of least privilege), all actions logged with agent_id. Agent accessing data: same RLS as human. Agent cannot bypass tenant isolation. (6) **invitation flow** — construtora invites fornecedor: creates relationship + sends invitation. Fornecedor accepts: creates user (if new) + membership in fornecedor org. Relationship: construtora_x → operates_with → fornecedor_a. Now: construtora_x can see fornecedor_a's operations with construtora_x only. (7) **deprovisioning** — user leaves org: membership revoked → tokens invalidated → access ceases immediately. Org leaves platform: data retained per regulatory requirement (LGPD) but access revoked. Admin audit: who was deprovisioned, when, by whom. Anti-pattern: global admin role that can see all tenants' data — violates principle of least privilege and creates single point of catastrophic leakage. Platform admin should use separate, audited, time-limited elevation (break-glass procedure), not permanent god-mode."
		dependsOn: ["mt-tenant-model", "mt-visibility-model"]
		crossDependsOn: [{
			lensId:    "lens-security-trust-infrastructure"
			conceptId: "sti-zero-trust"
			context:   "STI define zero-trust: never trust, always verify. MT identity + authorization is the identity layer of zero-trust: every request verifies user identity (authn) + org context (tenant) + role permissions (authz) + relationship (ReBAC). STI says 'verify everything'; MT says 'here's how to verify: token with org_id + role → RLS + permission check → access or deny.' STI is the principle; MT is the identity-specific implementation."
		}]
		rationale: "Organization-scoped roles 2023+. API key identity 2024+. Na Mesh, identity model: user → org → role → permissions (RBAC) + org → relationship → visibility (ReBAC). Combined: 'gestor da construtora X pode aprovar operações da construtora X.' Both dimensions checked on every request. Missing either: security hole."
	},
	{
		id:         "mt-data-sharing-patterns"
		name:       "Patterns de Compartilhamento de Dados: O que Cruza Fronteiras de Tenant e Como"
		nature:     "operational"
		role:       "method"
		reviewCadence: "quarterly"
		definition: "Em plataforma multisided, some data MUST cross tenant boundaries — that's the value proposition (connecting parties). Mas o cruzamento deve ser controlled, minimal, e consentido. Conceito de 'controlled data sharing' (2023+): 3 patterns: **(1) mutual visibility** — ambos participantes de uma relação veem subset dos dados do outro. Fornecedor e construtora veem status da operação entre eles. Symmetry: ambos veem, ambos contribuem. **(2) asymmetric visibility** — um participante vê mais do outro do que vice-versa. Construtora vê compliance do fornecedor; fornecedor não vê configurações da construtora. Rationale: construtora é quem assume risco de trabalhar com fornecedor — precisa de mais informação. **(3) aggregated/anonymized sharing** — dados compartilhados em forma que não identifica individuais. FIDC vê inadimplência aggregate, não operações específicas de fornecedores que não são da carteira dele. Benchmark: 'sua taxa está 0.5pp abaixo da média do mercado' — sem revelar taxas de fornecedores específicos. Conceito de 'consent-based sharing' (2024+): fornecedor consente, ao aderir à plataforma, que certos dados sejam visíveis para construtoras com quem opera. Consentimento: explicit nos termos de uso. Scope: limited aos dados necessários para a relação funcionar. LGPD compliance: data sharing tem base legal (execução de contrato) + consentimento explícito."
		meshManifestation: "Na Mesh, sharing patterns por dado: **(1) Mutual visibility:** operação de antecipação — fornecedor e construtora veem status, valor, timeline. FIDC vê se operação está na carteira dele. Cada um vê projeção diferente (mt-visibility-model) mas existência é mutual. **(2) Asymmetric visibility:** compliance de fornecedor → visível para construtora (que precisa verificar). Compliance de construtora → visível para FIDC (que precisa verificar sacado). Não simétrico: fornecedor não vê compliance da construtora. Score de operação → visível para construtora e FIDC (decisão). Fornecedor vê zona ('Bom') mas não score numérico (informação que poderia ser gamed). **(3) Aggregated sharing:** benchmark de taxas → 'sua taxa está 0.5pp abaixo da média para seu perfil de risco.' Sem revelar taxa de outros fornecedores. Performance de cadeia → 'inadimplência média de fornecedores nesta cadeia: 1.2%.' Sem identificar quais fornecedores contribuem. Concentração de FIDC → 'top sacado: 12% da carteira.' Sem revelar identidade do sacado para outros FIDCs."
		meshImplication: "Data sharing rules: (1) **sharing matrix** — documento no mesh-spec: matrix [dado × participante → visibilidade]. Cada cell: visible (full), visible (partial/projected), visible (aggregated), not visible. Maintained as governance artifact. Reviewed quarterly. Mudança: ADR com justificativa. (2) **minimum necessary** — share only what's necessary for the relationship to function. Fornecedor não precisa ver score numérico para operar (zona é suficiente). Construtora não precisa ver dados bancários do fornecedor (pagamento é via plataforma). FIDC não precisa ver comunicação operacional (risco é derivado de dados estruturados). (3) **consent and transparency** — termos de uso: explicit description of what data is shared, with whom, for what purpose. Fornecedor ao aderir: 'seus documentos de compliance serão visíveis para construtoras com quem você opera.' Granular: fornecedor pode escolher quais construtoras (se operar com múltiplas). (4) **derived data vs source data** — compartilhar derived (score zona, aggregate metrics, status) em vez de source (feature values, raw financials, internal scores). Derived: útil para decisão sem expor detalhes sensíveis. Source: expõe demais. (5) **time-limited sharing** — dados de operação: visíveis durante lifecycle (active, settled). Após período de retenção: archived com access restrito. Fornecedor que deixa plataforma: dados de relações passadas mantidos para compliance (regulatory) mas acesso do fornecedor revogado. Construtora que pede dados históricos de fornecedor que saiu: dados de compliance e performance da relação (necessários para auditoria). Dados sensíveis do fornecedor: não mais acessíveis. (6) **API enforcement** — sharing rules implementadas no API layer (projeções) e database layer (RLS). Frontend NUNCA é o enforcement boundary. Se API retorna dado que deveria ser invisible: frontend hiding é cosmético, não security. API must return only what's allowed. Anti-pattern: 'full data in API, filter in frontend' — API call bypasses frontend → all data exposed. Or: sharing decision made per-request by developer judgment → inconsistency, human error."
		dependsOn: ["mt-tenant-model", "mt-visibility-model"]
		crossDependsOn: [{
			lensId:    "lens-regulatory-compliance-as-architecture"
			conceptId: "rc-lgpd-data-governance"
			context:   "RC LGPD cobre: base legal para processamento, direitos do titular, data governance. MT data sharing patterns operacionaliza para multi-tenant: cada cross-tenant data share tem base legal (contrato de antecipação), consentimento (termos de adesão), e minimum necessary scope (derivado, não source). RC é o framework regulatório; MT é a implementação técnica de sharing que cumpre LGPD em contexto multi-tenant."
		}]
		rationale: "Controlled data sharing 2023+. Consent-based sharing 2024+. Na Mesh, sharing matrix: documento governante que define cada dado × participante × visibilidade. Minimum necessary: share derived, not source. Consent: explicit em termos. Enforcement: API + RLS, never frontend."
	},
	{
		id:         "mt-agent-tenant-scope"
		name:       "Escopo de Tenant para Agentes IA: Agentes Operam Dentro de Fronteiras"
		nature:     "operational"
		role:       "heuristic"
		reviewCadence: "quarterly"
		definition: "Em AI-native platform, agentes IA são operadores que acessam dados, tomam decisões, e executam ações. Agentes DEVEM operar dentro de tenant scope — mesmas restrições que humanos. Conceito de 'agent identity scoping' (2024+): cada agente IA tem: (a) service account identity (não pessoal). (b) org_id assignment (qual tenant o agente está servindo neste contexto). (c) permission set (principle of least privilege — agente de scoring não precisa de permissão de admin). (d) audit trail (toda ação do agente logada com: agent_id, org_id, action, data_accessed, decision, timestamp). Risco específico de agentes: (a) context window leak — agente que processa dados de tenant A em sessão que posteriormente processa tenant B: dados de A podem influenciar decisão para B (via model weights ou context). Mitigation: session isolation per tenant. (b) prompt injection — adversário insere instrução em dado de tenant A que faz agente acessar dados de tenant B. Mitigation: agente não pode override org_id via prompt — org_id é set pelo sistema, not by input. (c) escalation — agente que começa com permissão read escala para write via tool usage. Mitigation: permission boundaries enforced per-tool, not per-session."
		meshManifestation: "Na Mesh, agent scoping: (1) **scoring agent** — identity: service account 'scoring-agent.' Org scope: processes one operation at a time; org_id = construtora da operação. Permissions: read operation data, read fornecedor compliance (within construtora's visibility), write score. Cannot: access operations of other construtoras, modify configurações, access raw data de outros FIDCs. (2) **compliance agent** — identity: 'compliance-agent.' Org scope: per-fornecedor per-construtora relationship. Permissions: read fornecedor documents, verify against requirements, write compliance status. Cannot: access fornecedor's operations with OTHER construtoras, modify fornecedor data. (3) **reporting agent** — identity: 'reporting-agent.' Org scope: per-FIDC. Permissions: read carteira data (aggregated), generate reports, write to report storage. Cannot: access individual fornecedor details beyond what FIDC visibility allows, access data of other FIDCs. (4) **Claude Code (development agent)** — identity: 'development-agent.' Org scope: plataforma (Mesh itself). Permissions: read/write mesh-spec, read/write code, deploy. CANNOT: access production data of any participant (development is code-level, not data-level). If testing needed: synthetic data or anonymized snapshot."
		meshImplication: "Agent scoping implementation: (1) **service account per agent type** — each agent type (scoring, compliance, reporting, development) has dedicated service account with explicit permissions. Not: shared super-user that all agents use. (2) **org_id injection by system** — when agent processes operation: system sets org_id based on operation context (construtora_id). Agent CANNOT set its own org_id. If agent prompt says 'set org to X': ignored — org_id is system-controlled. (3) **per-tool permission enforcement** — agent uses tools (database query, API call, file write). Each tool: checks agent's permission before executing. Agent with read permission: tool blocks write attempt. (4) **session isolation** — agent processing tenant A data: session context cleared before processing tenant B. No carryover of data, context, or intermediate results between tenant sessions. (5) **audit logging** — every agent action: {agent_id, agent_type, org_id, action, data_entities_accessed[], decision, timestamp, session_id}. Auditable: 'scoring agent accessed operation #1234 in construtora X context, produced score 65, at 14:32 UTC.' (6) **anomaly detection for agents** — agent accessing unusually many records, agent accessing records outside its normal pattern, agent producing decisions that deviate significantly from historical distribution → alert for human review. (7) **development agent isolation** — Claude Code / development agents: NEVER access production data. Development database = synthetic data or anonymized copy. If development agent needs to debug production issue: explicit, logged, time-limited access grant (break-glass). Anti-pattern: agent with plataforma-level access that processes data for all tenants in same session — cross-tenant data leakage via context, model influence, or logging."
		dependsOn: ["mt-tenant-model", "mt-identity-and-authorization"]
		crossDependsOn: [{
			lensId:    "lens-ai-agent-governance"
			conceptId: "aag-hitl-calibration"
			context:   "AAG define human-in-the-loop para decisões de agente. MT agent scoping garante que quando agente escalates to human: human only sees data within their own tenant scope. If compliance agent flags issue for human review: review dashboard shows only data from the fornecedor-construtora relationship in question, not cross-tenant data. AAG governs decision quality; MT governs data boundary of that decision."
		}]
		rationale: "Agent identity scoping 2024+. Na Mesh AI-native, agentes são operadores primários — e portanto subject to mesmas restrições de tenant que humanos. Agent with plataforma-level access = single point of catastrophic leakage. Agent per-tenant-scoped = same isolation as human users. Principle: if human can't see it, agent can't see it (unless explicitly granted with audit)."
	},
	{
		id:         "mt-tenant-isolation-testing"
		name:       "Testes de Isolamento: Provar que Fronteiras São Invioláveis"
		nature:     "operational"
		role:       "method"
		reviewCadence: "quarterly"
		definition: "Tenant isolation deve ser provado, não assumido. Conceito de 'isolation testing' (2023+): testes automatizados que verificam: (a) positive access — user de tenant A acessa dados de tenant A → sucesso. (b) negative access — user de tenant A tenta acessar dados de tenant B → zero rows, 403, ou 404 (not 500 — graceful denial). (c) cross-tenant query — query sem tenant context → zero rows (fail-closed). (d) relationship-based access — user de construtora X acessa operação que envolve construtora X → sucesso. User de construtora Y acessa mesma operação → denial. (e) field-level visibility — user de fornecedor acessa operação → fields visíveis são apenas os permitidos (taxa dele, não taxa de outros). (f) event leakage — event de tenant A não é entregue a subscriber de tenant B. Conceito de 'isolation regression testing' (2024+): toda mudança em schema, API, event, ou permission model: run isolation test suite. Qualquer regressão (dado que era invisible agora é visible): deploy blocked. Isolation é a propriedade mais importante da plataforma multi-tenant — regressão é inaceitável."
		meshManifestation: "Na Mesh, isolation test suite: (1) **tenant separation** — cria 2 fornecedores (A, B), 2 construtoras (X, Y), 2 FIDCs (1, 2). Operação entre A-X-1. Tests: fornecedor B acessa operação → 0 rows. Construtora Y acessa operação → 0 rows. FIDC 2 acessa operação → 0 rows. (2) **field projection** — fornecedor A acessa operação → response contains: taxa (dele). Does NOT contain: score_numérico, threshold_construtora, dados_fidc. (3) **relationship boundary** — construtora X lista fornecedores → vê A (operates_with). Não vê B (no relationship). (4) **agent isolation** — scoring agent processes operação A-X: acessa apenas dados visíveis para construtora X context. Query for operação de construtora Y: 0 rows. (5) **event isolation** — operação A-X approved: fornecedor A recebe evento (projeção fornecedor). Construtora X recebe (projeção construtora). FIDC 1 recebe (projeção FIDC). Fornecedor B, construtora Y, FIDC 2: não recebem. (6) **deprovisioned access** — user removido de construtora X: login com token X → rejected. Cached token: expired or blacklisted."
		meshImplication: "Testing implementation: (1) **isolation test suite as CI gate** — runs on every PR that modifies: database schema, API endpoints, event handlers, permission rules. Failure: merge blocked. Non-negotiable. (2) **test fixture** — standard multi-tenant fixture: 3 orgs per type (fornecedores A, B, C; construtoras X, Y, Z; FIDCs 1, 2, 3). Relationships: A↔X↔1, B↔Y↔2, C↔Z↔3. Tests cross-check: every org against every other org's data. (3) **positive + negative** — for every endpoint: test both 'authorized access returns data' AND 'unauthorized access returns empty/403.' If only positive: doesn't prove isolation. (4) **field-level assertions** — response body assertions: 'response for fornecedor A on operation A-X-1 CONTAINS taxa.' 'response for construtora X on same operation DOES NOT CONTAIN fornecedor_bank_account.' (5) **fuzz testing for isolation** — generate random (tenant_id, resource_id) pairs. For each: attempt access. Assert: access is granted only when valid relationship exists. Catches: edge cases like newly created resources defaulting to public. (6) **production monitoring** — beyond testing: production query logging that flags any query that returns cross-tenant data (query result contains org_ids different from request org_id). Alert: immediate. Frequency: real-time. Severity: critical. (7) **penetration testing** — quarterly: external or internal adversary attempts to breach tenant isolation. Vectors: API manipulation, token forgery, parameter tampering (changing org_id in request), SQL injection targeting RLS bypass. Results: documented, remediated, re-tested. Anti-pattern: isolation tests only in staging, not CI — developer introduces RLS bypass in PR, tests pass (no isolation test), deployed to production, cross-tenant data exposed for hours/days until someone notices."
		dependsOn: ["mt-tenant-model", "mt-visibility-model", "mt-identity-and-authorization"]
		rationale: "Isolation testing 2023+. Isolation regression 2024+. Na Mesh, tenant isolation test suite as CI gate: every PR touching data access is verified. Regressão = blocked. Production monitoring: real-time cross-tenant query detection. Isolation is not asserted — it's continuously proven."
	},
	{
		id:         "mt-org-lifecycle"
		name:       "Lifecycle de Organização: Onboarding, Operação, Suspensão, Offboarding"
		nature:     "operational"
		role:       "method"
		reviewCadence: "semi-annual"
		definition: "Organizations have lifecycle: onboarding (join platform) → operational (active participation) → suspension (temporary disable) → offboarding (leave platform). Each state has identity and data implications. Conceito de 'graceful offboarding' (2024+): when org leaves platform: (a) data owned by org: retained per regulatory requirement (LGPD: period varies). (b) relationships: terminated (org's fornecedores removed from construtora's view). (c) active operations: settled or cancelled (no orphaned financial operations). (d) access: immediately revoked (all users, all API keys, all agent service accounts). (e) derived data: scores, benchmarks that included this org: recalculated without their data. (f) notification: counterparties notified ('Construtora X deixou a plataforma. Operações pendentes foram [status].')."
		meshManifestation: "Na Mesh, org lifecycle: (1) **onboarding** — construtora convida fornecedor → fornecedor cria conta → KYC/KYB → compliance docs → aprovação → relationship ativada. Identity: user created, org created, membership created, relationship created. Data: initial compliance docs uploaded, score generated. (2) **operational** — normal operation. Identity: users added/removed, roles changed, API keys created. Data: operations, documents, communications. (3) **suspension** — org suspended (compliance failure, fraud investigation, payment default). Access: read-only (org can see own data but cannot transact). Active operations: frozen (no new approvals, existing in flight continue to settlement). Relationships: suspended (construtora cannot initiate new operations with this fornecedor). Notification: counterparties notified ('Fornecedor X está temporariamente suspenso'). (4) **offboarding** — org leaves or is removed. Access: revoked for all users, API keys, agents. Data: retained per regulation. Operations in flight: settled or cancelled. Relationships: terminated. Counterparties: notified. Derived data: recalculated. Identity: memberships soft-deleted (audit trail preserved)."
		meshImplication: "Lifecycle implementation: (1) **org status enum** — onboarding → active → suspended → offboarded. State machine: defined transitions, each with preconditions (all operations settled before offboard). (2) **suspension = read-only mode** — API: POST/PUT/DELETE blocked for suspended org. GET allowed. UI: banner 'Sua conta está suspensa. Contate suporte.' Actions disabled but data visible. (3) **offboarding procedure** — documented runbook: (a) notify all counterparties (automated). (b) settle or cancel all active operations (manual review for complex cases). (c) revoke all access (automated: disable all users, invalidate all tokens, revoke all API keys). (d) retain data per regulation (automated: mark org as offboarded, data preserved but inaccessible via normal access). (e) recalculate derived data (automated: re-run aggregations excluding offboarded org). (f) notify plataforma admin (automated: audit entry). (4) **re-onboarding** — if org returns after offboarding: new org, new relationships. Historical data from previous tenure: available to regulador and platform (compliance), not restored to org (fresh start). (5) **orphan prevention** — before offboarding: verify: zero active operations, zero unresolved disputes, zero pending compliance actions. If any: offboarding blocked until resolved. Automated check + manual override (with justification) for exceptional cases."
		dependsOn: ["mt-tenant-model", "mt-identity-and-authorization"]
		rationale: "Graceful offboarding 2024+. Na Mesh, fornecedor que sai: operações settled, access revoked, data retained per regulation, counterparties notified, derived data recalculated. Every step documented and automated where possible. Offboarding poorly handled: orphaned operations, angry counterparties, regulatory risk."
	},
	{
		id:         "mt-audit-and-compliance-trail"
		name:       "Audit Trail Multi-Tenant: Quem Acessou o Quê, Quando, e de Qual Contexto"
		nature:     "operational"
		role:       "property"
		reviewCadence: "quarterly"
		definition: "Em plataforma financeira multi-tenant: toda ação e acesso a dados deve ser auditável. Reguladores (Bacen, CVM), auditores externos (FIDC), e compliance interna precisam responder: 'quem viu esse dado? Quem tomou essa decisão? Quando? Com qual autoridade?' Conceito de 'comprehensive audit trail' (2023+): log de auditoria que captura: who (user_id, agent_id, org_id, role), what (action, resource_type, resource_id, fields_accessed), when (timestamp, timezone), where (IP, device, service), why (justification for elevated access), outcome (success, failure, data returned). Conceito de 'tenant-scoped audit' (2024+): audit trail itself is tenant-scoped — construtora X's audit trail is visible only to construtora X (and to reguladores/plataforma with appropriate access). FIDC 1 cannot see construtora X's internal audit trail. Exception: shared operations have audit entries visible to all participants of that operation."
		meshManifestation: "Na Mesh, audit trail: (1) **every data access logged** — GET /operations → log: {user: joão, org: construtora_x, action: list_operations, count: 47, timestamp: ...}. GET /operations/123 → log: {user: joão, org: construtora_x, action: view_operation, operation_id: 123, fields: [id, status, valor, score_zona], timestamp: ...}. (2) **every mutation logged** — POST /operations/123/approve → log: {user: joão, org: construtora_x, action: approve_operation, operation_id: 123, previous_status: pendente, new_status: aprovado, timestamp: ...}. (3) **every agent action logged** — scoring_agent scores operation → log: {agent: scoring-agent, org_context: construtora_x, action: score_operation, operation_id: 123, score: 65, model: v2.3, features_used: [...], timestamp: ...}. (4) **elevated access logged** — plataforma admin accesses tenant data (break-glass) → log: {admin: admin_user, elevated_access: true, target_org: construtora_x, justification: 'support ticket #4567', data_accessed: [...], timestamp: ..., auto_expires: 1h}."
		meshImplication: "Audit implementation: (1) **audit log as append-only event stream** — audit entries are events: immutable, ordered, stored in dedicated audit storage (not same database as operational data). Event sourcing compatible: audit stream is separate event store or dedicated topic. (2) **structured audit entry** — schema: {event_id, timestamp, actor: {type: user|agent|system, id, org_id, role}, action, resource: {type, id, fields[]}, context: {ip, device, service, session}, outcome: {status, data_summary}, justification?: string}. (3) **retention** — minimum: 5 years (regulatory). FIDC operations: 10+ years. Immutable: audit entries cannot be modified or deleted (except by platform admin under compliance procedure with separate audit of the deletion). (4) **query access** — org admin: can query own org's audit trail. FIDC: can query audit trail of operations in their carteira. Regulador: full access (via formal request, logged). Plataforma: full access (logged, justified). (5) **anomaly detection on audit** — patterns: user accessing unusually many records in short time (data exfiltration). User accessing records outside working hours. Agent accessing data with no corresponding operation. User from IP in unusual geography. Automated alerts for anomalous patterns. (6) **audit of audit access** — who queried the audit trail is itself logged. Prevents: 'someone checked the audit trail to see if their unauthorized access was noticed.' Meta-audit adds layer of accountability. (7) **compliance reporting** — automated reports from audit trail: 'all accesses to FIDC 1 carteira data in last quarter.' 'All operations approved by construtora X in 2025.' 'All agent decisions with score <50 in last month.' Reports: generated on-demand or scheduled. Anti-pattern: audit logging only for mutations (writes) but not for reads — in financial multi-tenant, unauthorized READ is as serious as unauthorized WRITE (viewing another tenant's data is a breach even if nothing was modified)."
		dependsOn: ["mt-tenant-model", "mt-identity-and-authorization", "mt-visibility-model"]
		crossDependsOn: [{
			lensId:    "lens-observability-operational-intelligence"
			conceptId: "ooi-structured-logging"
			context:   "OOI define structured logging para operational health. MT audit trail extends para compliance and security: same structured format but different purpose. OOI asks 'is the system healthy?' MT audit asks 'who did what with whose data?' OOI logs are for engineers; MT audit logs are for compliance officers, reguladores, and legal. Both: structured, queryable, retained. But: audit logs are immutable and retained for years, operational logs may be shorter-lived."
		}]
		rationale: "Comprehensive audit 2023+. Tenant-scoped audit 2024+. Na Mesh financial multi-tenant: every read and write is logged with full context. Regulador can answer 'who saw this data?' for any operation at any time. Audit trail is the foundation of trust between platform and participants and between platform and reguladores."
	},
	{
		id:            "mt-multi-tenancy-review"
		name:          "Revisão de Multi-Tenancy: Inventário Periódico de Isolamento e Identidade"
		nature:        "operational"
		role:          "method"
		reviewCadence: "quarterly"
		definition:    "Inventário periódico: (1) tenant model — RLS policies current? New tables have tenant_id? (2) visibility — sharing matrix updated? Projections correct per persona? (3) identity — roles and permissions current? API keys audited? MFA adoption? (4) data sharing — minimum necessary enforced? Consent documentation current? (5) agent scoping — agents operating within tenant boundaries? No cross-tenant context carryover? (6) isolation testing — test suite passing? New endpoints covered? (7) org lifecycle — any orgs pending offboarding? Suspended orgs reviewed? (8) audit trail — logs complete? Anomalies detected? Compliance reports generated?"
		meshManifestation: "Na Mesh: revisão trimestral. Isolation test suite runs on every deploy. Quarterly: manual review of sharing matrix, permission model, and audit anomalies."
		meshImplication: "Quarterly (2h): (a) isolation test suite — all passing? Any new tables/endpoints not covered? Add tests. (b) sharing matrix — review: any visibility change requests from participants? Any new data types needing classification? Update matrix. (c) permission audit — list all roles × permissions. Any role with excessive permissions? Any user with role they shouldn't have? Review admin access: who has it, is it justified? (d) API key audit — all API keys: last used, owner, permissions. Revoke unused (>90 days). Review permissions: any over-granted? (e) agent scope review — agent service accounts: permissions still appropriate? Any new agent type needing its own service account? (f) audit trail anomalies — review anomaly alerts from quarter. Resolved? Root cause? Systemic issue? (g) org lifecycle — pending offboardings completed? Suspended orgs: review justification, determine if should be reactivated or offboarded. (h) penetration test results (if conducted) — remediated? Re-tested?"
		dependsOn: ["mt-tenant-model", "mt-visibility-model", "mt-identity-and-authorization", "mt-data-sharing-patterns", "mt-agent-tenant-scope", "mt-tenant-isolation-testing", "mt-org-lifecycle", "mt-audit-and-compliance-trail"]
		rationale: "Multi-tenancy degrades with feature additions: new table without RLS, new endpoint without projection, new agent without scoping. Quarterly review + CI isolation tests + production monitoring: continuous proof of isolation."
	},
]

reasoningProtocol: [
	{
		question:  "Toda tabela tem tenant_id ou relationship IDs? RLS policies estão ativas e enforcing isolation no database level?"
		reveals:   "Se isolamento é database-enforced (inviolável por application bug) — ou se isolation depende de WHERE clauses que developer pode esquecer."
		rationale: "RLS é safety net no database que application-level bugs cannot bypass. WHERE clause como único mecanismo: 1 esquecimento = data leak."
	},
	{
		question:  "Cada participante (fornecedor, construtora, FIDC) tem projeção de dados definida? API retorna apenas fields e records visíveis para o caller?"
		reveals:   "Se visibility é controlled by design — ou se API retorna tudo e frontend esconde (insecure)."
		rationale: "Data projection by role 2023+. API é o enforcement boundary. Frontend hiding é cosmético, não security."
	},
	{
		question:  "Identidade é user → org → role com permissions? Org_id é claim obrigatório em todo token? Multi-org user tem token per-org?"
		reveals:   "Se identity model é complete — ou se org_id é implícito/opcional (leakage vector quando missing)."
		rationale: "Organization-scoped roles 2023+. Org_id obrigatório: toda request tem contexto. Missing org_id: query sem scope = all tenants."
	},
	{
		question:  "Sharing matrix documenta cada dado × participante → visibilidade? Minimum necessary é enforced (derivado, não source)?"
		reveals:   "Se data sharing é governado por design — ou se cada developer decide caso a caso o que compartilhar (inconsistência)."
		rationale: "Controlled data sharing 2023+. Sharing matrix como governance artifact: decisão documentada, não ad hoc."
	},
	{
		question:  "Agentes IA operam com service account per-type, org-scoped, com permissions mínimas? Session isolation entre tenants?"
		reveals:   "Se agentes respeitam tenant boundaries — ou se agente com plataforma-level access processa todos os tenants em sessão compartilhada."
		rationale: "Agent identity scoping 2024+. Agent = operador. Mesmas restrições que humano. Session isolation: zero cross-tenant carryover."
	},
	{
		question:  "Test suite de isolamento roda em CI? Toda mudança em schema/API/eventos é verificada? Regressão bloqueia deploy?"
		reveals:   "Se isolamento é continuamente provado — ou se é assumido e só descoberto quando break ocorre em produção."
		rationale: "Isolation regression 2024+. CI gate: every PR touching data access → isolation verified. Regressão = blocked."
	},
	{
		question:  "Audit trail captura todo read e write com full context (who, what, when, where)? Tenant-scoped? Imutável?"
		reveals:   "Se accountability existe para toda ação — ou se 'quem viu esse dado?' é pergunta sem resposta."
		rationale: "Comprehensive audit 2023+. Em plataforma financeira: read não-autorizado é tão sério quanto write. Todo acesso: logged."
	},
]

meshExamples: [
	{
		id:       "ex-cross-tenant-visibility-design"
		scenario: "Construtora X quer ver taxa média praticada com seus fornecedores para comparar com mercado. Designer propõe mostrar taxa de cada fornecedor em tabela. Fornecedores reclamam: 'se construtora vê nossa taxa, vai pressionar quem cobra mais.'"
		analysis: "Conflito de informação assimétrica: construtora quer transparência total (ver taxa de cada fornecedor). Fornecedores querem opacidade (taxa é competitiva). Se construtora vê taxa individual: poder de barganha shift para construtora (pressiona taxa mais alta para baixo). Se construtora não vê nada: não consegue avaliar se está pagando fairly. Solução: informação derivada (aggregada) preserva utilidade sem expor individual."
		recommendation: "(1) Construtora NÃO vê taxa individual por fornecedor. Visibility rule: operations.taxa → visible_to = [fornecedor_owner] only. (2) Construtora VÊ: taxa média da carteira (R$: aggregate across all fornecedores). Distribuição: percentil (P25, P50, P75 das taxas dos seus fornecedores). Benchmark: 'sua taxa média está 0.3pp abaixo de construtoras similares.' (3) Derivado compartilhado, source protegido: construtora obtém informação útil (estou pagando fairly? compare with benchmark) sem ver taxa individual (que permitiria pressão específica). (4) Sharing matrix update: operations.taxa: fornecedor = visible, construtora = hidden (aggregate available via metric), FIDC = visible (precisa para risk pricing). (5) API implementation: GET /operations/{id} for construtora: response excludes taxa field. GET /analytics/taxa-media for construtora: returns aggregate {media: 2.3, p25: 1.8, p50: 2.2, p75: 2.8, benchmark: 2.6}. (6) Event projection: OperationApproved event → construtora subscriber: payload excludes taxa. FIDC subscriber: payload includes taxa. Fornecedor: includes (their own) taxa. (7) Rationale: information asymmetry by design. Fornecedor's competitive position (taxa) is protected. Construtora's evaluation need (am I fair?) is served. Platform value: creates safe space where fornecedores are willing to share data because sensitive data is protected."
		principlesApplied: ["ax-01", "ax-04", "ax-06"]
		assumptions: [
			"aggregate taxa is useful without individual — construtora may still want to see per-fornecedor for negotiation purposes",
			"fornecedores prefer opacidade — validate with fornecedor interviews",
			"benchmark is computable — requires sufficient data across construtoras (cold start: benchmark unavailable initially)",
			"FIDC seeing individual taxa is acceptable — FIDC needs for risk pricing; fornecedor consent covers this in contract",
		]
		rationale: "Information asymmetry by design 2024+. Derived data (aggregate) serves construtora's need without exposing fornecedor's competitive position. Platform that protects individual data while providing useful aggregates: trusted by all sides. Platform that exposes everything: trusted by no one (fornecedores leave)."
	},
	{
		id:       "ex-rls-prevents-application-bug"
		scenario: "Developer creates new API endpoint GET /fornecedores/{id}/documents for construtora to view fornecedor compliance documents. Developer forgets WHERE clause filtering by relationship (construtora→fornecedor). Bug: endpoint returns documents for ANY fornecedor, regardless of whether construtora has relationship."
		analysis: "Without RLS: construtora X calls GET /fornecedores/B/documents (fornecedor B operates with construtora Y, not X). Response: returns B's documents. Data leak: construtora X sees documents of fornecedor B with whom they have no relationship. Severity: critical — compliance documents contain sensitive business information. With RLS: same bug, same missing WHERE clause. PostgreSQL RLS policy: 'documents visible only if current_org has relationship with document.org_id.' Construtora X queries documents of fornecedor B: RLS returns 0 rows. Bug exists in application code, but data leak is prevented by database layer."
		recommendation: "(1) PostgreSQL RLS as defense-in-depth: even with application-level bug, database prevents cross-tenant access. RLS policy on documents table: CREATE POLICY doc_visibility ON documents USING (org_id IN (SELECT target_org_id FROM relationships WHERE source_org_id = current_setting('app.current_org_id')::uuid AND relationship_type = 'operates_with' AND status = 'active')). (2) Application-level WHERE is still required (defense in depth, not either-or). But RLS catches what application misses. (3) Fix the bug: add WHERE clause to endpoint. Add isolation test: 'construtora X accessing fornecedor B documents (no relationship) → 0 rows.' (4) CI gate: isolation test catches this class of bug before deploy. New endpoint → isolation test required before merge. (5) Post-incident: review all endpoints for similar missing relationship checks. Add missing WHERE clauses. Ensure all have corresponding isolation tests. (6) Long-term: generate endpoint boilerplate from scaffold that includes relationship check by default (td-debt-prevention: scaffolds with concerns inherited). Developer overrides to REMOVE check (with justification), not to ADD check (easily forgotten)."
		principlesApplied: ["ax-01", "ax-06", "dp-01"]
		assumptions: [
			"RLS performance is acceptable for document queries — PostgreSQL RLS on indexed foreign key: negligible overhead",
			"relationship table is maintained correctly — relationship creation/deletion must be transactional with operational data",
			"scaffold with default relationship check reduces future bugs — depends on scaffold adoption",
			"isolation test coverage catches this — test must cover every endpoint × non-authorized tenant combination",
		]
		rationale: "RLS as database-level safety net. Application bugs are inevitable. Data leaks from application bugs are preventable. RLS makes cross-tenant data leak from application bug impossible. Cost: RLS policy per table (minutes to create). Benefit: prevents class of critical bugs permanently."
	},
	{
		id:       "ex-agent-cross-tenant-prevention"
		scenario: "Scoring agent processes operations in batch: operation 1 (construtora X, fornecedor A), operation 2 (construtora Y, fornecedor B). Agent loads both into same session context for efficiency. Risk: features computed for operation 2 may be influenced by data from operation 1 (different tenant context)."
		analysis: "Cross-tenant context contamination: if agent processes operations from different tenants in same session, data from tenant 1 remains in context when processing tenant 2. Risks: (a) data in context window from operation 1 influences scoring of operation 2 (LLM-based agent). (b) cached data from tenant 1 used in computation for tenant 2 (traditional agent). (c) logging from operation 1 mixed with operation 2 in same session log (audit confusion). Even if no explicit data leak: appearance of cross-tenant processing undermines trust if discovered."
		recommendation: "(1) Enforce per-tenant session isolation: scoring agent processes operations one-at-a-time with session boundary between tenants. After processing operation 1 (construtora X): clear session context, clear cache, flush logs. Then: set new tenant context (construtora Y), process operation 2. (2) If batch is per-tenant: agent processes all operations for construtora X in one batch, then all for construtora Y. Within batch: same tenant context. Between batches: session boundary + context clear. (3) Implementation: agent orchestrator: groups operations by construtora_id → processes per-group → session reset between groups. Agent runtime: SET app.current_org_id at start of each group. Clear: model context, data cache, intermediate results at end of each group. (4) Audit: log includes session_id. Each session: single tenant. Cross-session: different tenant. Auditable: 'scoring session S1: construtora X, operations [1, 3, 5]. Session S2: construtora Y, operations [2, 4].' No session has mixed tenants. (5) Testing: test that agent with operations from 2 tenants in queue: processes in separate sessions. Assert: no data from tenant 1 in session 2 context. (6) Performance trade-off: per-tenant sessions are slower than mixed-tenant batch (session overhead × N tenants). Acceptable: isolation > throughput. If throughput is critical: parallelize per-tenant sessions (not mix tenants in same session)."
		principlesApplied: ["ax-01", "ax-06"]
		assumptions: [
			"per-tenant session isolation is feasible for scoring — depends on agent architecture (LLM: new conversation per tenant. Traditional: new process/container per tenant)",
			"session overhead is acceptable — if scoring takes 2s per operation and session setup takes 0.5s: 25% overhead. Acceptable for financial correctness",
			"batching by tenant doesn't create load imbalance — if construtora X has 500 operations and Y has 5: X batch takes 100x longer. Mitigation: break large batches into chunks with session refresh",
			"clearing LLM context between tenants is reliable — depends on agent framework (Claude: new conversation = fresh context. Fine-tuned model: weights may retain patterns — use per-tenant inference)",
		]
		rationale: "Agent identity scoping 2024+. Session isolation between tenants: prevents cross-contamination in AI-native platform. Even without explicit data leak: mixed-tenant processing is audit risk and trust risk. Per-tenant sessions: clean, auditable, trustworthy."
	},
	{
		id:       "ex-fidc-visibility-scope"
		scenario: "FIDC 1 requests full visibility into all operations on the platform for 'market intelligence.' Argues: 'we need to see all operations to price risk correctly, not just our carteira.' Platform must decide: grant extended visibility or preserve isolation."
		analysis: "FIDC request is commercially reasonable (more data = better pricing) but violates multi-tenancy principles: (1) FIDC 1 seeing operations of FIDC 2's carteira = competitive intelligence leak. (2) FIDC 1 seeing fornecedor operations not in their carteira = privacy violation (fornecedor didn't consent to share with this FIDC). (3) If granted to FIDC 1: every FIDC will demand same. Equilibrium: everyone sees everything = no privacy. Platform value (trusted intermediary) is destroyed. Information asymmetry between FIDCs is what makes platform valuable — each FIDC's pricing edge comes from their own carteira intelligence, not from platform-wide access."
		recommendation: "(1) Deny full visibility. FIDC 1 sees only: operations in their carteira (direct visibility), aggregate market benchmarks (indirect visibility). (2) Market intelligence via aggregated, anonymized data: 'inadimplência média do setor construção civil: 2.1%. Média de FIDCs no seu porte: 1.8%. Sua carteira: 1.5%.' No individual operation or entity identifiable. (3) Benchmark service: platform computes cross-FIDC benchmarks (aggregate). Each FIDC sees: own performance vs anonymized aggregate. Cannot reverse-engineer individual FIDC's data from aggregate (minimum N participants for benchmark: e.g., ≥5 FIDCs contributing before benchmark is shown). (4) Sharing matrix: operations → FIDC = visible only if operation.fidc_id = requesting FIDC. Aggregate metrics → all FIDCs (anonymized, minimum N). (5) Contractual: FIDC agreement explicitly states: 'access limited to own carteira. Market intelligence provided as anonymized aggregates.' (6) Technical enforcement: RLS on operations: FIDC can only see operations where fidc_id matches. Benchmark service: separate service with cross-tenant read (service account, audited) that produces aggregates. FIDC cannot call cross-tenant queries directly. (7) Communication to FIDC: 'we protect your carteira data from other FIDCs with the same rigor we protect other carteiras from you. This mutual protection is what makes the platform trustworthy. Aggregated benchmarks provide market context without exposing individual participants.'"
		principlesApplied: ["ax-01", "ax-04", "ax-06"]
		assumptions: [
			"FIDC accepts aggregated benchmark in lieu of full data — may need sales negotiation",
			"≥5 FIDC participants for meaningful benchmark — cold start: benchmark unavailable until 5+ FIDCs",
			"aggregated data cannot be reverse-engineered — with few participants: potential. Minimum N threshold prevents",
			"mutual protection argument is compelling — standard in financial infrastructure (clearinghouses operate this way)",
		]
		rationale: "Information asymmetry by design 2024+. FIDC full visibility = destroy platform trust. Aggregated benchmarks = serve FIDC need without destroying trust. Na Mesh, the value proposition to each participant is: 'your data is protected. You see your own data + anonymous market context. No one sees your data without your relationship granting access.' Granting full visibility to any participant: destroys this value proposition for all."
	},
]

principleIds: ["ax-01", "ax-04", "ax-06", "dp-01"]

relatedLenses: [
	{
		lensId:   "lens-security-trust-infrastructure"
		relation: "complementsWith"
		context:  "STI cobre encryption, zero-trust, TLS, secrets management. MT cobre tenant isolation, identity, visibility. STI protege data in transit and at rest; MT protege data in access (who sees what). STI is the cryptographic and network layer; MT is the identity and authorization layer. Together: data is encrypted (STI) AND accessible only to authorized tenants (MT)."
	},
	{
		lensId:   "lens-ai-agent-governance"
		relation: "complementsWith"
		context:  "AAG governa decisões de agentes (HITL, boundaries, drift detection). MT governa escopo de dados de agentes (tenant boundaries, service accounts, session isolation). AAG says 'agent must escalate to human for decisions above threshold'; MT says 'agent must operate within tenant X's data boundary when making that decision.' AAG is decision governance; MT is data governance for agents."
	},
	{
		lensId:   "lens-multi-sided-platform-ux"
		relation: "complementsWith"
		context:  "MUX define experiência por lado (UX, density, features). MT define o que cada lado pode ver (data projection, field visibility). MUX designs the interface; MT defines the data behind the interface. MUX says 'fornecedor sees simplified dashboard'; MT says 'fornecedor sees only own operations, own taxa, own documents.'"
	},
	{
		lensId:   "lens-regulatory-compliance-as-architecture"
		relation: "complementsWith"
		context:  "RC cobre LGPD, Bacen, CVM compliance. MT operacionaliza para multi-tenant: each cross-tenant data share has legal basis (contract), consent (terms), and minimum necessary scope. MT audit trail supports RC compliance reporting. RC is regulatory framework; MT is technical implementation in multi-tenant context."
	},
	{
		lensId:   "lens-event-driven-architecture-patterns"
		relation: "complementsWith"
		context:  "EDA define event catalog, event sourcing, async patterns. MT adds tenant dimension: every event carries source_org_id + related_org_ids. Event routing: filters payload per subscriber tenant. MT ensures event-driven architecture doesn't leak data cross-tenant."
	},
	{
		lensId:   "lens-observability-operational-intelligence"
		relation: "complementsWith"
		context:  "OOI define structured logging, monitoring, SLIs. MT extends: audit trail as compliance-grade logging (immutable, years of retention). MT anomaly detection for cross-tenant access patterns. OOI is operational health; MT audit is compliance and security accountability."
	},
	{
		lensId:   "lens-api-design-as-product"
		relation: "complementsWith"
		context:  "API design defines endpoints, contracts, versioning. MT adds projection layer: same endpoint returns different data per caller tenant. API design defines shape; MT defines scope. Together: API is well-designed (API lens) AND correctly scoped per tenant (MT lens)."
	},
	{
		lensId:   "lens-trust-and-credibility-design"
		relation: "complementsWith"
		context:  "TC builds trust through transparency and reliability. MT information asymmetry by design IS a trust mechanism: each participant trusts platform because their data is protected from competitors. Platform's trustworthiness depends on MT isolation being absolute. TC is trust perception; MT is trust infrastructure."
	},
]

limitations: [
	{
		description: "Shared-schema with RLS introduces runtime overhead — every query has additional WHERE/policy evaluation. For complex relationship graphs: RLS policy may be slow."
		alternative: "Index optimization: tenant_id and relationship foreign keys indexed. RLS policy: simple IN clause on indexed columns (fast). Complex graph traversal: pre-compute visibility set (materialized view refreshed periodically). Monitor: RLS query overhead as % of total query time. If >10%: optimize policy or consider schema-per-tenant for problematic tables."
		rationale: "RLS overhead is typically <5% for simple policies on indexed columns. Complex policies: pre-compute. Performance vs security: always choose security, then optimize performance."
	},
	{
		description: "Relationship-based access (ReBAC) is more complex to implement than simple RBAC. Debugging 'why can't user X see resource Y' requires traversing relationship graph."
		alternative: "Access explanation API: GET /debug/access?user=X&resource=Y → returns: 'User X belongs to Org A. Org A has no relationship with resource Y's owner Org B. Access: denied.' Available only in development/staging. Simplifies debugging without exposing in production."
		rationale: "ReBAC is more correct for multisided platforms but harder to debug. Access explanation tool: necessary for developer productivity."
	},
	{
		description: "Per-tenant agent session isolation reduces throughput — session setup/teardown overhead × number of tenants."
		alternative: "Parallel per-tenant sessions: process tenants concurrently in separate isolated sessions. Throughput: limited by parallelism capacity, not by sequential session overhead. For scoring: 10 parallel sessions processing 10 tenants simultaneously."
		rationale: "Isolation > throughput. Parallelism recovers most throughput loss while maintaining isolation."
	},
	{
		description: "Sharing matrix becomes complex as platform grows — more entity types, more relationships, more data fields. Matrix of 50 fields × 5 participant types × 3 visibility levels = 750 cells to maintain."
		alternative: "Default: invisible. Explicit: visible. Only document visibility grants, not denials. Matrix lists what IS shared, not what isn't (shorter). Group fields by sensitivity level: public (name, status), relational (compliance, performance), private (bank account, internal notes). Sensitivity level has default visibility per participant type."
		rationale: "Default-deny + explicit-grant: matrix lists exceptions, not every cell. Sensitivity levels: reduce 750 cells to ~15 rules."
	},
	{
		description: "Audit trail at the level of every read generates enormous log volume — 100 users × 50 queries/day × 365 days = 1.8M entries/year."
		alternative: "Tiered audit logging: Tier 1 (always): mutations (writes, approvals, rejections), elevated access, admin actions, agent decisions. Tier 2 (sampled or triggered): reads of sensitive data (financial values, compliance docs). Tier 3 (on-demand): general reads (list views, dashboard loads). Full audit for Tier 1 + sampled Tier 2 = 90% compliance value at 20% of volume."
		rationale: "Full read audit is ideal but volume-intensive. Tiered approach: always audit what matters most (mutations, sensitive reads), sample the rest."
	},
]

rationale: "A Mesh é plataforma B2B multisided onde fornecedores, construtoras e FIDC compartilham infraestrutura mas requerem isolamento rigoroso — um vazamento de dados entre tenants destrói a confiança na rede. Esta lens operacionaliza: modelo de tenant com shared-schema + PostgreSQL RLS + relationship-based access para isolamento database-enforced (Bezos 2002, tenant-aware 2023+), modelo de visibilidade com data projections por participante e information asymmetry by design (ReBAC Zanzibar 2019, data projection 2023+, information asymmetry 2024+), identidade e autorização com user→org→role + org-scoped permissions + API key management (organization-scoped roles 2023+, API key identity 2024+), patterns de compartilhamento com sharing matrix e minimum necessary + consent-based (controlled sharing 2023+, consent-based 2024+), escopo de tenant para agentes IA com service accounts e session isolation (agent identity scoping 2024+), testes de isolamento como CI gate com regression blocking (isolation testing 2023+, regression 2024+), lifecycle de organização com graceful offboarding (graceful offboarding 2024+), e audit trail multi-tenant com comprehensive logging e anomaly detection (comprehensive audit 2023+, tenant-scoped audit 2024+). Específica para multisided B2B financial platforms onde data isolation é existential — failure mode é not degraded experience but destroyed trust and legal liability."

}
