package lenses

import "github.com/sw6n297mn8-maker/mesh-spec/architecture/artifact-schemas:artifact_schemas"

// ════════════════════════════════════════════════════════════════
// lens-testing-and-validation-for-financial-systems
// ════════════════════════════════════════════════════════════════

testingAndValidationForFinancialSystems: artifact_schemas.#AnalyticalLens & {
id:     "lens-testing-and-validation-for-financial-systems"
name:   "Testing e Validação para Sistemas Financeiros"

purpose: "Orientar decisões sobre como testar sistemas financeiros com rigor — property-based testing, reconciliação contínua, chaos testing e validação de invariantes financeiras."
status: "draft"

trigger: {
	conditions: [
		"a decisão envolve como provar que dinheiro se move corretamente — somas batem, centavos não se perdem, saldos são consistentes",
		"a decisão envolve como testar reconciliação entre operações, pagamentos e saldos",
		"a decisão envolve como validar que decisões de agentes IA (scoring, compliance) produzem resultados corretos contra ground truth",
		"a decisão envolve como garantir que mudanças em código não introduzem erros financeiros em caminhos existentes",
		"a decisão envolve como projetar property-based testing para invariantes financeiras (soma de débitos = soma de créditos)",
		"a decisão envolve como projetar contract testing entre bounded contexts para garantir compatibilidade de interfaces",
		"a decisão envolve como validar edge cases financeiros (arredondamento, overflow, moeda, timezone, dias úteis)",
		"a decisão envolve como fazer chaos engineering e failure injection em sistema financeiro sem risco real",
		"a decisão envolve que nível de cobertura e que tipos de teste são adequados para cada camada do sistema",
	]
	keywords: [
		"teste", "test", "testing", "validação", "validation",
		"reconciliação", "reconciliation", "batimento", "conferência",
		"property-based", "invariante", "invariant", "propriedade",
		"contract test", "consumer-driven", "Pact", "schema compatibility",
		"arredondamento", "rounding", "centavo", "penny", "precision",
		"chaos engineering", "failure injection", "fault tolerance",
		"regression", "regressão", "golden file", "snapshot",
		"ground truth", "backtesting", "shadow mode", "champion-challenger",
		"coverage", "cobertura", "mutation testing",
		"end-to-end", "e2e", "integration", "unit",
		"idempotência", "idempotency", "retry", "duplicate",
		"settlement", "liquidação", "conciliação",
	]
	excludeWhen: [
		"a decisão é sobre observability e detecção de problemas em produção — usar observability-operational-intelligence",
		"a decisão é sobre dívida técnica e qualidade de código — usar technical-debt-as-strategic-instrument",
		"a decisão é sobre design de ML models e training — usar ml-ai-systems-design",
		"a decisão é sobre isolamento de dados entre tenants — usar multi-tenancy-and-identity-architecture",
		"a decisão é sobre modelagem temporal (D+0, D+1, calendário) — usar temporal-modeling-for-financial-systems",
	]
	rationale: "Sistemas financeiros têm tolerância zero a erro de centavo. Um bug que arredonda R$0,005 para baixo em 10.000 operações/mês: R$50/mês desaparecidos. Um bug que duplica liquidação: pagamento dobrado ao fornecedor. Um bug em scoring que classifica operação de alto risco como baixo risco: perda para o FIDC. OOI detecta problemas em produção (after the fact). TD cobre qualidade de código em geral. ML cobre design de modelos. Esta lens cobre como PROVAR CORREÇÃO ANTES DE PRODUÇÃO — reconciliação automática, property-based testing para invariantes financeiras, contract testing entre BCs, validação de decisões de agentes contra ground truth, e chaos engineering para failure modes. Na Mesh onde agentes IA tomam decisões financeiras (scoring, compliance) e processam fluxos monetários (antecipação, liquidação), testing não é quality assurance — é financial integrity infrastructure."
}

concepts: [
	{
		id:         "tv-financial-invariants"
		name:       "Invariantes Financeiras: Propriedades que NUNCA Podem Ser Violadas"
		nature:     "theoretical"
		role:       "framework"
		definition: "Invariante financeiro é uma propriedade do sistema que deve ser verdadeira em TODOS os estados, TODAS as transações, sem exceção. Violação de invariante = bug financeiro = perda de dinheiro ou violação regulatória. Invariantes fundamentais de contabilidade: (1) **conservation of money** — dinheiro não é criado nem destruído em transação. Soma de entradas = soma de saídas. Se operação de antecipação: valor cedido pelo fornecedor = valor pago pelo FIDC (menos deságio) + deságio retido pela plataforma. Total in = total out. (2) **double-entry consistency** — todo débito tem crédito correspondente. Ledger deve balancear: sum(débitos) = sum(créditos). Em qualquer momento: se não balanceia: bug. (3) **idempotency** — processar mesma operação 2x não duplica efeito financeiro. Se liquidação é executada, retry da mesma liquidação: no-op (não paga 2x). (4) **monotonic state progression** — operação financeira avança por estados sem retroceder ilegalmente. pendente → aprovada → liquidada → concluída. Não: concluída → pendente (sem operação explícita de estorno). (5) **precision preservation** — cálculos monetários não perdem precisão por arredondamento intermediário. R$100,00 ÷ 3 = R$33,33 + R$33,33 + R$33,34 (não R$33,33 × 3 = R$99,99 com R$0,01 perdido). Conceito de 'invariant-driven testing' (2023+): em vez de testar cenários específicos (dado input X, output deveria ser Y), testar propriedades que devem ser verdadeiras para QUALQUER input: 'para qualquer operação de antecipação: valor_cedido = valor_liquido + deságio.' Se propriedade viola para algum input: bug encontrado sem precisar enumerar todos os cenários."
		meshManifestation: "Na Mesh, invariantes financeiras: (1) **conservation em antecipação:** valor_face_recebível = valor_liquido_fornecedor + deságio_fidc + taxa_plataforma. Para toda operação, em todo estado: soma dos componentes = valor original. Se ≠: bug. (2) **double-entry no ledger:** para toda entrada no ledger: existe entrada oposta de mesmo valor. Débito em conta do FIDC = crédito em conta da operação. Débito em conta da operação = crédito em conta do fornecedor. Balance check: sum(all_entries) = 0. Se ≠ 0: ledger inconsistente = bug. (3) **idempotency de liquidação:** se liquidação é processada e sistema recebe retry (network timeout → automatic retry): segunda execução detecta que liquidação já ocorreu → no-op. Se não: fornecedor recebe 2x. (4) **state machine validity:** operação em estado 'liquidada' não pode transicionar para 'pendente.' Transitions definidas em state machine. Tentativa de transição inválida: rejeitada com erro. (5) **precision:** todos os cálculos monetários em representação decimal (não floating point). BigDecimal ou integer de centavos (R$48.750,00 = 4875000 centavos). Nunca: float/double para dinheiro (0.1 + 0.2 ≠ 0.3 em IEEE 754). (6) **arredondamento justo:** quando divisão produz fração de centavo: regra explícita (round half-up, ou banker's rounding). Diferença alocada a componente explícito (plataforma absorve ou fornecedor recebe). Nunca: centavos desaparecem silenciosamente."
		meshImplication: "Invariant implementation: (1) **codify invariants** — cada invariante documentado no mesh-spec como assertion testável. invariant-001: 'para toda operação: valor_face = valor_liquido + deságio + taxa.' invariant-002: 'sum(ledger_entries) = 0 at all times.' invariant-003: 'para toda operação: process(op) seguido de process(op) = process(op).' (2) **test each invariant** — para cada invariante: property-based test (tv-property-based-testing) que gera operações aleatórias e verifica propriedade. Unit test com edge cases (valores de centavo, valores máximos, divisões que produzem fração). Integration test que verifica invariante end-to-end. (3) **runtime assertion** — em produção: after cada transação, assertion verifica invariantes. conservation check: if valor_face ≠ sum(components): log error + alert + block transaction. ledger balance check: periodic (every N minutes): if sum(entries) ≠ 0: alert critical. (4) **money representation** — NEVER float/double. Always: integer cents (R$48.750,00 = 4875000) or decimal type (BigDecimal in Kotlin, Decimal in Python). Database: NUMERIC(15,2) para BRL (até R$9.999.999.999.999,99). Application: consistent type across all layers (API → service → database). (5) **rounding rules** — documented: 'when calculation produces fractional centavo: round half-up. When splitting amount: allocate remainder to last component (or to platform fee).' Rules in code as reusable function: roundMoney(value, mode='HALF_UP'). Not: each developer implementing own rounding. (6) **CLAUDE.md for agents:** 'all monetary calculations use Money type (integer centavos). Never use float for money. Division that produces fraction: use roundMoney(). Invariant: valor_face = valor_liquido + deságio + taxa MUST hold after every calculation.' Anti-pattern: monetary calculation using float — 0.1 + 0.2 = 0.30000000000000004 in JavaScript. Over 10.000 operations: accumulated error = R$X.XX disappeared or appeared from nowhere. IEEE 754 floating point is incompatible with financial precision."
		rationale: "Invariant-driven testing 2023+. Double-entry accounting fundamentals. IEEE 754 floating point precision issues are well-documented. Na Mesh, conservation of money and double-entry consistency are the 2 non-negotiable invariants. Property-based testing proves them for arbitrary inputs, not just known test cases."
	},
	{
		id:         "tv-property-based-testing"
		name:       "Property-Based Testing: Provar Propriedades para Qualquer Input, Não Apenas Cenários Conhecidos"
		nature:     "operational"
		role:       "method"
		reviewCadence: "semi-annual"
		definition: "Traditional testing: developer writes specific test cases (given input X, expect output Y). Covers known scenarios. Misses unknown edge cases. Property-based testing (PBT, Claessen/Hughes 2000, QuickCheck): developer defines property ('for any valid operation: conservation holds'). Framework generates hundreds/thousands of random valid inputs. Verifies property for each. If property violated: reports minimal failing case (shrinking). Advantages for financial systems: (1) finds edge cases developer didn't imagine (amount = R$0.01, amount = R$9.999.999.999,99, deságio = 0%, deságio = 99.99%). (2) proves property holds for distribution of inputs, not just specific cases. (3) shrinking produces minimal reproducer (helpful for debugging). Conceito de 'generator design for financial data' (2024+): PBT quality depends on generator quality. Generator for operation: { valor: randomCurrency(0.01, 10_000_000.00), taxa: randomPercent(0.01, 99.99), prazo: randomDays(1, 365), score: randomInt(0, 100) }. Generator must produce: valid edge cases (minimum, maximum), invalid cases (negative, zero, overflow), and realistic distributions (most values mid-range with edge cases). Conceito de 'oracle' (testing): for financial invariant, oracle is the invariant itself. 'conservation: valor_face = valor_liquido + deságio + taxa.' No need for pre-computed expected output — property IS the oracle."
		meshManifestation: "Na Mesh, PBT for financial invariants: (1) **conservation property:** forAll { op <- genOperation() }: op.valor_face == op.valor_liquido + op.deságio + op.taxa_plataforma. Generator: valor_face = randomCurrency(0.01, 10_000_000.00). Taxa = randomPercent(0.50, 5.00). Plataforma fee = randomPercent(0.10, 1.00). valor_liquido, deságio: derived by calculation. Assert: sum of parts = whole. Covers: centavos, large amounts, edge percentages, rounding scenarios. (2) **idempotency property:** forAll { op <- genOperation() }: process(op); process(op) == process(op). State after processing twice = state after processing once. Covers: all operation types, all amounts, network retry scenarios. (3) **state machine property:** forAll { transitions <- genTransitionSequence() }: every transition is valid per state machine definition. Invalid transitions: rejected. State after valid sequence: consistent. (4) **ledger balance property:** forAll { ops <- genOperationBatch(1, 100) }: after processing all ops: sum(ledger_entries) == 0. Covers: batches of 1-100 operations, various amounts, mixed types. (5) **scoring property:** forAll { features <- genFeatureSet() }: score(features) is in [0, 100] AND is deterministic (same features → same score). Does not test accuracy (that's backtesting) — tests consistency and bounds."
		meshImplication: "PBT implementation: (1) **framework:** Kotlin: kotest-property. Python: hypothesis. JavaScript: fast-check. Each: supports generators, shrinking, reproducible seeds. (2) **generators per domain type:** Money generator: range [0.01, 10_000_000.00], integer centavos internally. Percentage generator: range [0.01, 99.99], 2 decimal places. CNPJ generator: valid format + valid check digits. Date generator: business days only (exclude weekends, holidays — connects with temporal-modeling lens). Score generator: int [0, 100]. (3) **run count:** minimum 1000 iterations per property. For critical invariants (conservation, ledger balance): 10.000. CI: 1000 (fast). Nightly: 10.000 (thorough). (4) **seed persistence:** when PBT finds failure: seed is logged. Same seed reproduces same failure. Fix → re-run with same seed → verify fix. (5) **integration with CI:** property-based tests run in CI pipeline alongside unit tests. Failure: merge blocked. (6) **coverage of edge cases:** generators explicitly include: minimum (R$0.01), maximum (R$10M), zero (where valid), boundary values (score 0, 50, 100), rounding-trigger values (amounts that divide to fractional centavos). (7) **golden properties for Mesh:** document top 10 properties in mesh-spec. Each: name, description, generator, assertion. These are the financial constitution — immutable unless business rules change. Anti-pattern: 'we have 500 unit tests for the antecipação flow' — all with developer-chosen inputs. None test: R$0.01 antecipação (minimum), R$0 taxa (free?), R$9.999.999,99 (near overflow), taxa 0.001% (fractional centavo result). PBT with random generation: finds these edge cases automatically."
		dependsOn: ["tv-financial-invariants"]
		crossDependsOn: [{
			lensId:    "lens-ml-ai-systems-design"
			conceptId: "ml-model-versioning-reproducibility"
			context:   "ML defines model versioning and reproducibility — same input → same score with same model version. TV PBT tests this property: forAll { features }: score(features, model_v2.3) is deterministic. ML provides the model; TV proves its properties (determinism, bounded output, monotonicity where expected). ML is the system; TV proves its correctness."
		}]
		rationale: "Claessen/Hughes 2000: QuickCheck. Generator design 2024+. Na Mesh, PBT with 10.000 random operations proves conservation invariant holds across edge cases that no developer would enumerate manually. PBT found R$0.01 ÷ 3 = precision loss bug. Manual tests: never tested R$0.01."
	},
	{
		id:         "tv-reconciliation"
		name:       "Reconciliação Automática: Provar que o que o Sistema Diz Corresponde à Realidade"
		nature:     "operational"
		role:       "method"
		reviewCadence: "monthly"
		definition: "Reconciliação é o processo de comparar 2+ fontes de verdade e provar que concordam. Em sistemas financeiros: (1) **internal reconciliation** — sistema's own records agree with each other. Ledger entries balance. Operation total matches sum of line items. (2) **external reconciliation** — sistema's records agree with external source. Bank statement matches ledger. Tax records match operations. FIDC report matches carteira data. (3) **temporal reconciliation** — system's state at time T matches expected state based on operations processed up to T. End-of-day balance = opening balance + inflows - outflows. Conceito de 'continuous reconciliation' (2023+): não reconciliar 1x/mês (when discrepancy is found, 30 days of transactions to investigate). Reconciliar continuamente: after each transaction, after each batch, every hour, every day. Earlier detection = smaller scope of investigation. Conceito de 'reconciliation as test' (2024+): reconciliation checks are automated tests that run continuously. If discrepancy: alert (like test failure). Categories of discrepancy: (a) missing — record in source A but not in source B. (b) extra — record in source B but not in source A. (c) value mismatch — same record, different values. (d) status mismatch — same record, different status."
		meshManifestation: "Na Mesh, reconciliation layers: (1) **ledger self-reconciliation:** every N minutes: sum(all_ledger_entries) == 0. If ≠ 0: critical alert. Investigação imediata. Significa: money appeared or disappeared in accounting. (2) **operation-ledger reconciliation:** for each operation: sum of ledger entries for this operation == 0 (internal balance). operation.valor_face == ledger entries that compose it (valor_liquido credit to fornecedor + deságio debit from FIDC + taxa credit to plataforma). (3) **bank statement reconciliation:** daily: compare expected bank movements (from system: operations liquidated today) with actual bank statement (from banking partner API or file). Match: by operation reference + amount. Discrepancies: missing (system says liquidated, bank doesn't show), extra (bank shows movement system doesn't know), value mismatch. (4) **FIDC carteira reconciliation:** for each FIDC: system's carteira (sum of active operations) matches FIDC's own records. Monthly: FIDC receives report → compares with own system → discrepancies flagged. Automated: if FIDC provides API: reconcile programmatically. (5) **scoring reconciliation (backtesting):** model predicted score X for operation. After N months: actual outcome (defaulted or not). Compare: predicted probability vs actual default rate. Calibration: if predicted 5% default and actual is 15%: model miscalibrated → retrain. (6) **event reconciliation:** for each command processed: expected events were emitted. Command 'approve operation' → events: OperationApproved, LedgerEntryCreated, NotificationSent. If any missing: system inconsistency."
		meshImplication: "Reconciliation implementation: (1) **ledger self-check:** scheduled job: every 15 minutes. Query: SELECT SUM(amount) FROM ledger_entries. If ≠ 0: alert severity critical + page on-call + halt new operations until resolved. This is the canary — if ledger doesn't balance: something is fundamentally broken. (2) **operation-component check:** after each operation state change: verify sum of components. post-approve: assert valor_face == valor_liquido + deságio + taxa. Failure: block state change, log error, alert. (3) **bank reconciliation:** daily batch job: fetch bank statement (API or SFTP file). For each system-generated expected payment: match in bank statement by reference + amount (±R$0.01 tolerance for bank rounding). Unmatched system records: 'expected but not yet in bank' (may be timing — retry next day). If unmatched after 3 days: escalate. Unmatched bank records: 'in bank but not in system' → investigate (manual deposit? Error?). Dashboard: reconciliation status per day. (4) **reconciliation report:** daily email/notification to finance team: 'Reconciliação D-1: 147 operações matched. 0 discrepancies. Ledger balance: R$0.00 ✓.' If discrepancies: detail with operation IDs and amounts. (5) **scoring backtesting:** monthly: for cohort of operations scored N months ago: compare predicted PD (probability of default) with actual default rate. Report: calibration chart (predicted vs actual by score band). If miscalibration >2 percentage points for any band: flag for model review. (6) **reconciliation as CI test:** subset of reconciliation logic runs in CI with synthetic data: process N operations → verify ledger balances → verify component conservation. If fails: merge blocked. Production reconciliation: runs on real data continuously. Anti-pattern: manual reconciliation at month-end by finance team downloading spreadsheets — discrepancy discovered on day 30 when 1000 operations are suspect. Continuous automated reconciliation: discrepancy discovered in 15 minutes when 1 operation is suspect."
		dependsOn: ["tv-financial-invariants"]
		crossDependsOn: [{
			lensId:    "lens-observability-operational-intelligence"
			conceptId: "ooi-sli-slo-error-budget"
			context:   "OOI defines SLIs/SLOs for system health. TV reconciliation defines financial SLIs: 'ledger balance = 0 (always)', 'bank reconciliation match rate > 99.9% daily', 'scoring calibration within 2pp of actual.' These are financial health SLIs — not response time or uptime, but monetary correctness. OOI provides the monitoring infrastructure; TV defines the financial health metrics that need monitoring."
		}]
		rationale: "Continuous reconciliation 2023+. Reconciliation as test 2024+. Na Mesh, ledger self-check every 15 minutes: discrepancy detected in minutes, not days. Bank reconciliation daily: match rate >99.9% expected. Any unmatched after 3 days: investigated. Financial health is continuously proven, not periodically checked."
	},
	{
		id:         "tv-contract-testing"
		name:       "Contract Testing entre Bounded Contexts: Interfaces que Nunca Quebram Silenciosamente"
		nature:     "operational"
		role:       "method"
		reviewCadence: "semi-annual"
		definition: "Contract testing verifica que producer (BC que expõe interface) e consumer (BC que consome) concordam sobre o contrato da interface — schema, semantics, behavior. Se producer muda schema (adiciona campo required, remove campo, muda tipo): contract test detecta ANTES de deploy, não quando consumer quebra em produção. Tipos: **(1) consumer-driven contract testing** (Pact, 2013+): consumer defines expectations ('I expect field X as string, field Y as integer'). Producer runs consumer's expectations against its implementation. If producer violates any consumer expectation: test fails. Consumer drives the contract — producer must satisfy all consumers. **(2) schema compatibility testing** (Confluent, 2020+): event schemas verified for backwards compatibility (new version must be readable by old consumers). Forward, backward, and full compatibility modes. **(3) API contract testing** (OpenAPI/AsyncAPI validation): API implementation verified against published specification. Request/response validated against schema. Conceito de 'contract as safety net for evolution' (2024+): contract tests enable safe evolution — producer can change internals freely as long as contract is preserved. Consumer is protected from breaking changes. In Mesh: ECL bounded context changes scoring algorithm internals → contract test verifies that ScoreCalculated event still has same schema → NGR consumer is unaffected."
		meshManifestation: "Na Mesh, contract testing across BCs: (1) **ECL → NGR event contract:** ECL produces events (OperationApproved, ScoreCalculated). NGR consumes. Contract: event schema (fields, types, required/optional). Test: ECL schema change → verify NGR expectations still satisfied. If ECL removes field that NGR expects: test fails before deploy. (2) **ECL → FIDC reporting API contract:** ECL exposes API consumed by FIDC reporting. Contract: API response schema + semantics (field meanings, units, null behavior). Test: API change → verify FIDC reporting expectations. (3) **scoring service → ECL contract:** scoring service returns score + features + model_version. ECL expects: score (int 0-100), features (object), model_version (string semver). Test: if scoring service changes score to float or removes model_version: contract fails. (4) **Mesh → external banking API contract:** Mesh calls banking partner API for liquidação. Contract: request schema + expected response. Test: mock banking API with contract-defined responses. If banking API changes: contract defines expected behavior, mock updates, tests verify."
		meshImplication: "Contract testing implementation: (1) **event schema registry** — every event in event catalog (from EDA lens) has: schema definition (CUE, JSON Schema, or Avro). Schema registry validates: new version compatible with previous? Backward compatible: new schema can read old events (new fields optional, no removed required fields). (2) **Pact or equivalent** — for API contracts: consumer writes pact (expected request/response pairs). Provider verifies pact against implementation. CI: consumer PR runs consumer pact. Provider PR runs ALL consumer pacts. Provider change that breaks any consumer: blocked. (3) **schema evolution rules** — for events: (a) adding optional field: compatible (consumers ignore unknown fields). (b) adding required field: BREAKING — not allowed without consumer migration. (c) removing field: BREAKING. (d) changing field type: BREAKING. (e) renaming field: BREAKING (treat as remove old + add new). CI: schema compatibility check on every event schema change. (4) **contract test in CI** — every PR that changes: API response schema, event schema, inter-BC interface: contract tests run. Failure: merge blocked. Priority: same as unit tests (not optional, not 'nice-to-have'). (5) **contract for agent decisions** — scoring agent contract: input (feature set schema) → output (score schema: {score: int, model_version: string, features_used: string[], timestamp: datetime}). If agent output deviates from contract (missing field, wrong type): rejected by consumer. (6) **contract documentation** — each inter-BC contract in mesh-spec: producer, consumer, schema, compatibility rules, test location. Agente that modifies interface: check contract, run contract tests, update schema if needed. Anti-pattern: BCs communicate via shared database (no explicit contract). BC A changes column name → BC B breaks in production. No test caught it because there's no contract to test against."
		dependsOn: ["tv-financial-invariants"]
		crossDependsOn: [{
			lensId:    "lens-event-driven-architecture-patterns"
			conceptId: "eda-event-catalog"
			context:   "EDA defines event catalog as inventory of all events with schemas. TV contract testing uses catalog as the contract source: event schema in catalog IS the contract that producers must satisfy and consumers can rely on. EDA defines the catalog; TV proves that implementations conform to it. EDA is the specification; TV is the verification."
		}]
		rationale: "Pact 2013+. Schema compatibility Confluent 2020+. Contract as safety net 2024+. Na Mesh, ECL changing event schema without contract test: NGR breaks silently. With contract test: break detected in CI before deploy. Contract testing transforms evolution from 'scary change that might break consumers' to 'safe change verified against all consumers.'"
	},
	{
		id:         "tv-agent-decision-validation"
		name:       "Validação de Decisões de Agentes: Provar que IA Decide Corretamente"
		nature:     "operational"
		role:       "method"
		reviewCadence: "monthly"
		definition: "Agentes IA na Mesh tomam decisões com consequência financeira: scoring (determina taxa e aprovação), compliance (determina qualificação de fornecedor), alertas (determina se operação é flagged). Cada decisão deve ser validável contra ground truth ou business rules. Conceito de 'shadow mode / champion-challenger' (2023+): new model/agent runs in parallel with current (champion). Decisions compared. If challenger produces significantly different decisions: investigate before promoting. (1) **shadow mode:** challenger processes same inputs as champion. Output: logged but not acted upon. Comparison: are decisions aligned? Divergence report. (2) **champion-challenger A/B:** traffic split: 90% champion, 10% challenger. Both decisions acted upon. Compare outcomes over time. Better outcomes: promote challenger. (3) **backtesting:** apply new model to historical data with known outcomes. Compare: model's predictions vs actual outcomes. Calibration, discrimination (AUROC), precision, recall. Conceito de 'decision audit' (2024+): for each agent decision: record input, model version, output, confidence, features used. After outcome is known (operation defaulted or not): compare decision vs outcome. Aggregate: decision quality metrics per model version, per time period, per segment."
		meshManifestation: "Na Mesh, agent validation: (1) **scoring validation:** new scoring model (v2.4) before deployment: backtesting — apply v2.4 to last 6 months of operations with known outcomes. Compare: v2.4 scores vs actual default. Metrics: AUROC (discrimination), calibration (predicted PD vs actual), precision at approval threshold. If v2.4 AUROC > v2.3 AND calibration within 2pp: promote. If not: investigate. (2) **scoring shadow mode:** v2.4 runs in shadow: every new operation scored by both v2.3 (production) and v2.4 (shadow). Log: {operation_id, score_v2.3, score_v2.4, delta}. Dashboard: distribution of deltas. If >20% of operations have delta >10 points: significant divergence → investigate before promoting. (3) **compliance validation:** compliance agent checks documents against requirements. Validation: human sample review. Monthly: 50 random compliance decisions → human reviews same documents → agreement rate. Target: >95% agreement. If <90%: compliance agent is miscalibrated. (4) **alert validation:** alert agent flags anomalous operations. Validation: precision (of flagged operations, how many were genuinely anomalous?) and recall (of genuinely anomalous operations, how many were flagged?). Monthly review of flagged operations: 'was this flag correct?' False positive rate: target <20%. False negative: target <5% (critical — missed anomaly is worse than false alarm)."
		meshImplication: "Agent validation implementation: (1) **decision log** — every agent decision: {decision_id, agent_type, model_version, input_features: {...}, output: {score, decision, confidence}, timestamp, org_context}. Immutable. Retained for backtesting (years). Schema: standardized across agent types. (2) **outcome tracking** — for each scored operation: after 30/60/90/180 days: actual status (performing, late, defaulted). Link: decision_id → outcome. Enables: retrospective calibration analysis. (3) **backtesting pipeline** — automated: new model version → run against historical data → produce metrics report → compare with current version → flag if degradation. Can be triggered by: new model version, periodic schedule (monthly), or manual request. (4) **shadow mode infrastructure** — API/service: accepts operation → routes to champion + challenger → champion result returned to caller → challenger result logged. Comparison job: daily aggregate of champion vs challenger divergence. Dashboard: delta distribution, divergence %, by score band. (5) **human review sampling** — compliance: random 50 operations/month selected for human review. Blind: reviewer doesn't see agent's decision before own assessment. Compare: agreement rate. Statistical significance: 50 samples gives ±10% confidence at 95%. More for tighter bounds. (6) **promotion criteria** — document in mesh-spec: 'scoring model promotion requires: backtesting AUROC > current by ≥0.5%, calibration within 2pp across all score bands, shadow mode divergence <15% after 2 weeks.' Not: 'it looks better.' Quantitative criteria, documented, automated. (7) **regression detection** — production monitoring: rolling calibration (predicted PD vs actual, 30-day window). If calibration degrades >3pp from baseline: alert → investigate → potential revert to previous version. (8) **for agents generating code (Claude Code):** validation is different — output is code, not decision. Validation: CI tests (unit + property-based + contract + isolation). Code review by human for business logic. The code agent's 'decisions' are validated by the test suite it generates AND by the test suite that pre-exists. Anti-pattern: deploy new scoring model based on backtesting alone, without shadow mode. Backtesting uses historical data — may not reflect current distribution. Shadow mode catches distribution drift that backtesting misses."
		dependsOn: ["tv-financial-invariants", "tv-reconciliation"]
		crossDependsOn: [{
			lensId:    "lens-ai-agent-governance"
			conceptId: "aag-hitl-calibration"
			context:   "AAG defines HITL calibration — when human reviews agent decisions. TV agent validation defines HOW to validate: backtesting (historical accuracy), shadow mode (live comparison), human sampling (random blind review), production monitoring (rolling calibration). AAG says 'human must verify agent decisions above threshold'; TV says 'here's how to systematically verify decision quality: quantitative criteria, automated pipelines, documented promotion gates.' AAG is the governance principle; TV is the validation methodology."
		}]
		rationale: "Shadow mode / champion-challenger 2023+. Decision audit 2024+. Na Mesh, scoring model determines taxa and approval — wrong score = financial loss for FIDC or unfair taxa for fornecedor. Validation pipeline: backtesting → shadow mode → promotion criteria → production monitoring → regression detection. Each step: quantitative, automated, documented."
	},
	{
		id:         "tv-edge-case-testing"
		name:       "Testing de Edge Cases Financeiros: Os Cenários que Quebram Sistemas"
		nature:     "operational"
		role:       "heuristic"
		reviewCadence: "quarterly"
		definition: "Financial systems break at edges: minimum values, maximum values, zero, negative (if allowed), rounding boundaries, timezone crossings, leap years, month boundaries, division by zero, overflow, concurrent operations. Conceito de 'financial edge case catalog' (2023+): documented catalog of known edge cases that have broken financial systems historically. For each: description, test case, expected behavior. Catalog grows: every production incident adds edge case to catalog → test added → prevented forever."
		meshManifestation: "Na Mesh, edge case catalog: **Amount edges:** R$0.01 (minimum), R$0.00 (zero — valid? Depends on context), R$9.999.999.999,99 (maximum for NUMERIC(15,2)), negative amounts (never valid for antecipação — assert rejected). **Rounding edges:** R$100 ÷ 3 (produces R$33.333... — rounding allocates extra centavo), taxa 0.01% on R$100 = R$0.01 (minimum taxable amount), taxa 99.99% on R$100 (extreme but valid — edge). **Percentage edges:** 0.00% taxa (free? Valid?), 100.00% taxa (all deságio, R$0 to fornecedor — valid?), taxa that produces value_liquido < R$0.01 (rounding to zero — reject?). **Division edges:** 1 operation split among 3 recipients: how to allocate? Remainder: to whom? **Concurrency edges:** 2 approvals for same operation simultaneously (idempotency test). Bank debit + system credit happening out of order. **Time edges:** operation created at 23:59 on last business day of month. Settlement spanning month boundary. Leap year February 29 settlement date. **State edges:** operation in terminal state receives event (approve already-approved). Operation with dependencies (cancel operation that has dependent ledger entries). **Score edges:** score = 0 (minimum, always reject?), score = 100 (maximum, auto-approve?), score = threshold exactly (60 — approve or reject when threshold is ≥60?)."
		meshImplication: "Edge case testing approach: (1) **edge case catalog in mesh-spec** — documented list, grows continuously. Format: {id, category, description, input, expected_behavior, test_reference}. Example: {id: EC-001, category: rounding, description: 'R$100 ÷ 3 fornecedores', input: {valor: 10000, recipients: 3}, expected: {amounts: [3334, 3333, 3333], total: 10000}, test: tests/financial/rounding_test.kt#test_three_way_split}. (2) **each edge case has automated test** — catalog is not just documentation: each entry links to automated test. New entry without test: incomplete. (3) **incident-to-test pipeline** — production incident related to financial calculation: (a) investigate root cause. (b) add edge case to catalog. (c) write test that reproduces. (d) fix bug. (e) verify test passes. (f) deploy. Future: same edge case is prevented forever. (4) **PBT generators cover edges** — property-based test generators explicitly include edge values: minimum (0.01), maximum (9_999_999_999.99), zero, boundary values. Generators don't just produce random mid-range — they weight edges. (5) **score threshold boundary** — test: score = threshold exactly (e.g., 60). Behavior: documented rule ('≥60 approves'). Test: score 59 → reject, score 60 → approve, score 61 → approve. Boundary precision: not 'around 60' but 'exactly 60.' (6) **concurrent operation test** — test: submit same operation approval twice simultaneously. Expected: first succeeds, second returns idempotent response (not error, not duplicate). Implementation: optimistic locking or idempotency key. Test: verifiable in integration test with parallel threads. Anti-pattern: 'we tested with R$1000 and R$50.000 and it works.' But never tested R$0.01, R$0.00, R$10M, or R$100 ÷ 3. Edge cases are WHERE bugs live — mid-range works by default."
		dependsOn: ["tv-financial-invariants", "tv-property-based-testing"]
		rationale: "Financial edge case catalog 2023+. Na Mesh, edge case catalog: grows with every production incident. Each entry: documented + automated test. Over time: comprehensive coverage of financial edge cases. R$100 ÷ 3: tested. Score = threshold exactly: tested. Concurrent approval: tested. Leap year: tested."
	},
	{
		id:         "tv-test-strategy-by-layer"
		name:       "Estratégia de Testes por Camada: Pirâmide com Emphasis em Invariantes"
		nature:     "operational"
		role:       "method"
		reviewCadence: "semi-annual"
		definition: "Test pyramid (Cohn 2009): many unit tests (fast, isolated) → fewer integration tests (slower, real dependencies) → fewest e2e tests (slowest, full system). For financial systems: modified pyramid with financial emphasis: **(1) unit tests** — business logic: money calculations, state machine transitions, validation rules, scoring functions. Fast. Isolated. Cover all edge cases. Run on every build. **(2) property-based tests** — financial invariants: conservation, idempotency, ledger balance, state machine validity. Random inputs. Run on every build (1000 iterations) + nightly (10.000). **(3) contract tests** — inter-BC interfaces: event schemas, API contracts. Run on every build. Detect integration issues without running full system. **(4) integration tests** — real database, real event bus, real API calls between services (within test environment). Reconciliation tests. Tenant isolation tests. Run on every build (subset) + nightly (full). **(5) e2e tests** — full workflow: create fornecedor → submit operation → score → approve → liquidate → reconcile. Run nightly or per-deploy. Slow but comprehensive. **(6) agent validation tests** — backtesting pipeline, shadow comparison, human review sampling. Run: per model version + monthly. Conceito de 'test confidence for financial systems' (2024+): test suite must give confidence level: 'I can deploy with confidence that: money calculations are correct (property-based), interfaces are compatible (contract), system processes correctly end-to-end (e2e), and agent decisions are calibrated (validation).' Missing any layer: confidence gap."
		meshManifestation: "Na Mesh, test strategy: (1) **unit (run: every build, <2 min):** money arithmetic (roundMoney, splitAmount, calculateTaxa). State machine transitions (valid + invalid). Validation rules (CNPJ format, amount range, date validity). Score calculation (deterministic, bounded). ~200-500 tests at MVP. (2) **property-based (run: every build 1k, nightly 10k):** conservation invariant. Idempotency invariant. Ledger balance invariant. State machine completeness. Score determinism + bounds. ~10-20 properties. (3) **contract (run: every build, <1 min):** ECL event schemas vs NGR expectations. API response schemas vs consumer expectations. Scoring service output vs ECL expectations. ~20-50 contract tests at MVP. (4) **integration (run: every build subset, nightly full, <10 min):** operation flow: create → approve → liquidate with real PostgreSQL + real event bus. Tenant isolation: cross-tenant access denied (from MT lens). Reconciliation: ledger balance after N operations. ~50-100 integration tests. (5) **e2e (run: nightly or per-deploy, <30 min):** complete happy path: fornecedor creates operation → construtora approves → FIDC funds → liquidation → reconciliation. Complete error paths: reject, cancel, timeout, duplicate. ~10-20 e2e scenarios. (6) **agent validation (run: per model + monthly):** backtesting, shadow comparison, human sample review. ~3-5 validation pipelines."
		meshImplication: "Test strategy implementation: (1) **CI pipeline structure:** PR build: unit + property (1k) + contract + integration (subset) + tenant isolation. Time: <5 minutes. Failure: merge blocked. Nightly: property (10k) + integration (full) + e2e (all scenarios). Time: <30 minutes. Failure: alert team. (2) **coverage targets:** unit: >90% line coverage for financial calculation modules. Property: 100% of documented invariants have property test. Contract: 100% of inter-BC interfaces have contract test. Integration: 100% of critical paths (happy + primary error paths). E2e: top 5 user workflows. (3) **test data management:** synthetic data generators: reusable across test types. Generators: valid operations, valid fornecedores, valid construtoras with realistic distributions. Shared: unit, property, integration, e2e use same generators (configured differently). (4) **flaky test zero-tolerance** — flaky test (passes sometimes, fails sometimes): treated as bug. Investigate. Fix. If intermittent: isolate cause (timing, concurrency, test order dependency). Financial system cannot tolerate 'sometimes passes' — that means 'sometimes money is wrong.' (5) **mutation testing (optional, advanced)** — after high unit coverage: mutation testing verifies test quality. Mutate code (change + to -, remove condition): tests should fail. If mutant survives (tests don't catch): test gap identified. For financial calculations: mutation survival rate target <5%. (6) **test for agents:** CLAUDE.md: 'when implementing financial logic: write property-based test for invariants. When modifying inter-BC interface: run contract tests. When creating new endpoint: add tenant isolation test. Minimum: unit test for every function that touches Money type.' Anti-pattern: 100% line coverage but 0 property-based tests — all tests are 'given R$1000 at 2.5% for 30 days: expect R$979.17.' Tests pass. But: R$0.01 at 99.99% for 1 day → precision loss → no test catches it. Line coverage ≠ edge case coverage."
		dependsOn: ["tv-financial-invariants", "tv-property-based-testing", "tv-reconciliation", "tv-contract-testing", "tv-agent-decision-validation", "tv-edge-case-testing"]
		rationale: "Cohn 2009: test pyramid. Test confidence 2024+. Na Mesh, modified pyramid: property-based tests are as fundamental as unit tests (not optional). Contract tests protect BC boundaries. Agent validation protects AI decisions. Every layer: addresses different failure mode. All layers: give confidence to deploy financial system."
	},
	{
		id:         "tv-chaos-and-failure-testing"
		name:       "Chaos Engineering e Failure Testing: O que Acontece Quando as Coisas Quebram"
		nature:     "operational"
		role:       "method"
		reviewCadence: "quarterly"
		definition: "Chaos engineering (Netflix 2011, Principles of Chaos Engineering 2018): deliberately inject failures to verify system handles them correctly. For financial systems: failure handling is critical — partial failure that leaves money in inconsistent state is worse than clean failure that rolls back. Concepto de 'financial failure modes' (2024+): (1) **network failure mid-transaction** — bank API call succeeds but response is lost. System doesn't know if payment was made. Retry: might double-pay. Don't retry: might not pay. Solution: idempotency key + reconciliation. (2) **partial batch failure** — 50 operations approved in batch. 48 succeed, 2 fail (validation, timeout). What happens to the 2? Retried? Rolled back? Reported? (3) **database failure during write** — ledger entry partially written. On recovery: is ledger consistent? Solution: transaction isolation (ACID). (4) **event loss** — operation approved, event published, consumer doesn't receive (broker failure). System: operation is approved. Consumer: doesn't know. Solution: outbox pattern, event replay. (5) **clock skew** — 2 services with different clock readings. Timestamps disagree. Settlement date calculated differently. Solution: NTP synchronization, UTC everywhere, tolerance for small skew."
		meshManifestation: "Na Mesh, chaos scenarios to test: (1) **bank API timeout after sending payment** — test: inject timeout after sending POST to bank API. Verify: system records 'payment sent, response unknown.' Reconciliation: next bank statement check matches. No duplicate payment on retry (idempotency key). (2) **database failure during ledger write** — test: inject database failure mid-transaction. Verify: no partial ledger entries (transaction rolled back). Ledger balance unchanged. Operation status: unchanged (not partially updated). (3) **event broker unavailable** — test: stop event broker during operation approval. Verify: transactional outbox captures event. When broker recovers: event delivered. Consumer receives event (possibly delayed). No lost events. (4) **scoring service timeout** — test: inject timeout in scoring service. Verify: operation goes to 'scoring failed' status (not 'scored with default value'). Retry logic: attempts N times with backoff. After N failures: alert + manual review queue. (5) **concurrent approval race condition** — test: 2 simultaneous approve requests for same operation. Verify: exactly 1 succeeds (optimistic locking or database constraint). Other: receives conflict response. No duplicate approval. No inconsistent state."
		meshImplication: "Chaos testing implementation: (1) **staged approach** — don't start with production chaos. Stage 1: chaos in integration tests (inject failures in test environment). Stage 2: chaos in staging (inject in environment that mirrors production). Stage 3 (mature): chaos in production with safeguards (feature flags, automatic rollback). For Mesh MVP: Stage 1 only. (2) **failure injection mechanisms** — test environment: mock/stub external dependencies (bank API, event broker) with configurable failure modes (timeout, error, partial success). Framework: toxiproxy (network failures), testcontainers (database failure simulation), custom mocks (API failure). (3) **verify correct failure handling** — for each chaos scenario: define expected behavior BEFORE injecting failure. 'When bank API times out: system records unknown status, schedules reconciliation, does not retry payment without idempotency check.' Run scenario. Verify expected behavior. If different: fix handling, not just test. (4) **runbook per failure mode** — for each known failure: documented runbook in mesh-spec. Runbook: what happens, what system does automatically, what human must do if automated recovery fails. Example: 'Bank API timeout: system records unknown. Automated: next reconciliation cycle (15 min) checks bank. If matched: status updated. If not matched after 3 cycles: alert finance team. Manual: verify with bank, update status manually.' (5) **game days** — quarterly: simulate failure scenario. Team walks through: automated response, monitoring alerts, manual runbook. Verify: runbook is current, monitoring works, team knows what to do. Not chaos in production — tabletop exercise. (6) **idempotency as foundation** — every operation that touches money: idempotent. Idempotency key: unique per operation attempt. System checks: 'have I processed this key before?' If yes: return cached result. If no: process and store result with key. Prevents: double payment, double approval, double ledger entry. Implementation: idempotency_key column in operations table with unique constraint. Anti-pattern: no failure testing until production incident → scramble to fix → patch handling → no test added → same failure class occurs again. Proactive chaos: find failures before users do."
		dependsOn: ["tv-financial-invariants", "tv-reconciliation"]
		rationale: "Netflix 2011: chaos engineering. Financial failure modes 2024+. Na Mesh, bank API timeout is inevitable (networks fail). Question is not 'will it happen?' but 'when it happens, does the system handle it correctly?' Chaos testing: proves handling BEFORE production failure occurs."
	},
	{
		id:            "tv-testing-review"
		name:          "Revisão de Testes: Inventário Periódico de Cobertura e Confiança"
		nature:        "operational"
		role:          "method"
		reviewCadence: "quarterly"
		definition:    "Inventário periódico: (1) invariants — all documented? All have property tests? Any new invariant discovered? (2) PBT — all properties passing at 10k? Any new properties needed? (3) reconciliation — ledger balance check running? Bank recon running? Match rate >99.9%? (4) contracts — all inter-BC interfaces covered? Any new interfaces without contract? (5) agent validation — backtesting current? Shadow mode running for new models? Human sampling done? Calibration within bounds? (6) edge cases — catalog updated? Any production incidents that should add edge cases? All catalog entries have tests? (7) strategy — pyramid balanced? Unit >90% coverage for financial logic? CI time <5 min? (8) chaos — chaos scenarios tested? Runbooks current? Game day conducted?"
		meshManifestation: "Na Mesh: revisão trimestral. CI pipeline health + coverage metrics + reconciliation status."
		meshImplication: "Quarterly (1.5h): (a) invariant check — list all invariants in mesh-spec. Each has property test? Run with 10k iterations: all pass? Any new business rule that implies new invariant? (b) reconciliation health — ledger balance: has it triggered alert in last quarter? Bank recon match rate: >99.9%? Discrepancies resolved? Average resolution time? (c) contract coverage — list all inter-BC interfaces. Each has contract test? Any new interface from recent development without contract? Add. (d) agent validation — latest model: backtested? Shadow mode conducted? Calibration metrics within bounds? Human sample review: agreement rate >95%? (e) edge case catalog — any production incidents in quarter? Each added to catalog? Test written? (f) CI health — build time <5 min? Flaky tests: zero? Coverage: financial logic >90%? (g) chaos — any new failure scenario identified? Tested? Runbook written/updated? (h) confidence assessment — can I deploy today with confidence that money is correct? If not: what's the gap? Address."
		dependsOn: ["tv-financial-invariants", "tv-property-based-testing", "tv-reconciliation", "tv-contract-testing", "tv-agent-decision-validation", "tv-edge-case-testing", "tv-test-strategy-by-layer", "tv-chaos-and-failure-testing"]
		rationale: "Test suites degrade: new feature without test, new BC without contract, new invariant without property test, new edge case without catalog entry. Quarterly review: systematic gap identification. Every gap closed: confidence increases."
	},
]

reasoningProtocol: [
	{
		question:  "Os invariantes financeiros fundamentais (conservation, double-entry, idempotency) estão codificados e testados com property-based testing?"
		reveals:   "Se correção financeira é provada para arbitrary inputs — ou se apenas cenários conhecidos são testados (e edge cases são blind spots)."
		rationale: "Invariant-driven testing 2023+. Property-based: proves invariant for distribution of inputs, not just known cases."
	},
	{
		question:  "Reconciliação automática roda continuamente? Ledger balance verificado every 15 min? Bank reconciliation diária?"
		reveals:   "Se discrepâncias são detectadas em minutos — ou se são descobertas no month-end manual quando 1000 operações são suspeitas."
		rationale: "Continuous reconciliation 2023+. 15-minute detection vs 30-day detection: vastly different investigation scope."
	},
	{
		question:  "Contract tests existem para todas as interfaces entre BCs? Mudança de schema quebra CI?"
		reveals:   "Se evolução é segura (contract verifica compatibility) — ou se producer muda e consumer quebra silenciosamente em produção."
		rationale: "Contract as safety net 2024+. Contract test: evolve with confidence."
	},
	{
		question:  "Decisões de agentes IA (scoring, compliance) são validadas via backtesting + shadow mode + human review?"
		reveals:   "Se qualidade de decisão é medida e governada — ou se modelo é deployed based on 'looks good on training data.'"
		rationale: "Shadow mode 2023+. Decision audit 2024+. Backtesting + shadow + production monitoring = validation pipeline."
	},
	{
		question:  "Edge case catalog existe e cresce com cada incidente? R$0.01, score=threshold, concurrent approval todos testados?"
		reveals:   "Se edge cases são systematically covered — ou se apenas happy path é testado."
		rationale: "Edge cases are WHERE bugs live. Catalog + incident-to-test pipeline: coverage grows monotonically."
	},
	{
		question:  "Chaos testing verifica failure handling? Bank timeout, database failure, event loss — handled correctly?"
		reveals:   "Se sistema é resilient by verification — ou se resilience is assumed and first production failure is a surprise."
		rationale: "Netflix 2011: chaos engineering. Financial failure modes 2024+. Test failure handling before failure handles you."
	},
	{
		question:  "Money é representado como integer centavos ou BigDecimal (NUNCA float)? Arredondamento tem regra explícita documentada?"
		reveals:   "Se precision é preservada by design — ou se IEEE 754 float errors are silently accumulating."
		rationale: "0.1 + 0.2 ≠ 0.3 in float. × 10.000 operations = accumulated error. Integer centavos: exact arithmetic."
	},
]

meshExamples: [
	{
		id:       "ex-conservation-invariant-pbt"
		scenario: "Developer implements antecipação calculation: valor_liquido = valor_face - deságio - taxa_plataforma. Manual tests pass with R$1.000 at 2.5% taxa and 0.5% plataforma fee. QA approves. In production: operation for R$33,33 with taxa 3.333% produces valor_liquido = R$32,21 but deságio + taxa = R$1,11 + R$0,02 = R$1,13. R$33,33 - R$1,13 = R$32,20 ≠ R$32,21. R$0,01 discrepancy. Over 10.000 operations/month: R$100/month of unaccounted centavos."
		analysis: "Root cause: rounding applied to each component independently. deságio rounds to R$1,11. taxa rounds to R$0,02. Sum of rounded components: R$1,13. valor_face - sum = R$32,20. But valor_liquido was calculated by rounding (valor_face × (1-taxa-plataforma)) directly = R$32,21. Two different rounding paths produce different results. Manual tests: R$1.000 doesn't trigger this (clean division). R$33,33 with fractional taxa: triggers."
		recommendation: "(1) Property-based test that would have caught this: property('conservation') { forAll(genOperation()) { op -> val sum = op.valor_liquido + op.deságio + op.taxa assertEquals(op.valor_face, sum, 'conservation violated: face=${op.valor_face} sum=${sum}') } }. With generator producing R$33,33 at 3.333%: property violated. PBT shrinks to minimal failing case. (2) Fix: single rounding path. Calculate deságio = round(valor_face × taxa_rate). taxa = round(valor_face × plataforma_rate). valor_liquido = valor_face - deságio - taxa. Valor_liquido is derived (not independently rounded). Conservation holds by construction. (3) Alternative: 'last component absorbs remainder.' deságio = round(valor_face × taxa_rate). taxa = round(valor_face × plataforma_rate). valor_liquido = valor_face - deságio - taxa. This always conserves (valor_liquido is whatever remains). (4) Add to edge case catalog: EC-017: 'fractional taxa rate producing different results via independent vs sequential rounding.' Test: {valor: 3333, taxa: 3.333%, plataforma: 0.50%}. Expected: conservation holds. (5) Add property to CI: runs 10.000 iterations on every build. Catches this class of bug for any amount × rate combination. (6) CLAUDE.md: 'monetary calculations: NEVER round intermediate results independently. Calculate components sequentially with last-component-absorbs-remainder pattern. Property test: conservation invariant must pass.'"
		principlesApplied: ["ax-01", "ax-06"]
		assumptions: [
			"R$0.01 per operation is significant at scale — 10.000 ops/month × R$0.01 = R$100/month = R$1.200/year",
			"single rounding path eliminates all conservation violations — verify with PBT (10.000 iterations)",
			"last-component-absorbs-remainder is accounting standard — verify with accountant",
			"PBT generator produces edge values like R$33.33 at 3.333% — generator must include fractional percentages",
		]
		rationale: "Property-based testing finds bugs that no developer would enumerate as test case. R$33.33 at 3.333%: no developer writes this test manually. PBT generates it randomly. Invariant catches it. Bug fixed before production. R$1.200/year of discrepancy: prevented."
	},
	{
		id:       "ex-bank-reconciliation-discrepancy"
		scenario: "Daily bank reconciliation finds: system shows 147 liquidações for R$2.3M total. Bank statement shows 146 payments for R$2.27M. 1 operation (R$28.500) is in system as 'liquidated' but not in bank statement."
		analysis: "Possible causes: (1) bank processed but statement not yet updated (timing — bank settles D+1). (2) bank rejected payment (insufficient funds, invalid account) but rejection notification not yet received. (3) system marked as liquidated before bank confirmation (optimistic — should not happen for financial operations). (4) bank API returned success but payment actually failed (rare API bug)."
		recommendation: "(1) Reconciliation system action: flag operation #4567 as 'unmatched — pending bank confirmation.' Status: not changed yet (still 'liquidated' in system). (2) Day 2: re-run reconciliation. If now matched: resolved (was timing). Update flag to 'matched D+1.' (3) Day 3: still unmatched. Escalate: alert finance team. Auto-query bank status API: GET /payments/{reference}. Bank response: 'payment rejected — invalid beneficiary account.' (4) System action: revert operation #4567 status from 'liquidated' to 'liquidation failed.' Create reversal ledger entries (debit fornecedor, credit FIDC). Notify fornecedor: 'Liquidação falhou — conta bancária inválida. Atualize sua conta bancária e resubmeta.' Notify construtora: 'Operação #4567 — liquidação falhou. Detalhes: [reason].' (5) Prevention: bank API integration should poll for payment status after submission (not just fire-and-forget). T+1h: check status. If rejected: immediately revert. Don't wait for daily reconciliation. (6) Reconciliation improvement: add check: 'operations marked liquidated >24h without bank match → auto-query bank status.' Proactive, not reactive. (7) Test: chaos test — inject bank rejection after liquidation submission. Verify: system detects in next reconciliation cycle, reverts correctly, notifications sent."
		principlesApplied: ["ax-01", "ax-06"]
		assumptions: [
			"bank provides status query API — if not: rely on daily statement (slower detection)",
			"reversal ledger entries are straightforward — depends on how far downstream the liquidation has propagated",
			"fornecedor notification is appropriate — yes, they need to fix bank account",
			"24h auto-query threshold is appropriate — may need to be shorter for high-value operations",
		]
		rationale: "Continuous reconciliation 2023+. Daily reconciliation caught discrepancy in 24h. Without: discovered at month-end (30 days). Proactive bank status polling: catches in 1h. Each layer of reconciliation: faster detection, smaller scope."
	},
	{
		id:       "ex-scoring-shadow-mode"
		scenario: "Data science develops scoring model v2.4 with new features (payment history depth, seasonal adjustment). Backtesting shows AUROC improvement from 0.72 (v2.3) to 0.76 (v2.4). Team wants to deploy immediately."
		analysis: "Backtesting is necessary but not sufficient: (1) backtesting uses historical data — distribution may have shifted since training period. (2) backtesting doesn't test production integration (latency, error handling, feature pipeline). (3) AUROC improvement of 0.04 is meaningful but needs production validation. If v2.4 has calibration issue not visible in backtesting (predicts 5% default but actual is 12%): FIDC loses money."
		recommendation: "(1) Don't deploy directly. Follow promotion pipeline: **Step 1 — Backtesting (done):** AUROC 0.72 → 0.76 ✓. Calibration: within 2pp across all score bands ✓. Precision at threshold 60: improved ✓. Gate: passed. **Step 2 — Shadow mode (2 weeks):** v2.4 runs alongside v2.3 on all new operations. Both score every operation. Only v2.3 result is used for decisions. v2.4 results: logged. Daily comparison: delta distribution (v2.4 score - v2.3 score). Expected: most deltas small (±5 points). Investigate: deltas >15 points (20 operations with large divergence — why?). If divergence is explainable (new features capturing signal v2.3 missed): acceptable. If divergence is random/unexplainable: investigate model issue. Gate: divergence <15% of operations with delta >10, all large deltas explained. **Step 3 — Champion-challenger (optional, 4 weeks):** 90% v2.3, 10% v2.4. Both decisions acted upon. After 30-90 days: compare actual outcomes for v2.4 scored operations vs v2.3. If v2.4 calibration is better: promote. Gate: v2.4 calibration within 2pp of predicted. **Step 4 — Full rollout:** v2.4 becomes production champion. v2.3 available for rollback. **Step 5 — Production monitoring:** rolling 30-day calibration for v2.4. If degrades >3pp from backtesting: alert → investigate → potential rollback to v2.3. (2) Total timeline: 2-6 weeks from backtesting to full rollout. Slower than 'deploy tomorrow' but: confident that v2.4 performs in production, not just on historical data. (3) Document promotion criteria in mesh-spec: quantitative gates at each step. Agent/developer: follows documented pipeline, not ad-hoc 'looks good.'"
		principlesApplied: ["ax-01", "ax-06", "dp-01"]
		assumptions: [
			"2-week shadow mode is sufficient to detect issues — depends on operation volume (need ≥200 operations for meaningful comparison)",
			"champion-challenger with 10% is safe — 10% exposure limits risk while providing real outcome data",
			"AUROC 0.04 improvement is worth the deployment effort — yes, meaningful for credit scoring",
			"rolling 30-day calibration catches drift — depends on volume; low-volume: 90-day window",
		]
		rationale: "Shadow mode 2023+. Champion-challenger for credit scoring is industry practice. Backtesting alone: tests on past data. Shadow mode: tests on present data without risk. Champion-challenger: tests with real outcomes. Each step: higher confidence. Skip steps: higher risk of model deployed that looks good on paper but fails in production."
	},
	{
		id:       "ex-contract-test-prevents-bc-breakage"
		scenario: "ECL team modifies OperationApproved event: renames field 'approved_at' to 'approval_timestamp' for naming consistency. PR passes all ECL unit tests. Deployed. NGR consumer (which reads approved_at from event) starts throwing NullPointerException — field doesn't exist in new events."
		analysis: "Breaking change in event schema: field renamed = field removed (for consumer) + new field added. Consumer (NGR) expected 'approved_at'. Producer (ECL) now emits 'approval_timestamp'. No contract test existed between ECL and NGR for this event. ECL's unit tests don't test NGR's expectations. Break: silent until production consumer failure."
		recommendation: "(1) Prevention: consumer-driven contract test. NGR registers expectation: 'OperationApproved event MUST contain field approved_at (datetime).' ECL runs NGR's expectations against its event schema on every PR. ECL renames to approval_timestamp → NGR's expectation for approved_at fails → ECL PR blocked. (2) Resolution: ECL must either: (a) keep approved_at (don't rename — backwards compatible). (b) add approval_timestamp AND keep approved_at (deprecate old, support both during migration). (c) coordinate with NGR: NGR updates to read approval_timestamp → both deploy together. (3) Schema compatibility rules: (a) adding optional field: safe. (b) removing field: BREAKING — contract test catches. (c) renaming field: BREAKING (= remove old + add new). (d) changing type: BREAKING. (4) Contract test setup: NGR defines pact file: 'I expect OperationApproved to have: {operation_id: uuid, status: string, approved_at: datetime, approver_id: uuid}.' ECL CI: runs all consumer pacts against current event schema. Pact violation: merge blocked. (5) Schema registry enforcement: event catalog (EDA lens) with schema version. New version: compatibility check against previous version. Backward incompatible change: blocked without explicit migration plan. (6) CLAUDE.md: 'when modifying event schema: check event catalog for consumers. Run contract tests. If field is renamed or removed: this is BREAKING — add new field, deprecate old, support both for migration period.'"
		principlesApplied: ["ax-01", "ax-06"]
		assumptions: [
			"consumer-driven contract testing is implementable with Pact or equivalent — yes, mature tooling exists",
			"NGR is the only consumer of OperationApproved — may have multiple consumers; all must register expectations",
			"migration period for deprecated fields is feasible — yes, support both for N releases then remove old with notice",
			"schema registry catches incompatible changes — requires discipline in updating registry; CI enforcement helps",
		]
		rationale: "Contract as safety net 2024+. Without contract test: ECL's 'innocent rename' breaks NGR in production. With contract test: break caught in CI before merge. Cost: 2 hours to set up contract tests for this event. Benefit: prevents class of silent cross-BC breaks permanently."
	},
]

principleIds: ["ax-01", "ax-06", "dp-01"]

relatedLenses: [
	{
		lensId:   "lens-observability-operational-intelligence"
		relation: "complementsWith"
		context:  "OOI detecta problemas em produção (monitoring, alerting, SLIs). TV prova correção ANTES de produção (testing, validation, reconciliation). OOI is reactive detection; TV is proactive prevention. Together: bugs caught before production (TV) + bugs that slip through caught quickly in production (OOI). TV reconciliation runs in production but is validation (proving correctness), not monitoring (detecting anomalies)."
	},
	{
		lensId:   "lens-event-driven-architecture-patterns"
		relation: "complementsWith"
		context:  "EDA defines event catalog with schemas. TV contract testing uses catalog as contract source: producer must emit events conforming to catalog schema, consumer relies on schema. TV tests that both sides conform. EDA is the specification; TV is the verification."
	},
	{
		lensId:   "lens-ml-ai-systems-design"
		relation: "complementsWith"
		context:  "ML defines model training, versioning, deployment. TV agent validation defines how to prove model correctness: backtesting, shadow mode, champion-challenger, production monitoring. ML builds the model; TV proves it works."
	},
	{
		lensId:   "lens-ai-agent-governance"
		relation: "complementsWith"
		context:  "AAG governs agent decisions (HITL, escalation). TV validates decision quality (backtesting, calibration, human sample review). AAG says 'escalate above threshold'; TV says 'here's how to determine if threshold is correct and if decisions below threshold are accurate.'"
	},
	{
		lensId:   "lens-technical-debt-as-strategic-instrument"
		relation: "complementsWith"
		context:  "TD covers code quality and debt management. TV covers financial correctness specifically. Missing unit test is code debt (TD). Missing conservation invariant test is financial integrity risk (TV). TV is higher severity: financial bug > code smell."
	},
	{
		lensId:   "lens-distributed-systems-design"
		relation: "complementsWith"
		context:  "DSD defines distributed system patterns (idempotency, eventual consistency, outbox). TV chaos testing verifies these patterns work under failure: network partition → idempotency prevents double payment? Event broker failure → outbox preserves events? DSD is the pattern; TV proves the pattern works."
	},
	{
		lensId:   "lens-multi-tenancy-and-identity-architecture"
		relation: "complementsWith"
		context:  "MT defines tenant isolation. TV includes isolation testing as CI gate: every PR verified for cross-tenant access prevention. MT defines the isolation architecture; TV proves it holds."
	},
]

limitations: [
	{
		description: "Property-based testing finds edge cases but doesn't guarantee complete coverage — generator may miss certain input distributions."
		alternative: "Combine PBT with: explicit edge case catalog (known problematic values), mutation testing (verify test quality), and production reconciliation (catch what tests miss). No single technique is sufficient; layered approach covers gaps."
		rationale: "PBT is probabilistic, not exhaustive. Layered testing: PBT catches random edges, catalog catches known edges, reconciliation catches production edges."
	},
	{
		description: "Shadow mode for scoring requires 2x compute (both models score every operation) and sufficient operation volume for meaningful comparison."
		alternative: "Shadow mode duration: proportional to volume. High volume (100 ops/day): 1-2 weeks sufficient. Low volume (10 ops/day): 4-6 weeks. If volume too low for shadow: extend backtesting with bootstrap sampling to simulate more scenarios."
		rationale: "Statistical significance requires volume. Low volume: extend duration or supplement with backtesting."
	},
	{
		description: "Continuous reconciliation (every 15 min) creates database load — aggregation queries on ledger table compete with operational queries."
		alternative: "Reconciliation on read replica (not primary). Or: materialized view refreshed periodically (eventual — 15 min delay acceptable). Or: event-sourced balance maintained incrementally (no full table scan needed)."
		rationale: "Reconciliation must not degrade operational performance. Read replica or materialized view: isolation."
	},
	{
		description: "Contract testing between BCs requires organizational discipline — every consumer must register expectations, every schema change must check contracts."
		alternative: "CI enforcement: PR that modifies event schema → automated check against registered consumer contracts. Without consumer contract: warning (not block — consumer may not have registered yet). Over time: contract coverage tracked as metric, target >90%."
		rationale: "Contract testing is cultural as much as technical. CI enforcement + coverage metric: drives adoption without blocking velocity."
	},
	{
		description: "Chaos engineering in financial systems carries risk — even in test environments, injected failures may have unexpected cascading effects."
		alternative: "Start with chaos in isolated test environments (not staging, not production). Graduate to staging when confident. Production chaos: only for mature systems with comprehensive monitoring and instant rollback. For Mesh MVP: chaos in integration tests only."
		rationale: "Staged chaos adoption. Test environment first. Production chaos: years away for financial startup."
	},
]

rationale: "Sistemas financeiros têm tolerância zero a erro — um centavo perdido por arredondamento × 10.000 operações = dinheiro desaparecido. Na Mesh onde agentes IA tomam decisões financeiras e processam fluxos monetários, testing não é QA — é financial integrity infrastructure. Esta lens operacionaliza: invariantes financeiras codificados e testados (conservation, double-entry, idempotency, monotonic state, precision — invariant-driven 2023+), property-based testing para provar invariantes para arbitrary inputs (Claessen/Hughes 2000, generator design 2024+), reconciliação automática contínua entre ledger, banco, e carteira (continuous reconciliation 2023+, reconciliation as test 2024+), contract testing entre BCs para evolução segura (Pact 2013+, schema compatibility Confluent 2020+, contract as safety net 2024+), validação de decisões de agentes via backtesting + shadow mode + human review (shadow mode 2023+, decision audit 2024+), edge case catalog que cresce com cada incidente (financial edge case catalog 2023+), estratégia de testes em pirâmide com emphasis em invariantes (Cohn 2009, test confidence 2024+), e chaos engineering para verificar failure handling (Netflix 2011, financial failure modes 2024+). Específica para sistemas financeiros onde bug = perda de dinheiro, não degradação de UX."

}
