package lenses

import "github.com/sw6n297mn8-maker/mesh-spec/architecture/artifact-schemas:artifact_schemas"

designTokensAndSystematicComposition: artifact_schemas.#AnalyticalLens & {
id:     "lens-design-tokens-and-systematic-composition"
name:   "Design Tokens e Composição Sistemática"

purpose: "Orientar decisões sobre como usar design tokens como sistema de composição — consistência visual, themability e manutenção escalável."
status: "draft"

trigger: {
	conditions: [
		"a decisão envolve como definir design tokens (spacing, colors, typography, sizing, shadows, radii) como foundation do design system",
		"a decisão envolve como garantir consistência visual entre componentes, telas, personas e dispositivos",
		"a decisão envolve como estruturar component library para B2B multisided platform com density modes e themes",
		"a decisão envolve como compor componentes complexos (dashboard, table, form) a partir de primitivos simples (button, input, badge)",
		"a decisão envolve como design tokens habilitam density modes (compact, default, spacious), themes (light, dark) e white-labeling",
		"a decisão envolve como manter design system com solo founder onde agentes IA geram a maior parte do UI code",
		"a decisão envolve como design system governa output visual de agentes para prevenir inconsistência",
		"a decisão envolve trade-offs entre design system completo (100 componentes) e minimal viable (10 componentes) para MVP",
	]
	keywords: [
		"design tokens", "tokens", "variáveis de design", "CSS variables", "custom properties",
		"design system", "sistema de design", "component library", "UI library",
		"spacing", "sizing", "border-radius", "elevation", "shadow", "z-index",
		"breakpoint", "responsive", "grid", "layout", "column",
		"component", "componente", "primitive", "compound", "pattern", "template",
		"atomic design", "atoms", "molecules", "organisms",
		"consistency", "consistência", "reutilização", "reuse", "DRY",
		"density mode", "compact", "default", "spacious",
		"theme", "dark mode", "light mode", "white-label",
		"Tailwind", "Figma variables", "style dictionary", "token pipeline",
		"minimal viable design system", "MVDS",
	]
	excludeWhen: [
		"a decisão é sobre valores específicos de tipografia (escala, weights) — usar typographic-systems-for-dense-interfaces",
		"a decisão é sobre valores específicos de cor (semantic, palette) — usar color-as-functional-language",
		"a decisão é sobre density strategy e composição de dashboard — usar information-density-design",
		"a decisão é sobre patterns de interação (forms, feedback, batch) — usar interaction-patterns-for-professional-tools",
		"a decisão é sobre tipos de charts e encoding visual — usar data-visualization-semiotics",
	]
	rationale: "Design tokens são a foundation layer que habilita todos os outros aspectos do design visual. TS define typographic scale; CL define cores; ID define density strategy; IP define interaction patterns. DT codifica TODAS essas decisões em tokens consumíveis por componentes, tornando possível: mudar density mode (compact → spacious) via token override sem tocar em componente. Mudar theme (light → dark) via token override. Mudar brand (white-label para FIDC) via token override. Sem tokens: cada componente hardcoda seus próprios valores, inconsistência prolifera organicamente, e qualquer mudança global requer search-and-replace em todo o codebase. Na Mesh AI-native com agentes gerando UI code: tokens são constraints que agente consome para produzir output visualmente consistente — sem tokens, N sessões de agente produzem N estilos visuais diferentes. Com tokens: N sessões produzem 1 estilo consistente governado por design system."
}

concepts: [
	{
		id:         "dt-token-architecture"
		name:       "Arquitetura de Tokens: 3 Camadas de Abstração (Global → Alias → Component)"
		nature:     "theoretical"
		role:       "framework"
		definition: "Design token architecture formalizada por Salesforce Lightning Design System (2019, evoluída 2024+): tokens organizados em 3 camadas de abstração crescente: **Layer 1 — Global tokens (raw values):** valores primitivos sem significado semântico. São o vocabulário base. color-blue-500: #3b82f6. color-green-700: #15803d. spacing-4: 16px. font-size-14: 14px. shadow-md: 0 4px 6px -1px rgba(0,0,0,0.1). Nomeados por: type + scale position. Não referenciam contexto de uso. **Layer 2 — Alias tokens (semantic mapping):** mapeiam globals para significados semânticos. color-success-primary: {value: color-green-700}. color-text-primary: {value: color-gray-900}. spacing-gap-md: {value: spacing-4}. font-size-body: {value: font-size-14}. surface-card: {value: color-white}. Nomeados por: role/purpose + variant. Carregam significado: 'success-primary' comunica intent. **Layer 3 — Component tokens (component-specific):** mapeiam alias para contextos de componente específico. button-padding-horizontal: {value: spacing-gap-md}. badge-text-color: {value: color-success-primary}. table-row-height: {value: spacing-9}. kpi-card-padding: {value: spacing-gap-md}. Nomeados por: component + property. Optionais — muitos componentes podem referenciar alias diretamente. Úteis quando componente precisa de valor que difere do alias padrão. Conceito de 'token-driven development' (2024+): developers e agentes trabalham com tokens, nunca com raw values. Se designer diz 'make this green': developer usa --color-success-primary, não #15803d. Se designer diz 'more space here': developer usa next token in spacing scale, não arbitrary 18px. Token muda: todos os componentes que referenciam atualizam simultaneamente. Concepto de 'token as contract' (2024+): tokens são o contrato entre design e implementation. Designer define: 'success é verde, body é 14px, gap é 16px.' Developer implementa: variáveis CSS que referenciam esses valores. Mudança no contrato (designer muda verde para teal): propagação automática. Sem token: mudança requer grep + manual replacement."
		meshManifestation: "Na Mesh, 3 layers: **Global:** color scale: gray-50..gray-900 (10 steps), blue-50..blue-900, green-50..green-900, red-50..red-900, yellow-50..yellow-900, orange-50..orange-900. ~60 color globals. Spacing scale: 1(4px), 2(8px), 3(12px), 4(16px), 5(20px), 6(24px), 8(32px), 10(40px), 12(48px). 9 spacing globals. Font-size scale: 11, 12, 13, 14, 16, 18, 20, 24, 28px. 9 font globals. Font-weight: 400, 500, 600, 700. 4 weight globals. Border-radius: sm(4px), md(6px), lg(8px), xl(12px), full(9999px). 5 radius globals. Shadow: none, sm, md, lg. 4 shadow globals. Total globals: ~95 values. **Alias:** color-text-primary: gray-900. color-text-secondary: gray-600. color-text-muted: gray-500. color-surface-page: gray-50. color-surface-card: white. color-success-primary: green-700. color-success-subtle: green-50. (etc × 5 intents). spacing-gap-sm: spacing-2. spacing-gap-md: spacing-4. spacing-gap-lg: spacing-6. font-size-xs..font-size-xl (6 steps from TS). line-height-tight, line-height-normal, line-height-headline. Total alias: ~50 values. **Component (selective):** kpi-card-padding: spacing-gap-md. table-row-height-compact: 24px. table-row-height-default: 36px. button-radius: radius-md. badge-radius: radius-full. Total component: ~20 values (only where needed)."
		meshImplication: "Token implementation: (1) CSS custom properties para todos os tokens: :root { --color-gray-900: #111827; --color-text-primary: var(--color-gray-900); --kpi-card-padding: var(--spacing-gap-md); }. Components: p { color: var(--color-text-primary); }. .kpi-card { padding: var(--kpi-card-padding); }. (2) file structure: tokens/globals.css (raw values), tokens/aliases.css (semantic), tokens/components.css (component-specific). Or: single tokens.css with sections. Imported by all components. (3) naming convention: --{layer}-{category}-{property}-{variant}. Globals: --color-blue-500, --spacing-4, --font-size-14. Aliases: --color-text-primary, --spacing-gap-md, --font-size-body. Components: --button-padding, --table-row-height. Predictable: developer or agent can guess token name. (4) no magic numbers: CI lint rule — every color, spacing, font-size, border-radius, shadow in component files must reference token variable. Raw value (color: #3b82f6, padding: 16px, font-size: 14px) → CI warning. Forces token usage. (5) token documentation: design system docs list all tokens with: name, value, usage examples, visual swatch (for colors). Agente reads docs to select correct token. 'Need body text color → --color-text-primary. Need KPI card padding → --kpi-card-padding.' (6) token count discipline: ~165 total tokens (95 global + 50 alias + 20 component). Not 500. Every token earns existence by being referenced ≥3 times. Token referenced once: probably not needed (inline the value or use parent token). Anti-pattern: 500 tokens where 300 are referenced once — token sprawl is as bad as no tokens (developer can't find the right one among 500 options)."
		rationale: "Salesforce Lightning 2019: 3-layer architecture. Token-driven development 2024+. Token as contract 2024+. Na Mesh, ~165 tokens encode entire visual system. Change --spacing-gap-md from 16px to 12px: every gap in every component updates. Zero search-and-replace. Token change = global change."
	},
	{
		id:         "dt-component-composition"
		name:       "Composição de Componentes: Primitivos → Compounds → Patterns → Templates"
		nature:     "operational"
		role:       "framework"
		reviewCadence: "semi-annual"
		definition: "Frost (2016, Atomic Design): hierarchy de abstração para UI components: atoms (indivisible elements) → molecules (simple groups of atoms) → organisms (complex groups of molecules) → templates (page-level structures) → pages (templates with real data). Conceito adaptado para B2B design system: **Primitives (atoms):** Button, Input, Select, Checkbox, Badge, Icon, Text, Avatar, Spinner, Skeleton. Each: single responsibility, styled by tokens, no business logic. **Compounds (molecules/organisms):** MetricCard = Text[xl,bold] + Text[sm] + Sparkline + DeltaIndicator. FormField = Text[label] + Input + Text[error]. StatusBadge = Badge + Icon + Text (from CL semantic system). DataTable = TableHeader + TableRow[] + TableFooter + Pagination + ActionBar. Toast = Icon + Text + Button[dismiss]. **Patterns (recurring compositions):** KPIRow = 4× MetricCard in responsive grid. OperationForm = FormField[] + FileUpload + Button. FilterBar = Select[] + Input[search] + Button[apply]. **Templates (page layouts):** DashboardTemplate = KPIRow + DataTable + ChartSection. DetailTemplate = Breadcrumb + Header + Content + SidePanel. FormTemplate = ProgressIndicator + OperationForm + Navigation. Conceito de 'composition over configuration' (2023+): em vez de 1 mega-component com 30 props (BarChart com props para: type, stacked, horizontal, grouped, colors, labels, animations, legends, tooltips, themes...), compor components especializados: HorizontalBarChart, StackedBarChart, GroupedBarChart. Cada um: focused, simpler API, fewer props. Compound component é composed from primitives, not configured from god-component."
		meshManifestation: "Na Mesh, component inventory: **Primitives (10 core):** Button (primary, secondary, danger, ghost; sizes: sm, md, lg; states: default, hover, focus, active, disabled, loading). Input (text, number, currency, percentage, date; with label, placeholder, error, disabled). Select (single, multi; searchable, creatable). Checkbox (individual, group; indeterminate for header). Badge (semantic colors from CL; sizes: sm, md). Icon (from Lucide icon set; sizes: 16, 20, 24px). Text (sizes from TS scale; weights; colors from CL text tokens). Sparkline (data, threshold, color). Skeleton (types: card, table-row, text-line, chart). Spinner (sizes: sm, md, lg). **Compounds (8 core):** MetricCard (value + label + Sparkline + DeltaIndicator + click-to-drill). FormField (label + Input + validation message + help text). StatusBadge (Badge + Icon + text; status enum → CL semantic mapping). DataTable (header + rows + sort + filter + checkbox + pagination + ActionBar). Toast (icon + message + action button + dismiss; semantic type). Modal (overlay + header + content + footer buttons; sizes: sm, md, lg). SidePanel (overlay right; header + content + footer; push or overlay layout). CommandPalette (search input + results list + keyboard navigation). **Patterns:** KPIRow (MetricCard[] in responsive grid — 4 on desktop, 2 on tablet, 1 on mobile). FilterBar (Select + Input[search] + DateRange + Button[apply/clear]). ActionBar (count label + Button[] for batch actions; sticky). ScoreGauge (from DV fintech-specific). ConcentrationChart, VintageChart, WaterfallChart (from DV)."
		meshImplication: "Composition guidelines: (1) primitives consume tokens directly — Button uses --button-padding, --color-brand-primary, --font-size-base, --radius-md. Every visual property from token. (2) compounds compose primitives — MetricCard composes Text + Sparkline + DeltaIndicator. MetricCard doesn't define font-size — it uses Text[xl] which uses --font-size-xl. No visual properties at compound level — inherited from primitives which inherit from tokens. (3) props simplicity — compound accepts data props (value, label, trendData) not style props (fontSize, color, padding). Style comes from tokens via primitives. Developer: <MetricCard value='R$2.3M' label='Lastro Total' trendData={[1.8,2.0,2.1,2.3]} />. Not: <MetricCard value='R$2.3M' fontSize={24} fontWeight={700} color='#111827' padding={16} />. (4) component API documentation — each component has: description (what it does), props (name, type, required/optional, default), usage guidelines (when to use, when NOT to use), code example, visual example. Written for agent consumption: structured, concise, with examples (dp-agent-consumability). (5) new pattern evaluation — when UI pattern appears that doesn't match existing component: evaluate: (a) does it appear ≥3 times? → create DS component. (b) does it appear once? → acceptable as one-off with token usage (not hardcoded values). (c) does it partially match existing component? → extend existing with variant, not new component. (6) component count discipline — target: 18-25 components total for MVP (10 primitives + 8 compounds). Not 100. Each component earns existence by being used ≥3 times. Unused component: remove. Under-used: evaluate consolidation. Anti-pattern: 'god component' DataTable with 45 props covering every possible table variation — impossible to document, impossible for agent to use correctly, impossible to maintain. Better: DataTable (core: sort, filter, pagination) + BatchTable (extends DataTable + checkbox + ActionBar) + EditableTable (extends DataTable + inline edit)."
		dependsOn: ["dt-token-architecture"]
		crossDependsOn: [{
			lensId:    "lens-documentation-as-product"
			conceptId: "dp-agent-consumability"
			context:   "DP defines agent-consumable documentation: structured, concise, self-contained with examples. DT component docs follow DP principles: component API is structured (props with types), usage is concise (when/when not), examples are self-contained code snippets. Agent reads component doc → uses component correctly. DP says 'design for context window'; DT says 'component docs that agent parses in 500 tokens: description + props + example = sufficient for correct usage'."
		}]
		rationale: "Frost 2016: Atomic Design. Composition over configuration 2023+. Na Mesh, 18-25 components composed from tokens: consistent UI. Agent uses <MetricCard value='...' /> — component handles styling via tokens. Agent doesn't decide font-size, color, or padding. System decides. Consistency by construction, not by discipline."
	},
	{
		id:         "dt-density-mode-tokens"
		name:       "Tokens de Density Mode: Compact, Default, Spacious via Token Override"
		nature:     "operational"
		role:       "method"
		reviewCadence: "semi-annual"
		definition: "Density modes (ID lens: id-density-calibration-per-persona) são implementados via token override — mesmos componentes, diferentes valores de token. Conceito de 'mode as token layer' (2024+): density mode é uma layer de tokens que overrides alias tokens. Default mode: alias tokens have their standard values. Compact mode: override layer reduces spacing, font-sizes, heights. Spacious mode: override layer increases them. Component code: unchanged. Implementation: CSS class on root element that redefines token values. body.density-compact { --spacing-gap-md: 8px; --font-size-body: 13px; --table-row-height: 24px; }. Component: .table-row { height: var(--table-row-height); } — renders 24px in compact, 36px in default, 48px in spacious. Zero component code change."
		meshManifestation: "Na Mesh, 3 density modes com token overrides: **Compact (FIDC default):** --font-size-xs: 11px; --font-size-base: 13px; --font-size-xl: 20px. --spacing-gap-sm: 4px; --spacing-gap-md: 8px; --spacing-gap-lg: 12px. --table-row-height: 24px. --kpi-card-padding: 12px. --line-height-tight: 1.2. Result: maximum data density on 1440p+ screens. ~30 table rows visible. **Default (construtora default):** --font-size-xs: 12px; --font-size-base: 14px; --font-size-xl: 24px. --spacing-gap-sm: 8px; --spacing-gap-md: 16px; --spacing-gap-lg: 24px. --table-row-height: 36px. --kpi-card-padding: 16px. --line-height-tight: 1.3. Result: balanced density and readability. ~18 table rows visible. **Spacious (fornecedor default):** --font-size-xs: 13px; --font-size-base: 16px; --font-size-xl: 28px. --spacing-gap-sm: 12px; --spacing-gap-md: 24px; --spacing-gap-lg: 32px. --table-row-height: 48px. --kpi-card-padding: 24px. --line-height-tight: 1.4. Result: comfortable mobile-first experience. ~10 table rows visible on mobile."
		meshImplication: "Density implementation: (1) CSS class approach: body.density-compact { ... overrides ... }. Applied via: user preference (settings), persona default (FIDC auto-compact), or responsive (mobile forces minimum sizes). (2) token matrix — spreadsheet/table documenting: token name × mode = value. --font-size-base: compact=13, default=14, spacious=16. Reviewed and maintained as design system artifact. (3) mobile safety floor: even in compact mode on mobile: --font-size-base ≥ 14px. --touch-target ≥ 44px. Mobile overrides compact for safety: @media (max-width: 640px) { .density-compact { --font-size-base: max(14px, var(--font-size-base)); } }. (4) mode toggle: user-facing toggle in settings or toolbar. Persist per-user. Default per persona but overridable. FIDC power user who wants spacious for presentation: can switch. Construtora novato who wants compact: can switch. (5) testing: 3 modes × critical screens. Each screen must: (a) render without overflow/overlap in all modes. (b) maintain hierarchy (headline > body > caption in all modes). (c) maintain readability (no text below mode minimum). (6) implementation effort: token extraction (one-time migration from hardcoded values): 20-40 hours. Mode definition: 4 hours. Testing: 8 hours. Total: ~35-50 hours. After: any future density adjustment is token change (minutes, not hours). Anti-pattern: 'compact mode' implemented by shrinking every component by 80% via CSS scale transform — text blurry, click targets too small, not real density adjustment. Token override: real values change, rendering is native quality."
		dependsOn: ["dt-token-architecture"]
		crossDependsOn: [{
			lensId:    "lens-information-density-design"
			conceptId: "id-density-calibration-per-persona"
			context:   "ID defines density strategy per persona: FIDC = compact, construtora = default, fornecedor = spacious. DT implements: body.density-compact sets token overrides that make every component compact. ID is the strategy ('what density for whom'); DT is the implementation ('how density is achieved via token override'). ID defines the target; DT provides the mechanism."
		}]
		rationale: "Mode as token layer 2024+. Na Mesh, same DataTable component renders: 24px rows for FIDC (compact, 30 rows visible), 36px for construtora (default, 18 rows), 48px for fornecedor (spacious, 10 rows). Zero code duplication. Token overrides only. Investment: ~40 hours. Payoff: every future density adjustment is minutes of token change."
	},
	{
		id:         "dt-theme-tokens"
		name:       "Tokens de Theme: Light, Dark e White-Label via Token Override"
		nature:     "operational"
		role:       "method"
		reviewCadence: "annual"
		definition: "Themes work identically to density modes: token override layer. Light theme: alias tokens map to light values. Dark theme: alias tokens map to dark values. White-label (FIDC brand): brand tokens map to client brand colors. Conceito de 'theme as token layer' (2024+): mesma arquitetura de density applied to visual theme. body.theme-dark { --color-surface-page: var(--color-gray-900); --color-text-primary: var(--color-gray-100); --color-success-primary: hsl(142, 71%, 55%); /* lighter green for dark bg */ }. Component: p { color: var(--color-text-primary); } — renders dark text on light bg OR light text on dark bg. Zero component change. Conceito de 'semantic color preservation across themes' (2024+): semantic meaning is preserved across themes. Success is green in light AND dark — different shade, same meaning. Error is red in both. Brand primary is blue in both (or whatever brand color is). Meaning is constant; visual representation adapts to background."
		meshManifestation: "Na Mesh, theme layers: **Light (default):** --color-surface-page: gray-50. --color-surface-card: white. --color-text-primary: gray-900. --color-text-secondary: gray-600. --color-success-primary: hsl(142, 71%, 29%). --color-error-primary: hsl(0, 85%, 45%). --shadow-sm: 0 1px 2px rgba(0,0,0,0.05). **Dark (optional):** --color-surface-page: hsl(220, 20%, 10%). --color-surface-card: hsl(220, 18%, 14%). --color-text-primary: gray-100. --color-text-secondary: gray-400. --color-success-primary: hsl(142, 71%, 55%). /* lighter for dark bg */ --color-error-primary: hsl(0, 85%, 60%). --shadow-sm: 0 1px 2px rgba(0,0,0,0.3). /* stronger shadow for dark bg */ **FIDC white-label (future):** --color-brand-primary: var(--fidc-client-brand-color). --color-brand-primary-hover: darker(--fidc-client-brand-color). Semantic colors: UNCHANGED. Green success, red error, yellow warning — same across all FIDC clients. Only brand color changes."
		meshImplication: "Theme implementation: (1) theme file per theme: themes/light.css, themes/dark.css, themes/fidc-{client}.css. Each overrides alias tokens. (2) theme selection: user preference (settings toggle). System preference detection: @media (prefers-color-scheme: dark) { :root { /* dark tokens */ } }. Persist: localStorage or user profile on server. (3) semantic preservation: when creating dark theme, for each semantic color: re-compute to maintain: (a) ≥4.5:1 contrast against dark backgrounds (re-verify all pairs). (b) same hue family (green stays green, red stays red). (c) adjust lightness upward for dark backgrounds (dark green on dark bg → lighter green on dark bg). (4) white-label: only brand tokens change. Semantic: constant. Construtora sees Mesh brand colors. FIDC sees their own brand colors. Both: same green for success, same red for error. (5) combinability: density + theme are independent layers. body.density-compact.theme-dark → compact sizing + dark colors. Both applied via token override. No interaction conflicts (spacing doesn't depend on color). (6) priority: light theme first. Ship complete and tested. Dark theme: subsequent release (doubles color testing effort). White-label: per-client customization when FIDC onboards (brand color only — low effort since only --color-brand-* tokens change). (7) dark mode testing: every text/background pair re-verified. Light text on dark bg has different contrast characteristics than dark text on light bg. Cannot assume: 'if light mode passes, dark mode passes.' Dedicated dark mode contrast audit required. Anti-pattern: dark mode implemented by CSS filter: invert(100%) — inverts everything including images, semantic colors (green becomes magenta), and brand colors. Not a theme — a visual distortion."
		dependsOn: ["dt-token-architecture"]
		crossDependsOn: [{
			lensId:    "lens-color-as-functional-language"
			conceptId: "cl-dark-mode-and-theming"
			context:   "CL defines semantic color adaptation for dark mode: lighter greens, lighter reds to maintain contrast on dark backgrounds. DT theme tokens implement: dark theme file overrides color tokens with CL-specified dark values. CL says 'success-primary in dark mode is hsl(142, 71%, 55%)'; DT encodes as --color-success-primary: hsl(142, 71%, 55%) in themes/dark.css. CL defines values; DT provides implementation infrastructure."
		}]
		rationale: "Theme as token layer 2024+. Semantic preservation 2024+. Na Mesh, light + dark + white-label: all achieved via token override. Same components render differently based on active theme. Investment: theme file creation (~8 hours per theme). FIDC white-label: ~2 hours per client (brand color only). Scale: unlimited themes, zero component changes."
	},
	{
		id:         "dt-responsive-layout-tokens"
		name:       "Tokens de Layout Responsivo: Breakpoints, Grid e Adaptive Composition"
		nature:     "operational"
		role:       "property"
		reviewCadence: "semi-annual"
		definition: "Layout tokens define: breakpoints (when layout changes), grid (how content is organized), and adaptive behaviors (what changes at each breakpoint). Conceito de 'breakpoint-responsive tokens' (2024+): tokens whose values change per breakpoint. Not just layout (columns) but content-level (font-size, spacing, visibility). @media (max-width: 640px) { :root { --font-size-base: 16px; --grid-columns: 1; --kpi-per-row: 1; } }. @media (min-width: 1024px) { :root { --font-size-base: 14px; --grid-columns: 12; --kpi-per-row: 4; } }. Conceito de 'content priority at breakpoints' (2024+, from ID lens responsive-density): at each breakpoint, not just layout changes — content changes. Mobile: show P0 (essential). Tablet: show P0 + P1. Desktop: show P0 + P1 + P2. Implementation: components accept priority prop; CSS shows/hides based on breakpoint."
		meshManifestation: "Na Mesh, responsive tokens: **Breakpoints:** --bp-mobile: 640px. --bp-tablet: 1024px. --bp-desktop: 1440px. --bp-wide: 1920px. **Grid:** mobile: 1 column (stacked). Tablet: 8 columns. Desktop: 12 columns. Wide: 12 columns with max-width container. **Adaptive per breakpoint:** mobile (<640px): KPIRow = 1 card stacked. Table = essential columns only (3-4). Sidebar = hidden (bottom nav). Charts = hidden or simplified. tablet (640-1024px): KPIRow = 2 cards per row. Table = medium columns (6-8). Sidebar = collapsible. Charts = simplified. desktop (1024-1440px): KPIRow = 4 cards per row. Table = full columns. Sidebar = persistent. Charts = full. wide (>1440px): same as desktop with more whitespace or additional context panels."
		meshImplication: "Layout implementation: (1) CSS Grid with token-based columns: .layout { display: grid; grid-template-columns: repeat(var(--grid-columns), 1fr); gap: var(--spacing-gap-md); }. Breakpoint changes --grid-columns: mobile = 1, tablet = 8, desktop = 12. (2) component visibility by priority: <TableColumn priority={1}> shown always. <TableColumn priority={2}> shown on tablet+. <TableColumn priority={3}> shown on desktop+. CSS: @media (max-width: 640px) { [data-priority='2'], [data-priority='3'] { display: none; } }. (3) sidebar behavior: desktop: persistent sidebar (200-240px width). Tablet: collapsible (hamburger toggle). Mobile: hidden (bottom navigation instead). Transition: CSS media query changes sidebar display and main content width. (4) KPIRow adaptive: grid-template-columns changes by breakpoint. Desktop: repeat(4, 1fr). Tablet: repeat(2, 1fr). Mobile: 1fr. Same MetricCard component, different grid placement. (5) max-width container: wide screens (>1440px): content has max-width to prevent extreme line lengths. --container-max-width: 1440px. Centered with auto margins. Prevents: 3000px wide table on ultrawide monitor (illegible). (6) touch targets: mobile breakpoint: all interactive elements ≥ 44px × 44px. Token: --touch-target-min: 44px. Components: min-height: var(--touch-target-min) on mobile. (7) testing: each persona's primary workflow on primary device. Fornecedor: submit antecipação on mobile (375px). Construtora: review dashboard on desktop (1440px). FIDC: analyze operations on wide desktop (1920px). Workflow must complete without device switch."
		dependsOn: ["dt-token-architecture"]
		rationale: "Breakpoint-responsive tokens 2024+. Content priority at breakpoints 2024+. Na Mesh, same components render: mobile (1 column, essential content, touch targets) → desktop (12 columns, full content, precise pointer). Token-driven breakpoints: layout adapts without component code changes."
	},
	{
		id:         "dt-design-system-governance-for-ai"
		name:       "Governança de Design System para AI: Tokens como Constraints para Agentes"
		nature:     "operational"
		role:       "method"
		reviewCadence: "quarterly"
		definition: "Em AI-native development, design system tem dual role: (1) traditional — visual consistency para humanos que usam o produto. (2) AI-specific — constraint system para agentes que geram UI code. Sem constraints: agente usa qualquer valor que 'parece razoável' — cada sessão produz estilo levemente diferente. Com constraints: agente consome tokens e componentes, produzindo output consistente governado pelo sistema. Conceito de 'design system as prompt' (2024+): CLAUDE.md e component docs são, efetivamente, prompt engineering para agentes que geram UI. Quanto mais claro o prompt (docs), melhor o output (UI). Component docs com structured API + usage guidelines + examples = agent generates correct UI. Component docs vagos ou ausentes = agent guesses, inconsistency follows. Conceito de 'CI as design system enforcer' (2024+): CI pipeline valida que agent output complies with design system: (a) lint for raw values — hardcoded hex, px, font-size → warning. (b) lint for missing tokens — new visual property not referencing token → warning. (c) lint for unknown components — custom div with styles where DS component exists → suggestion. (d) accessibility checks — contrast ratios, ARIA labels. CI transforms design system from 'guidelines' to 'enforced rules.'"
		meshManifestation: "Na Mesh AI-native, DS governance: (1) **CLAUDE.md instruction:** 'UI components: use design system components from @mesh/ui. Tokens from tokens.css. Never use raw hex values, raw pixel values, or inline font-sizes. For new UI: compose existing components. If no component matches need: document the gap, create as new DS component with tokens — not one-off styled div.' (2) **component docs as agent prompt:** cada componente em design system docs: MetricCard — description: 'displays single KPI with value, label, trend, and comparison.' Props: value (string, required), label (string, required), trendData (number[], optional — 8-12 points), comparison (string, optional), onClick (function, optional — drill-down). When to use: 'KPI display on dashboards.' When NOT to use: 'detailed metrics (use table). Multiple related values (use table or custom layout).' Example: <MetricCard value='R$2.3M' label='Lastro Total' trendData={[1.8,1.9,2.1,2.3]} comparison='+8% vs mês anterior' />. Agent reads 500 tokens of doc → generates correct MetricCard usage. (3) **CI rules:** eslint-plugin-design-system (custom): rule 'no-raw-colors' (flags hardcoded hex/rgb). rule 'no-raw-spacing' (flags hardcoded px for padding/margin/gap). rule 'prefer-ds-component' (flags <div className='badge...'> when <StatusBadge> exists). rule 'token-reference' (flags CSS property values that don't use var(--*)). (4) **agent reviewer:** optional second-pass agent that reviews UI output for DS compliance before merge. Checks: all components from DS? All values from tokens? Consistent with existing pages?"
		meshImplication: "Governance implementation: (1) CLAUDE.md: 3 sections for UI: (a) available components (list with 1-line description each). (b) token usage rules ('use --color-* for colors, --spacing-* for gaps, --font-size-* for text'). (c) anti-patterns ('never: inline style with hex value. Never: custom badge when StatusBadge exists.'). Updated when: new component added, component API changes, new anti-pattern identified. (2) CI enforcement: start with: 'no-raw-colors' rule (highest impact, catches most inconsistency). Add rules incrementally. Each rule: warning first (agent learns), then error (enforced). (3) agent output review process: agent generates UI code → CI runs lint → if violations: agent receives feedback, fixes. If no violations: human reviews business logic (not visual consistency — DS + CI handled that). Human review effort: reduced from 'review every pixel' to 'review business logic only.' (4) new component process: agent encounters UI pattern not covered by DS → agent documents: 'need: [description], similar to: [existing component], proposed approach: [extend X or create Y].' Human reviews proposal. If approved: agent creates DS component with tokens + docs + tests. (5) DS metrics: % of UI code using DS components (target: >90%). % of visual properties using tokens (target: >95%). CI violations per PR (target: <2 new violations per PR, trending to 0). (6) minimal viable enforcement: for day 1, even without custom eslint plugin: CLAUDE.md instruction + post-session manual review is sufficient. CI enforcement: add when volume of agent sessions justifies automation investment. Anti-pattern: design system exists in Figma but not in code — beautiful designs that agents can't consume. DS must be code-first: component library in code + token CSS file. Figma is optional visualization, not source of truth."
		dependsOn: ["dt-token-architecture", "dt-component-composition"]
		crossDependsOn: [{
			lensId:    "lens-ai-agent-governance"
			conceptId: "aag-governance-as-code"
			context:   "AAG defines governance como código consultável por agentes: policies, boundaries, conventions. DT design system governance is the visual manifestation: tokens are visual policies (color-success-primary = this green), components are visual boundaries (use MetricCard, not custom div), CI rules are visual enforcement. AAG governs agent behavior broadly; DT governs agent visual output specifically. Together: agent produces code that is both architecturally sound (AAG) and visually consistent (DT)."
		}]
		rationale: "Design system as prompt 2024+. CI as enforcer 2024+. Na Mesh AI-native, design system is the constraint system that makes N agent sessions produce 1 visual style. Without DS governance: visual entropy increases with each agent session. With: visual consistency maintained automatically through tokens + components + CI. Solo founder doesn't review pixels — system governs."
	},
	{
		id:         "dt-minimal-viable-design-system"
		name:       "Minimal Viable Design System: Começar com o Suficiente, Expandir com Evidência"
		nature:     "operational"
		role:       "method"
		reviewCadence: "quarterly"
		definition: "Full design system (100+ components, comprehensive documentation, design tool integration, theme builder) takes months to build. For solo founder building MVP: months on design system = months without product. But no design system = visual chaos from day 1 that compounds. Conceito de 'minimal viable design system' (MVDS, 2023+): the smallest design system that prevents visual chaos while enabling rapid development. Includes: tokens (all visual values), core components (covers 80% of UI), and basic docs (agent can use components correctly). Expand: when evidence shows gap (pattern appears 3+ times without component, token is missing for common value). Conceito de 'invest-as-you-go' (2024+): DS investment proportional to product maturity. Pre-MVP: tokens + 10 components. MVP: tokens + 15-20 components + basic docs. Growth: tokens + 25-35 components + full docs + CI enforcement + theme support. Scale: tokens + 50+ components + design tool sync + multi-brand. Each stage: justified by current needs, not future speculation."
		meshManifestation: "Na Mesh, MVDS for pre-MVP/MVP: **Phase 1 — Tokens (4 hours):** all visual values as CSS custom properties. Colors (semantic 5×3 + gray scale + brand = ~25). Spacing (9 steps). Font-size (6 steps per density). Font-weight (4). Border-radius (5). Shadow (4). Total: ~95 globals + ~50 aliases = ~145 tokens in 1 CSS file. **Phase 2 — 10 Core Components (30 hours):** Button, Input, Select, Badge/StatusBadge, MetricCard, DataTable (basic: header + rows + sort + pagination), FormField, Toast, Modal, Skeleton. These cover: dashboards (MetricCard + DataTable), forms (Input + FormField + Button + Select), feedback (Toast + Modal + Skeleton), status (StatusBadge). 80% of MVP UI covered. **Phase 3 — Basic Docs (8 hours):** each component: 1-page doc with props, usage guidelines, code example. CLAUDE.md section: available components + token usage rules. **Total Phase 1-3: ~42 hours.** Sufficient for: agent-generated UI with consistency, density modes (token override), and basic theming (light). **Phase 4 — Expand (ongoing):** add components as patterns emerge: Sparkline (when KPI cards need trend), CommandPalette (when 20+ actions), SidePanel (when drill-down pattern established), ActionBar (when batch operations built). Each: justified by usage ≥3 times."
		meshImplication: "MVDS implementation: (1) tokens FIRST — before any component. Even if building with raw Tailwind initially: create tokens.css that maps semantic names to Tailwind values. --color-success-primary: theme('colors.green.700'). When ready for custom components: tokens already exist. (2) 10 components by priority — ordered by: frequency of use × complexity of getting wrong. Button (used everywhere, states matter). Input (forms, critical for data entry). DataTable (FIDC + construtora primary interface). MetricCard (dashboard primary). StatusBadge (status everywhere). Toast (feedback everywhere). These 6 are highest priority. Next 4: Select, FormField, Modal, Skeleton. (3) build incrementally — day 1: tokens.css (4h). Day 2: Button + Input + Badge (8h). Day 3: MetricCard + Toast (6h). Day 4: DataTable (8h, most complex). Day 5: FormField + Select + Modal + Skeleton (8h). Day 6: docs (8h). Total: 6 days / 42 hours for complete MVDS. (4) agent workflow — agent reads CLAUDE.md → sees component list → uses components + tokens → CI validates. From day 6: every agent session produces consistent UI. Before day 6: agent uses Tailwind with token-mapped classes (acceptable for MVP, migrate to components when built). (5) what NOT to build yet — chart components (use Recharts/Chart.js with token-based styling). Dark mode (light first, dark later). Animation library (focus on function, not motion). Icon library (use Lucide CDN). Design tool sync (Figma variables sync — nice but not MVP). (6) expand trigger — 'I need a component that doesn't exist' appears 3 times → create it. 'This pattern is inconsistent across 3 pages' → component needed. 'Agent generated this differently than existing pattern' → component prevents recurrence. Anti-pattern: spend 3 months building comprehensive DS before writing any product code — DS without product to style is speculation. Or: spend 0 time on DS, build product with hardcoded values → visual chaos that takes 3 months to untangle later. MVDS: 42 hours prevents both extremes."
		dependsOn: ["dt-token-architecture", "dt-component-composition"]
		rationale: "MVDS 2023+. Invest-as-you-go 2024+. Na Mesh solo founder, 42 hours of DS investment prevents: visual inconsistency from day 1, agent-generated chaos, and costly retrofit later. 42 hours = 1 week. Product without DS: visual debt accrues at ~10 hours/month of inconsistency fixes. DS payback: <5 months."
	},
	{
		id:         "dt-spacing-system"
		name:       "Sistema de Spacing: Escala Consistente para Gaps, Padding e Margins"
		nature:     "operational"
		role:       "property"
		reviewCadence: "semi-annual"
		definition: "Spacing system define: how much space between and within elements. Base: 4px grid (most common in modern design systems — divisible into halves and quarters cleanly, aligns with common line-heights). Scale: geometric or linear progression based on 4px. Conceito de 'spacing roles' (2023+): different spacing values for different roles: (a) inline spacing — within component (padding, gap between icon and text). Small: 4-8px. (b) component spacing — between elements within a group (gap between form fields, gap between cards in row). Medium: 8-16px. (c) section spacing — between groups/sections (gap between KPI row and table, gap between page header and content). Large: 16-32px. (d) page spacing — margins, gutters, container padding. Largest: 24-48px. Conceito de 'spacing and density' (2024+): spacing role values shift per density mode. Compact: all values shrink by ~50%. Spacious: all values grow by ~50%. But role hierarchy is preserved: inline < component < section < page in all modes."
		meshManifestation: "Na Mesh, spacing scale: **Base grid: 4px.** Scale: step-1: 4px, step-2: 8px, step-3: 12px, step-4: 16px, step-5: 20px, step-6: 24px, step-8: 32px, step-10: 40px, step-12: 48px. **Role mapping (default mode):** --spacing-inline: step-2 (8px) — icon to text, badge padding horizontal. --spacing-component: step-4 (16px) — form fields gap, card internal padding. --spacing-section: step-6 (24px) — KPI row to table, header to content. --spacing-page: step-8 (32px) — page margins, container padding. **Density overrides:** compact: inline=4, component=8, section=12, page=16. Spacious: inline=12, component=24, section=32, page=48."
		meshImplication: "Spacing implementation: (1) 9-step scale as tokens: --spacing-1: 4px through --spacing-12: 48px. (2) role aliases: --spacing-inline: var(--spacing-2). --spacing-component: var(--spacing-4). --spacing-section: var(--spacing-6). --spacing-page: var(--spacing-8). (3) density overrides change role aliases, not component code: .density-compact { --spacing-component: var(--spacing-2); }. Component: .card { padding: var(--spacing-component); } — 16px default, 8px compact. (4) no arbitrary spacing: every margin, padding, and gap references token. If 18px is needed: it doesn't exist in scale → pick 16px or 20px. Scale enforces consistency. (5) Gestalt proximity: spacing between items within a group < spacing between groups. Card internal padding (16px) < gap between cards (24px). Table cell padding (8px) < gap between table and chart (24px). If within-group = between-group: grouping is invisible. (6) responsive spacing: mobile: --spacing-page = 16px (screen edge is close). Desktop: --spacing-page = 32px (ample room). Components: responsive via token. (7) testing: take any screen → measure spacing between elements. All on 4px grid? Role hierarchy preserved (inline < component < section)?"
		dependsOn: ["dt-token-architecture"]
		rationale: "Spacing roles 2023+. Spacing and density 2024+. Na Mesh, 9-step scale + 4 role aliases + density overrides = consistent spacing governed by tokens. No 'this looks like about 18px' — every space is from scale."
	},
	{
		id:            "dt-tokens-review"
		name:          "Revisão de Tokens e DS: Inventário Periódico de Saúde do Sistema"
		nature:        "operational"
		role:          "method"
		reviewCadence: "quarterly"
		definition:    "Inventário periódico que consolida todos os conceitos da lens. Para cada período: (1) token coverage — all visual properties use tokens? Raw values detected in codebase? (2) component coverage — all recurring UI patterns have DS component? One-off components that should be promoted? (3) density modes — all 3 modes render correctly? No overflow/overlap in compact? No excessive space in spacious? (4) themes — light mode consistent? Dark mode (if implemented) contrast passes? White-label (if implemented) brand tokens correct? (5) responsive — breakpoints working? Priority content visible per device? Touch targets on mobile? (6) agent governance — CLAUDE.md current? CI rules catching violations? Agent output consistent? (7) MVDS — components inventory: used ≥3 times each? Any unused? Any pattern appearing 3+ times without component? (8) spacing — all on grid? Role hierarchy preserved?"
		meshManifestation: "Na Mesh: revisão trimestral. Token health + component inventory + density/theme test."
		meshImplication: "Quarterly (1.5h): (a) token audit — grep codebase for raw hex, raw px, raw font-size not in token definition files. Count violations. Target: 0. If >0: fix + add CI rule to prevent recurrence. (b) component audit — list all components. Usage count per component (grep for import). <3 uses: evaluate — still needed? Remove if not. Identify: 3 UI patterns on screen that aren't DS components. Should they be? (c) density test — switch to compact: FIDC table renders correctly? 30 rows visible? No overflow? Switch to spacious: fornecedor mobile renders correctly? Touch targets 44px? No text below 14px? (d) theme test — if dark mode: load 3 key screens. Contrast passes? Semantic colors correct? If white-label: load with FIDC brand tokens. Brand applied? Semantic preserved? (e) responsive test — load fornecedor flow on mobile (375px). Complete workflow? Load FIDC dashboard on 1920px. Full content visible? (f) agent governance — recent 3 PRs from agent: all using DS components? Any raw values? CI caught violations? If not caught: add rule. (g) spacing audit — screenshot → inspect 5 spacing values. All on 4px grid? Role hierarchy maintained? (h) documentation — component docs up-to-date? New components documented? CLAUDE.md updated?"
		dependsOn: ["dt-token-architecture", "dt-component-composition", "dt-density-mode-tokens", "dt-theme-tokens", "dt-responsive-layout-tokens", "dt-design-system-governance-for-ai", "dt-minimal-viable-design-system", "dt-spacing-system"]
		rationale: "Design systems decay: new developer adds raw value, agent generates one-off component, density mode breaks with new feature, docs lag behind. Quarterly audit catches drift before it compounds. Token violations found in audit = CI rule to prevent recurrence = self-improving governance."
	},
]

reasoningProtocol: [
	{
		question:  "Todas as propriedades visuais (cor, spacing, font, radius, shadow) são tokens? Zero raw values no codebase?"
		reveals:   "Se design system é source of truth para visual — ou se cada componente hardcoda seus próprios valores, inconsistência proliferando."
		rationale: "Token-driven 2024+. Raw value = inconsistency. Token = governed. CI lint: flags raw values."
	},
	{
		question:  "UI é composta de DS components (Button, MetricCard, DataTable)? Ou cada tela constrói UI ad hoc com divs e inline styles?"
		reveals:   "Se components são reusados e consistentes — ou se N telas = N implementações visuais do mesmo pattern."
		rationale: "Frost 2016. Composition 2023+. MetricCard component: usado em 10 telas, identical. Custom div: 10 telas, 10 variants."
	},
	{
		question:  "Density modes (compact, default, spacious) funcionam via token override sem mudar código de componente?"
		reveals:   "Se density é configuration (token change) — ou se compact mode requer rewrite de componentes."
		rationale: "Mode as token layer 2024+. body.density-compact: token overrides. Zero component code changes."
	},
	{
		question:  "Theme (light, dark, white-label) funciona via token override? Semantic colors preservam significado across themes?"
		reveals:   "Se theming é infra (token layer) — ou se dark mode é fork/filter que distorce tudo."
		rationale: "Theme as token layer 2024+. Semantic preservation: green = success in ALL themes."
	},
	{
		question:  "CLAUDE.md instrui agentes a usar DS components e tokens? CI valida compliance? Agent output é visualmente consistente?"
		reveals:   "Se DS governa AI output — ou se cada sessão de agente produz estilo diferente."
		rationale: "DS as prompt 2024+. CI as enforcer 2024+. N sessions × 1 DS = 1 visual style."
	},
	{
		question:  "DS é minimal viable (10-20 components para MVP) expandido com evidência? Ou comprehensivo nunca-shipped ou inexistente?"
		reveals:   "Se investimento em DS é proportional ao estágio — ou se extremos (3 meses de DS sem produto, ou zero DS com chaos)."
		rationale: "MVDS 2023+. 42 hours prevents visual chaos. Expand when evidence shows gap."
	},
	{
		question:  "Spacing segue escala de 4px com roles (inline < component < section < page)? Ou valores arbitrários everywhere?"
		reveals:   "Se espaçamento é sistemático — ou se cada componente inventa seus próprios gaps."
		rationale: "Spacing roles 2023+. 9-step scale + 4 roles = consistent spatial system."
	},
]

meshExamples: [
	{
		id:       "ex-token-based-density-switch"
		scenario: "Product needs to add compact density mode for FIDC. Currently all interfaces use default density with hardcoded spacing, font-sizes, and row heights. Estimated hardcoded values: 200+ occurrences across 30 component files."
		analysis: "Without tokens: adding compact mode requires finding and modifying 200+ hardcoded values, creating conditional logic in each component (if compact: 8px, else 16px), and testing each component individually. Estimated effort: 80-120 hours. With tokens: extract values to tokens (one-time), then override tokens in density mode class. Effort: extraction 30h + mode definition 4h + testing 8h = 42h. And: every future density change is token-only (minutes)."
		recommendation: "(1) Phase 1 — Token extraction (30h): systematically replace every hardcoded visual value with token reference. padding: 16px → padding: var(--spacing-component). font-size: 14px → font-size: var(--font-size-base). height: 36px → height: var(--table-row-height). 200+ replacements across 30 files. Use search-and-replace for common patterns, manual for complex cases. (2) Phase 2 — Mode definition (4h): create density mode CSS: .density-compact { --spacing-component: 8px; --font-size-base: 13px; --table-row-height: 24px; --kpi-card-padding: 12px; --line-height-tight: 1.2; ... }. All overrides in 1 CSS block. (3) Phase 3 — Apply and test (8h): add class='density-compact' to FIDC portal body. All components: automatically compact. Test: each screen in compact. Fix: any overflow or overlap (text that wraps in compact where it didn't in default). (4) Result: FIDC table shows ~30 rows instead of ~18 (67% improvement). KPI cards are tighter. Overall: more data per screen. (5) Ongoing benefit: future density adjustment = change token value. 'Table rows too tight?' → --table-row-height: 26px. Done. No component hunting. (6) ROI: token extraction (42h) vs per-feature density (80-120h) + ongoing maintenance (10h/quarter for manual sync). Payback: immediate. Plus: theme support (dark mode, white-label) becomes trivial — same token override pattern."
		principlesApplied: ["ax-01", "ax-03", "dp-01"]
		assumptions: [
			"200+ hardcoded values is accurate estimate — could be more in larger codebase",
			"30 hours for extraction is feasible — agent can assist with search-and-replace patterns",
			"compact mode doesn't break layouts — some components may need min-height or text truncation adjustments",
			"FIDC users prefer compact — validate with FIDC gestor feedback after deployment",
		]
		rationale: "Token-driven 2024+. Token extraction is one-time investment. ROI: immediate (42h vs 80-120h for same result). Plus: every future density/theme change is configuration (minutes), not code (hours). Tokens are infrastructure — invest once, benefit forever."
	},
	{
		id:       "ex-agent-visual-inconsistency-prevention"
		scenario: "3 agent sessions over 2 weeks generated: (1) fornecedor page with Tailwind 'text-sm text-gray-600 p-4 rounded-lg'. (2) construtora page with 'text-base text-gray-700 p-5 rounded-md'. (3) FIDC page with 'text-[13px] text-gray-800 p-3 rounded'. Visual review reveals: 3 different font sizes, 3 different text colors, 3 different paddings, 3 different border radii. Each 'looks reasonable' individually. Together: visual chaos."
		analysis: "Root cause: agent has no constraint system. Each session: agent makes 'reasonable' choices independently. Reasonable choice #1 + reasonable choice #2 + reasonable choice #3 = 3 different visual treatments for same semantic purpose (body text). Compounded: if 50 agent sessions each make 10 styling decisions: 500 independent choices = visual entropy. Without DS: inconsistency is mathematically inevitable."
		recommendation: "(1) Immediate fix: normalize 3 pages to use DS tokens. All body text → var(--font-size-base) + var(--color-text-primary). All container padding → var(--spacing-component). All border-radius → var(--radius-md). 2 hours. (2) Prevention — CLAUDE.md update: 'CRITICAL: when creating UI, never use raw Tailwind utilities for: colors (text-gray-600), spacing (p-4), font-sizes (text-sm), border-radius (rounded-lg). Instead use design tokens: color: var(--color-text-primary), padding: var(--spacing-component), font-size: var(--font-size-base), border-radius: var(--radius-md). Tokens are in tokens.css. Reference: [component docs URL].' (3) CI lint rules: eslint rule 'no-raw-tailwind-visual': flags text-gray-*, p-*, text-sm/base/lg/xl, rounded-* in component files. Allowed in: tokens.css definition only. Blocked in: all other files. On violation: 'Use design token var(--color-text-*) instead of text-gray-600. See design system docs.' (4) component promotion: instead of raw HTML with tokens, provide components: <Text size='body' color='primary'>...</Text>. <Card padding='component' radius='md'>...</Card>. Component encapsulates correct token usage. Agent uses component API — can't get tokens wrong because component handles styling. (5) measure: track visual consistency metric: CI violations per PR. Week 1 (before DS): ~15 violations per agent PR. Week 4 (after CLAUDE.md + lint): ~3. Week 8 (after components): ~0-1. Trend to zero = DS governance working. (6) agent reviewer (optional): second agent reviews first agent's UI code specifically for DS compliance. Pattern: generator agent → reviewer agent → human reviews business logic only."
		principlesApplied: ["ax-01", "ax-03", "ax-05"]
		assumptions: [
			"CLAUDE.md instruction is sufficient to change agent behavior — may need few-shot examples in docs",
			"CI lint for Tailwind utilities is implementable — eslint-plugin-tailwindcss or custom rule",
			"components prevent token misuse — agent still needs to select correct component (docs must be clear)",
			"visual inconsistency compounds with sessions — validated: 50 sessions × 10 decisions = 500 independent choices",
		]
		rationale: "DS as prompt 2024+. CI as enforcer 2024+. Without DS: N agent sessions = N visual styles (mathematical certainty). With DS + CLAUDE.md + CI + components: N sessions = 1 style. The constraint system is what makes AI-generated UI viable at scale."
	},
	{
		id:       "ex-mvds-implementation-plan"
		scenario: "Solo founder needs to ship MVP in 6 weeks. Full design system with 50 components, comprehensive docs, Figma sync, and theme builder: estimated 3 months. No design system: visual chaos that will cost 3 months to fix later. Need: minimal viable DS that ships in 1 week."
		analysis: "Trade-off: 1 week DS investment (out of 6 week total = 17% of timeline) prevents: visual inconsistency in remaining 5 weeks of agent-generated development, plus ongoing maintenance burden. Without DS: agent generates ~100 UI elements over 5 weeks, each with independent styling decisions. Inconsistency correction after launch: estimated 60-80 hours (reviewing every element, normalizing, testing). With MVDS: 42 hours of investment, zero inconsistency from day 8 onward."
		recommendation: "**Week 1 Plan (42 hours total):** Day 1 (Mon) — Tokens (4h): create tokens.css. All color, spacing, font-size, weight, radius, shadow tokens. Result: foundation exists. Day 2 (Tue) — Core primitives (8h): Button (3 variants, 3 sizes, all states), Input (text, number, currency, date, with validation states), Badge/StatusBadge (5 semantic intents, 2 sizes). Day 3 (Wed) — Data components (8h): DataTable (headers, rows, sort, pagination — basic, no batch yet), MetricCard (value, label, sparkline placeholder, delta). Day 4 (Thu) — Feedback + containers (6h): Toast (success, error, info), Modal (sm, md, lg with confirmation pattern), Skeleton (card, table-row, text-line). Day 5 (Fri) — Form + docs (8h): FormField (label + input + validation message), Select (single, searchable). Component docs: 1 page per component (props, when to use, example). Day 6 (Mon week 2) — Integration (8h): CLAUDE.md update with component list + token rules. Test: agent generates sample page using MVDS → visually consistent? Fix gaps. CI: add 'no-raw-colors' lint rule (simplest, highest impact). **Result at day 6:** 10 components, ~145 tokens, basic docs, CLAUDE.md, 1 CI rule. Every agent session from day 7: produces consistent UI. **Expansion plan (weeks 3-6, as needed):** Sparkline component (when KPI cards built). ActionBar + batch (when batch operations built). SidePanel (when drill-down established). CommandPalette (when 20+ actions). Each: 4-8 hours, justified by usage."
		principlesApplied: ["ax-01", "ax-03", "dp-01"]
		assumptions: [
			"42 hours in 1 week is feasible for solo founder — intense but scoped (6-8h/day for 6 working days)",
			"10 components cover 80% of MVP UI — may need 12-15, but additional 2-5 can be added in weeks 3-6",
			"agent produces consistent output after MVDS — validated by Day 6 test; iterate if gaps found",
			"Sparkline can be deferred — KPI cards use delta indicator only until Sparkline is built",
		]
		rationale: "MVDS 2023+. Invest-as-you-go 2024+. 42 hours (1 week) of DS prevents: (a) ~100 inconsistent UI elements over 5 weeks. (b) 60-80 hours of post-launch cleanup. (c) ongoing debt of ~10h/month maintaining inconsistent code. Net ROI: 42h invested, 60-80h saved in first quarter, plus ongoing savings. The question isn't 'can we afford 1 week on DS?' — it's 'can we afford NOT to, when agent generates UI at tokens-per-second speed?'"
	},
	{
		id:       "ex-fidc-white-label-theming"
		scenario: "FIDC client requests white-label portal: their brand color (navy #1a3b5c) instead of Mesh default (teal), their logo, and their corporate font (IBM Plex Sans). Without token architecture: forking entire codebase. With tokens: token override."
		analysis: "White-label requirements: (1) brand color change: affects buttons, links, active states, focus rings, selected items. ~15 component instances using brand color. (2) logo: config, not code (logo URL in config). (3) corporate font: typeface change affecting entire interface. With tokens: override 3 token families (brand color, logo, font-family). Without tokens: find and replace 15+ brand color usages, change font-family in 30+ components, maintain fork for this client."
		recommendation: "(1) Brand color override (1h): .theme-fidc-client-a { --color-brand-primary: #1a3b5c; --color-brand-primary-hover: #152f4d; --color-brand-primary-active: #10243e; --color-brand-contrast: #ffffff; /* white text on navy */ }. All Button, Link, ActiveNav, FocusRing, SelectedRow: automatically navy. Semantic colors: UNCHANGED. Green success, red error — same across ALL clients. (2) Logo override (30min): config: { fidc_client_a: { logo_url: '/assets/fidc-a-logo.svg', logo_alt: 'FIDC Client A' } }. Sidebar/header component reads config. (3) Font override (1h): .theme-fidc-client-a { --font-family-primary: 'IBM Plex Sans', sans-serif; }. Load IBM Plex Sans (400, 500, 600, 700) for this client. Verify: tabular figures work in IBM Plex Sans (yes — has tnum support). All components: automatically use IBM Plex instead of Inter. (4) Apply: FIDC client A portal root: <body class='density-compact theme-fidc-client-a'>. Both density and theme applied. Zero component code changes. (5) Testing (2h): verify: (a) brand color applied to all interactive elements. (b) semantic colors unchanged (green success, red error). (c) IBM Plex renders correctly at 11-20px compact scale. (d) contrast passes WCAG AA for navy brand color on all backgrounds. (e) logo displays correctly in sidebar. (6) Total effort: 4.5 hours per FIDC client. Not 4.5 weeks. (7) Scale: 10 FIDC clients = 45 hours total. Each client: unique theme file (3-5 token overrides). Same codebase. Zero forks. Maintenance: fix bug once → all clients get fix. (8) Future: FIDC client self-service theme builder: upload logo, pick brand color, select font → preview → apply. Token override generated automatically."
		principlesApplied: ["ax-01", "ax-03"]
		assumptions: [
			"IBM Plex Sans meets TS criteria (legibility at 11px, tabular figures, glyph distinction) — verified: IBM Plex is professional typeface with full feature set",
			"navy (#1a3b5c) on white provides ≥4.5:1 contrast for text — verify: contrast ratio is ~8.5:1 ✓",
			"FIDC clients only need brand customization (not layout/feature) — validate with client requirements",
			"theme file per client is manageable at scale — 10 clients = 10 small CSS files, minimal overhead",
		]
		rationale: "Theme as token layer 2024+. White-label via token override: 4.5 hours per client vs codebase fork (weeks). With 10 FIDC clients: 45 hours total. Without tokens: 10 separate codebases to maintain. Tokens make multi-brand viable, not just possible."
	},
]

principleIds: ["ax-01", "ax-03", "ax-05", "dp-01"]

relatedLenses: [
	{
		lensId:   "lens-information-density-design"
		relation: "complementsWith"
		context:  "ID define density strategy (compact, default, spacious) e composição visual. DT implementa: density modes via token overrides, component library para composição. ID diz 'FIDC = compact, 30 rows visible'; DT diz 'body.density-compact overrides --table-row-height to 24px, --font-size-base to 13px — all components automatically compact'. ID é strategy; DT é infrastructure."
	},
	{
		lensId:   "lens-typographic-systems-for-dense-interfaces"
		relation: "complementsWith"
		context:  "TS define typographic scale, weights, line-heights, typeface. DT tokeniza: --font-size-xs through --font-size-xl, --font-weight-regular through --font-weight-bold, --line-height-tight through --line-height-relaxed, --font-family-primary. TS define design decisions; DT encoda como tokens para implementação. Change propagation: TS decides 'body is now 15px'; DT updates 1 token; all components update."
	},
	{
		lensId:   "lens-color-as-functional-language"
		relation: "complementsWith"
		context:  "CL define semantic colors (5 intents × 3 variants), data palettes, brand vs functional separation, theme adaptation. DT tokeniza all: --color-success-primary, --palette-seq-3, --color-brand-primary. Theme files override CL tokens for dark mode and white-label. CL defines color decisions and values; DT provides the token infrastructure for encoding and overriding them."
	},
	{
		lensId:   "lens-data-visualization-semiotics"
		relation: "complementsWith"
		context:  "DV charts consume DT tokens for consistent styling: chart background = --color-surface-card, axis text = --font-size-xs, grid lines = --color-gray-200, data colors from palette tokens. DT provides tokens; DV chart components consume them. Consistent chart appearance across all dashboards via shared tokens."
	},
	{
		lensId:   "lens-interaction-patterns-for-professional-tools"
		relation: "complementsWith"
		context:  "IP defines interactive components (Button, Input, Toast, Modal, DataTable). These are DT design system components with token-based styling. IP defines behavior (hover → darken, click → confirm); DT defines visual implementation (hover = --color-brand-primary-hover). IP is interaction; DT is composition and styling."
	},
	{
		lensId:   "lens-documentation-as-product"
		relation: "complementsWith"
		context:  "DP defines agent-consumable documentation. DT component docs are prime example: structured (props, types, defaults), concise (1-page per component), with examples (code snippet). DP says 'design for context window efficiency'; DT says 'component doc in 500 tokens: sufficient for agent to use correctly'."
	},
	{
		lensId:   "lens-ai-agent-governance"
		relation: "complementsWith"
		context:  "AAG governs agent behavior broadly. DT design system governance is the visual-specific manifestation: tokens are visual policies, components are visual vocabulary, CI lint is visual enforcement, CLAUDE.md is visual onboarding. AAG governs architecture + behavior; DT governs visual output. Together: agent produces code that is architecturally sound AND visually consistent."
	},
	{
		lensId:   "lens-progressive-disclosure-and-information-architecture"
		relation: "complementsWith"
		context:  "PD defines navigation patterns, drill-down, layouts. DT provides layout tokens (breakpoints, grid columns, container widths, sidebar widths) and template components (DashboardTemplate, DetailTemplate). PD defines information structure; DT provides the layout infrastructure to implement it."
	},
]

limitations: [
	{
		description: "Token extraction from existing codebase is labor-intensive initial investment (estimated 30h for medium codebase)."
		alternative: "Incremental extraction: when touching component for feature work, extract its tokens (boy scout rule from TD lens). Start with new components: all token-based from day 1. Existing: migrate incrementally over 2-3 months. Or: agent-assisted extraction (agent scans file, proposes token replacements, human reviews)."
		rationale: "Incremental > big-bang. Agent-assisted > fully manual. Either way: extraction pays for itself in first density/theme change."
	},
	{
		description: "MVDS of 10 components may not cover all MVP UI patterns — some screens may need components not yet built."
		alternative: "For uncovered patterns: use raw HTML/Tailwind with token references (tokens.css imported, use var(--*) for values). Not ideal but consistent via tokens. Promote to component when pattern appears 3+ times. Tokens ensure: even non-component UI uses consistent values."
		rationale: "Token coverage > component coverage. 10 components + token-based raw HTML = 95% visual consistency. 10 components alone = 80%."
	},
	{
		description: "Agent may struggle with complex component APIs — MetricCard with 8 optional props may be misused."
		alternative: "Design components with sensible defaults: most props optional. Agent provides minimum (value, label). Component handles everything else via tokens. Fewer required props = less agent error. Provide 2-3 usage examples in docs (copy-paste friendly)."
		rationale: "Component API complexity ∝ 1/agent reliability. Simplest API that covers use cases = best API for AI-native development."
	},
	{
		description: "Density mode tokens assume all components scale well when spacing values change — some layouts may break in compact (text wrapping where it didn't, overflow in constrained containers)."
		alternative: "Test density modes on all key screens after token override. For components that break: add component-specific token override or min-width/min-height constraint. Keep overrides minimal (<10% of components should need them)."
		rationale: "Test in context. Token system handles 90%. Manual fixes for 10%. Fix is component-specific token, not hardcoded value."
	},
	{
		description: "~165 tokens seems like many — developer or agent may be overwhelmed by choice."
		alternative: "Alias tokens are the working set: ~50 semantic tokens that developers/agents use daily. Globals exist but are rarely referenced directly (aliases abstract them). Component tokens: only where alias doesn't fit. Docs: 'Use --color-text-primary for text. Use --spacing-component for padding. Use --font-size-base for body.' Top 10 tokens cover 80% of use. Full reference for edge cases."
		rationale: "50 alias tokens is the practical working set. 95 globals are implementation detail. Agent learns: 10 tokens for 80% of work, references docs for rest."
	},
]

rationale: "Design tokens são a foundation layer que codifica todas as decisões visuais (cor, espaçamento, tipografia, tamanho, sombra, raio) como variáveis consumíveis por componentes, habilitando: density modes, themes, white-labeling, e consistency governada por sistema em vez de disciplina individual. Na Mesh AI-native com solo founder e agentes gerando UI, esta lens operacionaliza: arquitetura de tokens em 3 camadas (Salesforce Lightning 2019, token-driven development 2024+, token as contract 2024+), composição de componentes com primitivos e compounds (Frost 2016, composition over configuration 2023+), density modes via token override (mode as token layer 2024+), themes (light, dark, white-label) via token override (theme as token layer 2024+, semantic preservation 2024+), responsive layout tokens com breakpoints e content priority (breakpoint-responsive 2024+, content priority 2024+), governança de DS para agentes IA com CLAUDE.md + CI + component docs (design system as prompt 2024+, CI as enforcer 2024+), minimal viable design system de 42 horas (MVDS 2023+, invest-as-you-go 2024+), e spacing system com 4px grid e role hierarchy (spacing roles 2023+, spacing and density 2024+). Universal como infraestrutura de design system; específica como constraint system que governa output visual de agentes IA e habilita multi-persona density + multi-brand theming sem duplicação de código."

}
