package lenses

import "github.com/sw6n297mn8-maker/mesh-spec/architecture/artifact-schemas:artifact_schemas"

dataVisualizationSemiotics: artifact_schemas.#AnalyticalLens & {
id:     "lens-data-visualization-semiotics"
name:   "Semiótica de Visualização de Dados"

purpose: "Orientar decisões sobre como usar visualização de dados como linguagem — cores, formas, posição e movimento carregam significado semântico em dashboards financeiros."
status: "draft"

trigger: {
	conditions: [
		"a decisão envolve como representar dados quantitativos visualmente (charts, graphs, encodings)",
		"a decisão envolve qual tipo de gráfico usar para um dado tipo de pergunta (trend, comparison, composition, distribution, correlation)",
		"a decisão envolve como encodar variáveis em canais visuais (posição, comprimento, cor, tamanho, forma)",
		"a decisão envolve como projetar sparklines, micro-charts e inline visualizations para KPI cards e tabelas",
		"a decisão envolve como evitar erros visuais que distorcem percepção de dados (truncated axis, misleading scale, lie factor)",
		"a decisão envolve como projetar legendas, labels, tooltips e anotações em gráficos",
		"a decisão envolve como projetar visualizações de risco, concentração, scoring e performance de safra para fintech",
		"a decisão envolve como adaptar complexidade de visualização ao chart literacy da persona",
		"a decisão envolve como garantir que charts são acessíveis (colorblind-safe, screen-reader compatible)",
	]
	keywords: [
		"gráfico", "chart", "graph", "plot",
		"visualização", "visualization", "vis", "dataviz",
		"encoding", "canal visual", "visual channel",
		"sparkline", "micro-chart", "mini-chart", "bullet chart",
		"bar chart", "line chart", "scatter", "heatmap",
		"treemap", "funnel", "waterfall", "sankey",
		"eixo", "axis", "escala", "scale", "legend",
		"tooltip", "annotation", "label", "data label",
		"Bertin", "Tufte", "Cleveland", "Munzner", "Few",
		"semiótica", "semiotics", "marks", "channels",
		"concentração", "safra", "vintage", "score gauge",
		"small multiples", "facet", "trellis",
		"lie factor", "data-ink", "chartjunk",
	]
	excludeWhen: [
		"a decisão é sobre densidade informacional e composição de dashboard (quantas métricas, layout de KPI cards) — usar information-density-design",
		"a decisão é sobre sistema de cores semânticas (success, warning, error) — usar color-as-functional-language",
		"a decisão é sobre tipografia em charts e labels — usar typographic-systems-for-dense-interfaces",
		"a decisão é sobre design tokens para styling de charts — usar design-tokens-and-systematic-composition",
		"a decisão é sobre progressive disclosure de dados — usar progressive-disclosure-and-information-architecture",
	]
	rationale: "Visualização de dados é a tradução de números em formas visuais que o olho e o cérebro processam mais rapidamente que texto. Na Mesh com métricas financeiras (inadimplência, concentração, retorno, scoring), operacionais (volume, compliance, qualificação), e de rede (fornecedores, construtoras, operações), a escolha de como visualizar determina: gestor FIDC detecta concentração perigosa em 2 segundos (heatmap com palette correta) ou em 30 segundos (tabela de números). A diferença entre chart que informa e chart que desinforma é a aplicação correta de princípios semióticos — qual mark, qual channel, qual tipo de gráfico para qual pergunta. ID cobre composição de dashboard e quantas métricas; CL cobre sistema de cores funcional; TS cobre tipografia. Esta lens cobre a semiótica — como encodar dados em marks e channels para máxima eficácia perceptual, quais tipos de chart servem quais perguntas, como micro-visualizações maximizam informação por pixel, como manter integridade visual, e como projetar visualizações específicas de fintech (scoring, concentração, safra)."
}

concepts: [
	{
		id:         "dv-marks-and-channels"
		name:       "Marks e Channels: A Gramática Visual de Dados"
		nature:     "theoretical"
		role:       "framework"
		definition: "Bertin (1967, Sémiologie Graphique): fundação da semiótica gráfica — marks (pontos, linhas, áreas) são os elementos visuais básicos; retinal variables (posição, tamanho, valor/lightness, textura, cor, orientação, forma) são os canais que encodam dados nos marks. Cada retinal variable tem propriedades perceptuais diferentes: posição é a mais precisa para dados quantitativos; cor é eficaz para dados categóricos mas imprecisa para quantitativos. Munzner (2014, Visualization Analysis and Design): formaliza channels ordenados por eficácia perceptual para dados quantitativos: (1) posição em escala comum (mais preciso — leitura de bar chart com baseline compartilhada). (2) posição em escalas não-alinhadas (juxtaposed charts). (3) comprimento (bar chart). (4) ângulo/inclinação (line chart slope, pie chart — menos preciso). (5) área (bubble chart — significativamente menos preciso que comprimento). (6) luminância/saturação (heatmap — categórico ok, quantitativo impreciso). (7) volume (3D — quase impossível de julgar com precisão). Cleveland/McGill (1984, 'Graphical Perception: Theory, Experimentation, and Application to the Development of Graphical Methods'): estudo empírico que confirmou e quantificou o ranking perceptual — humanos fazem julgamentos mais precisos com posição e comprimento do que com área e cor, e a diferença é significativa (erros de julgamento 2-3x maiores com área vs posição). Conceito contemporâneo de 'channel budget' (2023+): cada visualização tem budget limitado de channels eficazes — encodar 2-3 variáveis em channels distintos é eficaz (x-position para tempo, y-position para valor, cor para categoria). 5+ variáveis num único chart: overload perceptual — channels interferem entre si, e leitura se torna task de decodificação consciente em vez de percepção pré-atentiva. Solução: distribuir variáveis entre multiple small charts (small multiples, Tufte 1983) em vez de sobrecarregar 1 chart. Conceito de 'preattentive processing' (Healey 1996, evoluído 2022+): certas propriedades visuais (cor, tamanho, orientação, motion) são processadas pelo sistema visual em <200ms sem atenção consciente. Um ponto vermelho em campo de pontos azuis: detectado instantaneamente. Isso é a base de conditional formatting, anomaly highlighting, e status indicators — o encoding que funciona é aquele que o sistema visual pré-atentivo detecta antes que a mente consciente processe."
		meshManifestation: "Na Mesh, channel usage por tipo de dado: (1) inadimplência trend — line chart: x-position encoda tempo (meses), y-position encoda valor (%). 2 channels de máxima eficácia (posição × posição). Preferido sobre: area chart (area implica acumulação, misleading para rate), bar chart (barras desconectadas perdem continuidade temporal). (2) concentração por sacado — horizontal bar chart: comprimento encoda valor (% da carteira), y-position encoda sacado (categórico). Preferido sobre: pie chart (ângulo é menos preciso que comprimento — Cleveland/McGill: 2x mais erros de julgamento com ângulo), treemap (área é menos precisa que comprimento). (3) score distribution — histogram: x-position encoda score range (bins), y-position encoda contagem. Mostra shape da distribuição (normal? bimodal? skewed?). Preferido sobre: scatter com overplotting, box plot sozinho (perde shape). (4) performance por safra — small multiples: 1 mini line chart por safra, mesmo eixo x (meses desde originação), mesmo eixo y (inadimplência %). Preferido sobre: 1 chart com 12 linhas sobrepostas (spaghetti chart — ilegível após 4-5 linhas). (5) heatmap de risco — matrix: rows = sacados, columns = meses, cor (luminância) = inadimplência rate. Cor como channel: eficaz para detectar patterns espaciais ('onde está quente?'), impreciso para valores exatos (tooltip supre). (6) relação score vs default — scatter: x-position = score, y-position = dias em atraso. Cada operação é um ponto. Revela: correlação negativa (score alto → menor atraso) e outliers (score alto com atraso grande = investigar). (7) preattentive highlighting — na tabela de operações: score <50 em vermelho (cor pré-atentiva). Gestor escaneia 50 rows e detecta 3 vermelhos instantaneamente sem ler cada número."
		meshImplication: "Channel selection framework: (1) identify the question — comparison? trend? distribution? correlation? composition? (2) select primary encoding — use highest-ranked channel available: position > length > angle > area > color for quantitative data. (3) add secondary encoding — if 2 variables: use 2 high-ranked channels (x-position + y-position = scatter/line). If 3: add color as categorical differentiator. (4) max 3 encoded variables per chart — if more: small multiples (facet by 1 variable, encode remaining 2-3 in each facet). Never 5 variables in 1 chart. (5) preattentive encoding for anomalies — anomalous data point: encode with color (red among neutral) or size (large among small). Detected in <200ms. Non-anomalous: neutral color, standard size. (6) channel matching table for agents — CLAUDE.md or design guide: 'comparison → bar (length). Trend → line (position × time). Distribution → histogram (position × position). Correlation → scatter (position × position). Composition → stacked bar (length × position). Spatial pattern → heatmap (color × position × position).' Agente que gera chart: consulta table, seleciona type. (7) avoid: pie chart (ângulo impreciso — bar chart quase sempre superior), dual y-axis (cria falsa correlação visual), 3D charts (volume é canal impossível de julgar), area chart quando line suffice (area implica acumulação). Anti-pattern: 'scatter plot colorido por 5 categorias com tamanho variável e shape diferente por segmento' — 5 channels num chart, overload perceptual. Nenhuma variável é lida com precisão porque todas competem."
		rationale: "Bertin 1967: sémiologie graphique. Munzner 2014: channel effectiveness ranking. Cleveland/McGill 1984: empirical validation. Channel budget 2023+. Preattentive processing Healey 1996. Na Mesh, bar chart para concentração (length — preciso) é perceptualmente superior a pie chart (angle — 2x mais erro). A diferença não é estética — é accuracy de julgamento."
	},
	{
		id:         "dv-chart-type-selection"
		name:       "Seleção de Tipo de Gráfico: Cada Pergunta Tem um Chart Ótimo"
		nature:     "operational"
		role:       "method"
		reviewCadence: "semi-annual"
		definition: "Schwabish (2021, Better Data Visualizations): chart type follows question type — a visualização é resposta visual a uma pergunta, não decoração de dados. Few (2012, Show Me the Numbers, 2nd ed.): match chart type to data relationship. Conceito de 'question-driven chart selection' (2023+): framework de seleção: (1) 'how much? which is bigger?' → bar chart (horizontal para muitas categorias, vertical para poucas). (2) 'how does it change over time?' → line chart (contínuo) ou slope chart (2 pontos no tempo). (3) 'what's the breakdown? what's the composition?' → stacked bar (composição por categoria) ou treemap (composição hierárquica). (4) 'how are they related? do they correlate?' → scatter plot (2 variáveis) ou bubble chart (3 variáveis: x, y, size). (5) 'what's the distribution? what's the shape?' → histogram (1 variável) ou box plot (comparar distribuições). (6) 'where are patterns? what's the spatial structure?' → heatmap (matrix patterns) ou choropleth (geographic patterns). (7) 'what's the flow? how does value transform?' → sankey (flows entre categorias) ou waterfall (aditivo/subtrativo). Conceito de 'chart literacy calibration' (2024+): audiência com chart literacy alta (FIDC gestores financeiros): scatter plots, heatmaps, box plots, small multiples — lêem fluentemente. Audiência com chart literacy média (construtora gestores operacionais): bar, line, sparklines — familiar e eficaz. Audiência com chart literacy baixa (fornecedor PME): números grandes, badges de status, listas simples — charts são friction, não valor. Calibrar chart complexity à literacy da persona: não enviar heatmap para fornecedor PME."
		meshManifestation: "Na Mesh, chart selection por pergunta × persona: **FIDC (literacy alta):** (a) 'inadimplência trend?' → line chart (monthly, 12-24 meses, with target reference line). (b) 'concentração?' → horizontal bar chart (top 10 sacados, sorted descending, with regulatory limit line at 30%). (c) 'score vs default?' → scatter plot (cada operação = ponto, x=score, y=dias em atraso, color=status). (d) 'safra performance?' → small multiples: 12 mini line charts (1 por safra), same axes. OR heatmap (safra × month → color = inadimplência %). Toggle entre views. (e) 'risk spatial?' → heatmap (sacado × mês → inadimplência). (f) 'score distribution?' → histogram (score bins × count). (g) 'cash flow?' → waterfall (opening → receivables → payments → anticipated → closing). **Construtora (literacy média):** (a) 'quantos qualificados?' → KPI number (47), not chart. Chart adds no value for single number. (b) 'volume trend?' → sparkline (inline 8-week, no axis — just direction). (c) 'compliance by fornecedor?' → horizontal bar (sorted by compliance %, color-coded by status). (d) 'performance comparison?' → bar chart (top/bottom fornecedores). **Fornecedor (literacy baixa):** (a) 'status?' → badge (aprovado ✓ / pendente 🔄 / rejeitado ✗). Not chart. (b) 'minhas taxas ao longo do tempo?' → simple line (5-6 pontos, large, labeled, no jargon). (c) 'quanto recebo?' → single number, grande (R$48.750). Charts são overhead cognitivo para fornecedor PME que quer 1 resposta."
		meshImplication: "Chart selection decision tree (for agents and designers): (1) identify question type (comparison, trend, distribution, correlation, composition, spatial, flow). (2) identify persona (FIDC → full vocabulary, construtora → medium, fornecedor → minimal). (3) select chart from matrix: question × persona. (4) validate: does selected chart answer the question in the persona's language? If construtora asks 'como está compliance?': horizontal bar sorted by % (sim). Heatmap de compliance × mês (não — overcomplicated for the question). (5) chart type prohibition list: (a) pie chart — quase sempre inferior a bar chart. Exceção: 2 fatias (binário: compliant 92% / non-compliant 8%). Máximo 3 fatias. (b) donut chart — pie chart com buraco. Mesmos problemas. (c) dual y-axis — cria percepção de correlação que pode não existir. Dois charts lado a lado com eixos independentes: mais honesto. (d) 3D qualquer coisa — perspectiva distorce valores. Sem exceção. (e) radar/spider chart — áreas difíceis de comparar, distorcidas por ordem de eixos. Bar chart serve melhor. (f) gauge/speedometer — ocupa muito espaço para 1 número. Bullet chart é mais compacto e informativo. (g) area chart quando line suffice — area implica volume/acumulação. Usar area apenas para dados acumulados (stacked area para composição ao longo do tempo). (6) chart library padronizado — design system includes: LineChart, BarChart, HorizontalBar, Scatter, Histogram, Heatmap, SmallMultiples, Sparkline, BulletChart, Waterfall. Componentes com props padronizados. Agente compõe a partir da library. Não cria SVG custom. Anti-pattern: 'gráfico bonito' como objetivo — chart que é visualmente atraente mas não responde a pergunta com precisão é chartjunk. Objetivo é clarity, não beauty."
		dependsOn: ["dv-marks-and-channels"]
		crossDependsOn: [{
			lensId:    "lens-multi-sided-platform-ux"
			conceptId: "mux-per-side-experience"
			context:   "MUX define experiência diferenciada por lado da plataforma. DV chart type selection calibra complexidade de visualização por persona: FIDC (high literacy) gets scatter, heatmap, small multiples. Construtora (medium) gets bar, line, sparkline. Fornecedor (low) gets numbers and badges, not charts. MUX diz 'experiência por lado'; DV diz 'chart vocabulary por lado — proporcional ao chart literacy'."
		}]
		rationale: "Schwabish 2021: chart follows question. Few 2012: match chart to data. Question-driven 2023+. Chart literacy calibration 2024+. Na Mesh, heatmap de risco para FIDC (appropriate — FIDC lê heatmaps) vs heatmap para fornecedor (inappropriate — fornecedor não entende heatmaps). Chart type mismatch com literacy é tão ruim quanto chart type mismatch com dados."
	},
	{
		id:         "dv-sparklines-and-micro-vis"
		name:       "Sparklines e Micro-Visualizações: Dados em Espaço Mínimo"
		nature:     "operational"
		role:       "property"
		reviewCadence: "semi-annual"
		definition: "Tufte (2006, Beautiful Evidence): sparklines são 'datawords: data-intense, design-simple, word-sized graphics.' Inline com texto ou números, sparklines comunicam trend sem consumir real estate de chart completo. São contexto temporal para números isolados — '1.8%' é um número; '1.8%' + sparkline descendo = tendência de melhora. Diferença de valor informacional: ordens de magnitude. Conceito contemporâneo de 'micro-visualizations' (2023+): além de sparklines, um vocabulário de representações compactas: (a) bullet chart (Few 2006) — target vs actual em espaço mínimo: barra mostrando valor atual, marca de referência para target, faixas de background para zones (poor/ok/good). ~120×16px. (b) progress bar — percentual completo em barra horizontal. (c) delta indicator — seta (↑↓→) + percentual + cor semântica. Direction + magnitude em 3-5 characters. (d) status dot — 8px circle com cor semântica. 1 pixel de informação. (e) mini histogram — 8-12 barras em 60×20px, mostrando distribution shape. (f) win/loss sparkline — sequência de ticks positivos e negativos mostrando pattern de success/failure. Conceito de 'glanceable data' (2024+): representações projetadas para <2 segundos de comprehension. Sparkline: direction em <1 segundo. Bullet chart: performance vs target em <1 segundo. Delta indicator: change em <0.5 segundo. Não são alternativas a charts completos — são complementos: glanceable em KPI cards e table cells para scan rápido, full charts para deep analysis quando scan indica necessidade."
		meshManifestation: "Na Mesh, micro-vis por contexto: (1) KPI cards (construtora e FIDC) — sparkline de 8-12 semanas inline mostrando trend do KPI. 'Inadimplência: 1.8%' + sparkline descendo = gestor vê melhora em <1 segundo. Sem sparkline: gestor vê número isolado sem context temporal — '1.8% é bom? Está melhorando? Piorando?' Indecidível. (2) KPI cards — delta indicator: '↑8.3% vs mês anterior' em success color (se aumento é positivo, e.g. lastro) ou error color (se aumento é negativo, e.g. inadimplência). Delta inverts meaning by metric. (3) table cells (FIDC operações) — sparkline de score últimos 6 meses por comprador, inline em cell da tabela. Gestor escaneia 50 rows: sparklines subindo = portfólio saudável. Sparklines descendo em 3 rows = investigar esses 3. Pattern detection em <5 segundos para 50 rows. (4) table cells (construtora fornecedores) — bullet chart de compliance: barra mostrando % atual contra zones (0-70 red, 70-90 yellow, 90-100 green). Em 1 glance: fornecedor está na zona correta ou não. (5) fornecedor operação — delta na taxa: '2.5% (↓0.3% vs sua última operação).' Fornecedor vê: taxa melhorou. Sem delta: fornecedor não tem comparação. (6) status dot — compliance status em tabela: ● verde, ● amarelo, ● vermelho. Combinado com text label (acessibilidade): 'ok ●', 'atenção ●', 'crítico ●'. Scan de 50 fornecedores por status: <3 segundos."
		meshImplication: "Micro-vis como componentes do design system: (1) Sparkline component — props: data (number[], 8-12 points), threshold (optional reference line), color (semantic: neutral default, error if below threshold). Render: polyline 80×20px, last-point dot emphasized, optional threshold dashed line. No axis, no labels — context from surrounding text/number. (2) DeltaIndicator — props: current, previous, invertPositive (boolean, true for metrics where decrease is good like inadimplência). Render: arrow (↑↓→) + formatted percentage + semantic color. Compact: ~40px width. (3) BulletChart — props: actual, target, zones [{min, max, color}]. Render: horizontal bar with reference mark and zone backgrounds. ~120×16px. (4) StatusDot — props: status enum. Render: 8px circle with semantic color (from CL lens). Always paired with text label. (5) MiniHistogram — props: data (number[]), bins (number, default 8). Render: 8 bars in 60×20px. No axis — just shape. (6) usage rules: sparkline em every KPI card (trend context é obrigatório). Delta em every KPI card (comparison é obrigatório). Status dot em every table with status column. Bullet chart onde target exists. Mini histogram onde distribution matters (score distribution no header da coluna). (7) accessibility: every micro-vis has aria-label com text equivalent: sparkline aria-label='tendência de 8 semanas: crescente, de 1.2% para 1.8%'. Screen reader obtém mesma informação. Color never sole encoding — dot always with text, sparkline with number. (8) mobile: sparklines render at 60×16px minimum on mobile. Smaller: illegible. If space insufficient: show delta indicator instead (smaller, still informative). Anti-pattern: sparkline sem número associado — sparkline alone doesn't communicate absolute value. '1.8%' + sparkline = completo. Sparkline sozinha = 'algo está subindo, não sei o que nem de quanto.'"
		dependsOn: ["dv-marks-and-channels"]
		crossDependsOn: [{
			lensId:    "lens-information-density-design"
			conceptId: "id-kpi-dashboard-design"
			context:   "ID define metric card anatomy: hero number + label + trend + comparison. DV sparklines provê o componente de trend: sparkline inline no card comunica pattern temporal em <1 segundo. DeltaIndicator provê comparison numérica. ID é a composição do card; DV é o encoding visual dos componentes de trend e comparison dentro do card. ID diz 'card tem 4 elementos'; DV diz 'trend element é sparkline de 8-12 weeks com threshold reference, comparison element é delta com arrow + % + semantic color'."
		}]
		rationale: "Tufte 2006: sparklines as datawords. Few 2006: bullet charts. Micro-visualizations 2023+. Glanceable data 2024+. Na Mesh, '1.8% + sparkline descendo + ↓0.3pp' em KPI card: contexto completo (valor absoluto + trend + change) em <2 segundos. '1.8%' alone: 1 dado sem contexto."
	},
	{
		id:         "dv-visual-integrity"
		name:       "Integridade Visual: O Chart Deve Representar os Dados com Honestidade"
		nature:     "theoretical"
		role:       "heuristic"
		definition: "Tufte (1983, The Visual Display of Quantitative Information): lie factor = size of effect shown in graphic / size of effect in data. Lie factor = 1: truthful. >1: exaggeration. <1: understatement. Distorções comuns e suas consequências: (1) truncated y-axis em bar chart — barra começando em 98% em vez de 0% faz diferença de 2% parecer 100% da altura do gráfico. Lie factor: height of bar / actual difference × scale. Barras devem começar em 0 (always). (2) dual y-axis — 2 escalas no mesmo gráfico criam falsa correlação visual. Se linha A sobe e linha B sobe, mas escalas são diferentes: percepção de correlação onde pode não haver. Solução: 2 charts lado a lado com escalas independentes, ou normalizar ambas em index (100 = baseline). (3) area scaling — se valor dobra, radius de circle dobra, mas area quadruplica. Percepção de size é por area (2D), não radius (1D). Se bubble chart: area proporcional a value, não radius. (4) 3D perspective — perspectiva oculta valores atrás de outros, distorce proporções. Sem exceção: nunca 3D. (5) cherry-picked timeframe — mostrar 3 meses de uptrend em 12 meses de downtrend. Contexto temporal deve ser suficiente para pattern verdadeiro. (6) suppressed baseline em line chart — line chart pode ter y-axis que não começa em 0 (menos distorcido que bar chart porque line encoda slope, não length), mas deve ser labeled explicitamente. Few (2012): 'quantitative data should be represented with visual properties that our eyes perceive as proportionally accurate.' Conceito contemporâneo de 'responsible visualization' (2024+): em fintech, distorted visualization pode causar financial decisions based on misperception. Inadimplência chart com truncated axis faz 1.5%→1.8% parecer crise. FIDC gestor pode sair de posição baseado em percepção visual, não em dado real. Responsible vis: fidelidade perceptual é requisito funcional, não aspiração estética."
		meshManifestation: "Na Mesh, integridade é non-negotiable em: (1) inadimplência charts — bar chart: y-axis começa em 0. Line chart: se y-axis não começa em 0 (para ampliar sinal): label explícito 'eixo inicia em 1.0%' + anotação de scale. Sempre incluir target reference line (2.5%) para contexto. 1.8% é alarm? Depende: se target é 2.5%, 1.8% é bom. Se target é 1.0%, 1.8% é ruim. Sem reference: interpretação ambígua. (2) score distributions — histogram: bins de largura igual. Bins desiguais (0-40, 40-60, 60-80, 80-100) distorcem shape porque área de bins desiguais não é comparável. Se bins customizados necessários: normalize por largura (density histogram). (3) concentração — bar chart: y-axis começa em 0. Sacado com 12% da carteira deve parecer 12% da barra, não 100%. Regulatory limit line at 30%: contexto visual de 'quanto falta para o limite.' (4) safra performance — SAME SCALE across all small multiples. Se safra A usa y-axis 0-5% e safra B usa 0-10%: comparação visual é impossível (safra A com 4% preenche 80% do chart, safra B com 4% preenche 40%). Shared axis é obrigatório para small multiples. (5) retorno — CDI+3.7% deve ser apresentado com context: retorno absoluto vs retorno relativo a benchmark. Se chart mostra apenas 3.7%: gestor pode esquecer que é sobre CDI. Label: 'Retorno: CDI+3.7% (absoluto: ~14.4%).' (6) temporal context — default: últimos 12 meses. Se usuário seleciona 1 mês: caveat 'mostrando último mês. Para contexto completo: [expandir para 12 meses].' 1 mês pode mostrar anomalia que 12 meses contextualiza."
		meshImplication: "Integrity rules implementadas no design system: (1) bar chart component: y-axis minimum forcado em 0. Props não permite override. Se signal é pequeno (1.5% → 1.8%): não usar bar chart — usar line chart (line encoda slope, não length, y-axis não precisa de 0). (2) line chart component: y-axis default starts at data_min - 10%. Label de axis range sempre visível. Props: showAxisWarning (boolean, true quando y-axis não começa em 0). (3) small multiples: shared_axis = true por default. Para override: explícito com justificativa (ADR). (4) no dual y-axis — não existe como props no chart component. Se 2 metrics precisam de comparison: 2 charts lado a lado. Or: normalize ambas em index (100 = first data point). (5) no 3D — chart components não têm opção 3D. (6) reference lines — props: references [{value, label, color, style}]. Usar para: target, regulatory limit, average, threshold. Adicionam context que previne misinterpretation. (7) annotations — props: annotations [{dataPoint, text}]. Usar para: anomalies ('Dez 2025: sazonalidade construção'), events ('Mar 2026: nova regulação'), context ('abaixo do target'). Annotation previne: gestor vê spike, assume problema, quando na verdade é sazonalidade conhecida. (8) timeframe — default 12 meses para charts de trend. User pode ajustar. Se <3 meses selecionado: warning 'período curto — trend pode não representar padrão.' (9) number labels — bar chart com ≤10 bars: label cada barra com valor exato. Line chart: label último ponto e qualquer ponto anotado. Reduce need to estimate from axis. Anti-pattern: inadimplência bar chart com y-axis começando em 1.5% — change de 1.5% para 1.8% preenche 100% da altura do chart. Lie factor ≈ 5x. FIDC gestor vê: 'crisis.' Realidade: 0.3 percentage points de change em escala de 0-100%. Responsible visualization: bar chart com y-axis 0-3% mostra change como 10% da altura — proportional e honest."
		dependsOn: ["dv-marks-and-channels"]
		crossDependsOn: [{
			lensId:    "lens-trust-and-credibility-design"
			conceptId: "tc-transparency-calibration"
			context:   "TC define calibrated transparency — revelar informação suficiente para decisão informada sem overwhelm. DV visual integrity é transparency aplicada a charts: chart com y-axis truncado esconde scale; chart com reference line e annotation revela context. TC diz 'transparência calibrada'; DV diz 'integridade visual com reference lines, annotations, e scales honestas é como transparency se manifesta em visualizações'. Chart desonesto é opacidade — esconde a verdadeira magnitude. Chart honesto é transparência — mostra magnitude real com context suficiente para interpretar."
		}]
		rationale: "Tufte 1983: lie factor. Few 2012: proportional accuracy. Responsible visualization 2024+. Na Mesh fintech, chart que distorce percepção → decisão financeira baseada em misperception. Y-axis começando em 0 para bar charts é non-negotiable. Reference lines para context é obrigatório. Integrity não é guideline — é requisito funcional."
	},
	{
		id:         "dv-labels-tooltips-annotations"
		name:       "Labels, Tooltips e Anotações: Contexto Sem Clutter"
		nature:     "operational"
		role:       "property"
		reviewCadence: "semi-annual"
		definition: "Três camadas de texto em charts: (1) Labels — texto permanentemente visível no chart (valor em cima de barra, label do último ponto em line chart). Vantagem: leitura imediata. Custo: espaço visual. Quando: poucos data points (≤10 barras) ou key points (último ponto de line). (2) Tooltips — informação contextual mostrada on hover/tap. Vantagem: contexto completo sem clutter. Custo: requer interação. Quando: muitos data points, detalhes que complementam visual. (3) Annotations — texto explicativo ligado a data points específicos. Vantagem: explica anomalias, marca eventos. Custo: adiciona elementos visuais. Quando: anomalias que precisam de explicação, eventos que afetam dados. Conceito de 'progressive labeling' (2023+): hierarquia de texto no chart: always-visible (key data points), on-hover (all data points with detail), on-demand (annotations toggle on/off). Esta hierarquia previne clutter enquanto garante que toda informação é acessível. Schwabish (2021): 'the chart should tell the story — labels, titles, and annotations are part of the story, not afterthoughts.' Título do chart é a pergunta ou insight. Annotation é o contexto. Label é a evidência."
		meshManifestation: "Na Mesh, labeling strategy por chart type: (1) line chart (inadimplência trend) — always-visible: label do último ponto ('1.8%'). Reference line label ('target: 2.5%'). Title: 'Taxa de Inadimplência — Últimos 12 Meses.' On-hover: tooltip com date + value + comparison: 'Fev 2026: 1.8%. Mês anterior: 1.9%. Target: 2.5%. ↓0.1pp MoM.' Annotation: eventos significativos: 'Dez 2025: sazonalidade construção ↑.' (2) bar chart (concentração) — always-visible: value label em cada barra (top 10, ≤10 bars: label all). Limit line label: 'limite regulatório: 30%.' On-hover: tooltip com: sacado name, valor absoluto, % da carteira, trend vs mês anterior. (3) scatter (score vs default) — always-visible: nenhum (muitos pontos — labels sobreporiam). Axis labels: 'Score' (x), 'Dias em Atraso' (y). Quadrant labels: 'Alto Risco', 'Monitorar', 'Baixo Risco.' On-hover: tooltip com: operação ID, score, dias, fornecedor, valor. Annotation: outliers marcados com call-out se known issue. (4) heatmap — always-visible: color legend com scale (0% → 5%+). Row/column headers. On-hover: tooltip com: sacado, mês, exact value, comparison to average. (5) small multiples (safras) — always-visible: label do último ponto de cada mini-chart. Shared axis labels. Title de cada mini-chart: safra ID."
		meshImplication: "Labeling rules para design system: (1) every chart has title — title é pergunta ou insight: 'Inadimplência por Mês' (pergunta) ou 'Inadimplência Caiu 0.3pp no Último Trimestre' (insight). Insight title é mais informativo se chart conta história conhecida. (2) every chart has tooltip — tooltip para todo data point interativo. Tooltip format padronizado: primary value + date/category + comparison + additional context. Consistente cross-charts. (3) label key points — bar chart ≤10 bars: all labeled. Line chart: last point + annotated points. Scatter: no labels (hover for detail). Heatmap: legend always visible. (4) annotations for anomalies — if data point is unusual: annotate with explanation. If no explanation known: annotate with '? investigar'. Annotation prevents misinterpretation of anomaly as pattern. (5) number formatting consistent — all labels, tooltips, and annotations use same formatting: currency (R$X.XXX,XX), percentage (X,X%), date (mmm/yyyy for charts). From design token system (TS/DT lenses). (6) mobile tooltips — no hover on mobile. Tap to show tooltip (as overlay). Tap outside to dismiss. Tooltip positioned to not obscure data point. Tap target: minimum 44×44px hit area around data point. (7) color legend positioning — right of chart or below chart. Not overlapping chart area. Legend items clickable to toggle series on/off (useful for line charts with multiple series). (8) axis labels — always present. Labeled with unit: 'Inadimplência (%)', 'Valor (R$ mil)', 'Score (0-100).' Not just 'Value' or unlabeled. Anti-pattern: chart com 30 barras todas labeled — labels sobrepostos, ilegíveis. Ou: chart sem tooltip — data points sem detail, user guesses values from axis."
		dependsOn: ["dv-marks-and-channels", "dv-visual-integrity"]
		rationale: "Progressive labeling 2023+. Schwabish 2021: chart tells the story. Na Mesh, line chart com título 'Inadimplência Caiu 0.3pp', último ponto labeled '1.8%', reference line 'target 2.5%', tooltip com MoM comparison, e annotation de sazonalidade: storytelling visual completo em 1 chart. Mesmo chart sem título, sem labels, sem reference, sem tooltip: ambíguo."
	},
	{
		id:         "dv-fintech-specific-visualizations"
		name:       "Visualizações Específicas de Fintech: Scoring, Concentração, Safra e Risco"
		nature:     "operational"
		role:       "method"
		reviewCadence: "quarterly"
		definition: "Fintech tem necessidades de visualização que não são cobertas por charts genéricos. Domain-specific visualization patterns: (1) score gauge — representação visual de score dentro de range e zones. Formas: bullet chart (Few 2006, preferido — compacto e preciso), semicircular gauge (familiar mas ineficiente em espaço), linear gauge (horizontal bar com zones). Score sem gauge: '65' — número sem contexto. Score com gauge: '65' na zona verde (60-80) = 'bom, próximo do limite inferior da zona boa.' Contexto transforma número em compreensão. (2) concentration/exposure chart — Lorenz curve (formal, para reports) ou horizontal bar chart (prático, para dashboards) mostrando distribuição de exposição. Regulatory context: limite de concentração por sacado (e.g., 30%). Bar chart com reference line at 30%: compliance visual. (3) vintage/safra analysis — cohort performance over time. Cada safra é um cohort; performance (inadimplência, loss rate) medida por meses desde originação. Visualization: small multiples (1 line chart por safra — precisão) ou heatmap (safra × month → color — pattern detection). Safra analysis é como credit risk é avaliado ao longo do tempo — fundamental para FIDC. (4) waterfall chart — mostra como valor inicial se transforma em final through additions and subtractions. Para: cash flow (opening → receivables → payments → anticipated → closing), portfolio changes (opening → new → matured → defaulted → closing). (5) risk matrix/scatter — 2D mapping de probability × impact. Para operações: score (probability proxy) × value (impact). Quadrants: high risk (low score + high value), investigate (high score + high value), monitor (low score + low value), low risk (high score + low value). (6) funnel (pipeline) — para NGR bounded context: leads → qualified → contracted → operating. Cada stage com count and conversion rate."
		meshManifestation: "Na Mesh, fintech vis por interface: (1) operação detail (construtora + FIDC) — score gauge: bullet chart horizontal mostrando score (65) contra zones (0-40 red 'alto risco', 40-60 yellow 'atenção', 60-80 green 'bom', 80-100 dark green 'excelente'). Tooltip: 'Score: 65. Zona: Bom. Modelo: v2.3. Features principais: histórico de pagamento (peso 40%), receita (peso 25%), tempo de relacionamento (peso 20%), setor (peso 15%).' Feature importance como sub-chart: horizontal bar chart compacto mostrando peso de cada feature. (2) FIDC carteira — concentração: horizontal bar chart, top 10 sacados, sorted descending. Vertical reference line at 30% (regulatory limit). Bars exceeding limit: warning color. Summary: 'Concentração máxima: 12% (Sacado ABC). Limite regulatório: 30%. ✓ Dentro do limite.' (3) FIDC safras — toggle: small multiples (precisão) / heatmap (pattern). Small multiples: 1 mini line chart por safra, x = meses desde originação (0-12), y = inadimplência acumulada (%), same scale. Heatmap: rows = safras (newest at bottom), columns = meses, color = inadimplência (white → red sequential). Insight visual: se bottom-left é mais claro que top-left: safras mais novas performam melhor = model/origination improving. (4) construtora cash flow — waterfall: abertura → recebíveis gerados → pagamentos recebidos → antecipações → fechamento. Bars verdes para additions, vermelhas para subtractions, azul para totals. (5) FIDC risk scatter — cada operação como dot: x = score, y = valor. Quadrant backgrounds em cores semânticas sutis. Outliers (score alto + valor alto + em atraso) marcados com annotation."
		meshImplication: "Fintech vis como componentes do design system: (1) ScoreGauge — props: score (number 0-100), zones (array [{min, max, color, label}]). Render: bullet chart horizontal com zones, marker, label. Default zones: 0-40 'Alto Risco', 40-60 'Atenção', 60-80 'Bom', 80-100 'Excelente.' Zones configuráveis por construtora. Tooltip: score value + zone label + model version. Accessibility: aria-label 'score 65 de 100, classificação boa.' (2) ConcentrationChart — props: data ({name, value, percentage}[]), limit (number, regulatory). Render: horizontal bars sorted descending + vertical limit line. Bars > limit: warning color. Summary text above. (3) VintageChart — props: safras ({id, dataPoints [{month, value}]}[]), mode ('multiples' | 'heatmap'). Render: small multiples (default) or heatmap (toggle). Shared scales. Tooltip with exact values. (4) WaterfallChart — props: steps ({label, value, type: 'increase' | 'decrease' | 'total'}[]). Render: connected bars, green for increase, red for decrease, blue for total. Labels on each bar. (5) RiskScatter — props: operations ({score, value, status}[]), quadrants ({label, xRange, yRange, color}[]). Render: scatter with quadrant backgrounds. Hover: operation detail. Click: navigate to operation. (6) FeatureImportance — props: features ({name, weight}[]). Render: horizontal bar chart sorted descending, showing weight %. For score explanation. (7) each component: tested with real Mesh data. Edge cases: zero operations (empty state), 1 safra (single chart, not multiples), all operations in same quadrant (no spread). Anti-pattern: score shown as plain number without gauge — '65' means nothing without zone context. Gestor doesn't know if 65 is pass or fail without reference. Gauge provides reference by design."
		dependsOn: ["dv-marks-and-channels", "dv-chart-type-selection"]
		crossDependsOn: [{
			lensId:    "lens-trust-and-credibility-design"
			conceptId: "tc-trust-in-ai-decisions"
			context:   "TC define trust in AI decisions: users need to understand why AI decided. DV fintech vis provides visual explanation: score gauge with zones explains what score means visually. FeatureImportance bar chart shows why (which features contributed most). Safra analysis shows historical model performance. TC diz 'make AI decisions explainable'; DV diz 'visualize the explanation — zones, feature weights, historical performance — so trust is built through comprehension, not faith'."
		}]
		rationale: "Fintech visualization patterns são domain-specific e não cobertas por charts genéricos. Score gauge, concentration chart, vintage analysis, waterfall, e risk scatter são vocabulário visual obrigatório para plataforma que serve FIDC, construtora, e fornecedor. Na Mesh, score gauge não é decoração — é o primary means pelo qual construtora e FIDC entendem decisões de scoring. Concentration chart com regulatory limit não é analytics — é compliance visualization. Safra analysis não é reporting — é risk management visual."
	},
	{
		id:         "dv-chart-accessibility"
		name:       "Acessibilidade de Charts: Visualizações que Todos Conseguem Ler"
		nature:     "operational"
		role:       "heuristic"
		reviewCadence: "semi-annual"
		definition: "Chart accessibility tem 3 dimensões: (1) color vision deficiency (CVD) — ~8% dos homens e ~0.5% das mulheres têm alguma forma de CVD. Mais comum: deuteranopia (red-green). Charts que dependem de red-green para differentiate: inacessíveis para 8% dos homens. Solução: nunca color alone. Pair com: shape (circle vs square), pattern (solid vs dashed line), position (separate spatially), label (direct label). Palettes CVD-safe: blue-orange, viridis, CARTOcolors. (2) screen reader — chart deve ter text alternative: título, descrição de trend/pattern, key data points. ARIA: role='img' + aria-label com descrição textual. Para charts complexos: hidden table com dados. (3) low vision — minimum contrast ratios per WCAG 2.1: non-text elements (chart lines, bars, data points) ≥3:1 against background. Text (labels, axis, annotations) ≥4.5:1. Conceito de 'redundant encoding' (2023+): cada data encoding tem pelo menos 2 channels. Se cor differentiates 3 series: cor + shape (circle, square, triangle). Se cor shows anomaly: cor + size (larger point). Grayscale test: converter chart para grayscale — toda informação ainda distinguível? Se não: add redundant channel."
		meshManifestation: "Na Mesh, accessibility por chart: (1) multi-series line chart (safras) — cada série: cor diferente + dash pattern diferente (solid, dashed, dotted, dash-dot). Grayscale: series distinguíveis by dash pattern. Direct label para cada série (not just legend). (2) concentration bar — bars em cor primária (não need para differentiate — 1 color). Limit line: dashed (pattern distinguishes from bars). Label on limit: 'limite 30%.' (3) heatmap — sequential palette que funciona em grayscale (white → dark red = light → dark). CVD-safe: luminance gradient, não hue gradient. (4) scatter (risk) — quadrants: não dependem de cor alone. Background color sutil + text label ('Alto Risco') em cada quadrant. Points: shape por status (circle = normal, triangle = alert, square = default). (5) all charts: aria-label com descrição: line chart aria-label='inadimplência nos últimos 12 meses, tendência de queda de 2.1% para 1.8%, abaixo do target de 2.5%.'"
		meshImplication: "Accessibility implementation: (1) CVD-safe palette — never red-green as only differentiator. Default categorical palette: blue, orange, teal, purple, pink, brown. Tested with deuteranopia simulator. (2) redundant encoding — every color encoding has paired secondary encoding. Multi-series: color + dash. Status: color + shape. Anomaly: color + size. Design system: chart components enforce redundancy (series prop accepts {color, dash, shape}). (3) grayscale test — every chart type tested in grayscale (CSS filter: grayscale(100%)). If information lost: fix encoding. CI: automated screenshot + grayscale comparison (manual quarterly if automated not feasible). (4) ARIA — every chart: role='img', aria-label with descriptive text. Complex charts: aria-describedby linking to hidden data table. Chart component generates aria-label from data props automatically: LineChart with title='Inadimplência' and trend='decreasing' generates label. (5) contrast — chart lines/bars: ≥3:1 against background. Validated per CL lens (semantic colors pre-checked). Thin lines (1px): increase to 2px for visibility, or increase color contrast. (6) keyboard navigation — chart data points navigable with arrow keys. Focus shows tooltip. Tab moves between chart regions. For interactive charts (scatter with click-to-detail): keyboard operable. (7) text alternative for micro-vis — sparkline: aria-label='trend crescente.' Delta: aria-label='aumento de 8.3%.' Status dot: text label always present alongside dot. Anti-pattern: heatmap with red-green diverging palette, no text labels, no aria — inacessível para CVD users, screen readers, e low-vision users simultaneously. Triple failure."
		dependsOn: ["dv-marks-and-channels", "dv-visual-integrity"]
		crossDependsOn: [{
			lensId:    "lens-color-as-functional-language"
			conceptId: "cl-accessibility"
			context:   "CL define accessibility para cores: WCAG AA contrast, color-independent encoding. DV chart accessibility aplica: chart elements usam CL semantic colors (pre-checked contrast), chart series use CL categorical palette (CVD-safe), e every color encoding has redundant non-color channel. CL define as cores acessíveis; DV garante que charts as usam corretamente e adicionam redundancy encoding."
		}]
		rationale: "CVD affects 8% of males. Screen readers are used by visually impaired. WCAG 2.1 applies to charts. Redundant encoding 2023+. Na Mesh, FIDC gestor pode ser deuteranopic — scatter com red-green points é inacessível. Blue-orange + shape: accessible. Accessibility não é optional feature — é requisito."
	},
	{
		id:         "dv-small-multiples"
		name:       "Small Multiples: Comparação através de Repetição Estruturada"
		nature:     "theoretical"
		role:       "method"
		definition: "Tufte (1983, 1990): small multiples são 'illustrations of postage-stamp size, indexed by category or time.' Mesma estrutura visual repetida, variando 1 dimensão (tempo, categoria, condição). O olho compara pelo que muda entre os multiples, não pelo que é igual. Vantagem sobre: (a) spaghetti chart (muitas linhas no mesmo chart) — após 4-5 linhas, impossível de ler. Small multiples: cada série é isolada, legível. (b) animation (chart que muda ao longo do tempo) — memory burden: user precisa lembrar frame anterior. Small multiples: todos os frames visíveis simultaneamente, comparação spatial. Conceito contemporâneo de 'faceted visualization' (2022+): small multiples como facets de 1 dataset. Facet por categoria (1 chart por sacado), por tempo (1 chart por safra), ou por condição (1 chart por score range). Cada facet: mesmo chart type, mesma scale, mesmo encoding. Variação é no dado, não na forma."
		meshManifestation: "Na Mesh, small multiples applications: (1) safra analysis (FIDC) — 12 safras × 1 line chart cada. Cada mini-chart: x = meses desde originação (0-12), y = inadimplência acumulada (%). Same x-range (0-12), same y-range (0-5%). Gestor compara visualmente: safra mais recente (bottom) tem curva mais baixa que safra mais antiga (top) = origination quality melhorando. Pattern visible em 3 seconds that 144-cell table couldn't reveal in 3 minutes. (2) performance por segmento (construtora) — 4 segmentos (residencial, comercial, industrial, infraestrutura). 1 bar chart por segmento: fornecedores qualificados vs total. Same scale. Comparison: which segment has highest qualification rate? (3) trend por sacado (FIDC deep analysis) — top 5 sacados: 1 sparkline expandida por sacado. Same time range, same y-range. Gestor compara performance temporal de cada sacado side-by-side."
		meshImplication: "Small multiples guidelines: (1) shared axes — OBRIGATÓRIO. Same x-range, same y-range across all multiples. If different scales: comparison is impossible and misleading. If data ranges are very different: consider normalization (index to 100). (2) layout — grid layout: typically 2-4 columns. Label each multiple clearly with facet category (safra ID, segmento name, sacado name). (3) ordering — meaningful order: chronological (safras by date), by value (best to worst performing), or by category relevance. Not arbitrary. (4) maximum — 12-16 multiples per view. Beyond: pagination or filter. 30 multiples in grid: too small to read. (5) interaction — hover on one multiple: highlight corresponding data in all multiples (linked brushing). User hovers over month 6 in safra A: month 6 highlighted in all safras. Cross-comparison at specific point. (6) fallback — if >16 facets: offer heatmap as alternative. Heatmap compresses many facets into matrix. Toggle between small multiples (precision) and heatmap (scale). (7) responsive — mobile: 1 column (stacked vertically). Larger individual charts. Swipe to compare. Desktop: 3-4 column grid. Anti-pattern: 12 line series overlaid in 1 chart (spaghetti) — after 4 lines: visual chaos. Or: animation of 12 safras played sequentially — user forgets frame 1 by frame 12."
		dependsOn: ["dv-marks-and-channels", "dv-visual-integrity"]
		rationale: "Tufte 1983, 1990: small multiples. Faceted visualization 2022+. Na Mesh, 12 safras as small multiples: pattern of improvement visible in 3 seconds. Same 12 safras as spaghetti chart: indecipherable. Same as animation: memory burden. Small multiples are the right answer for cohort comparison."
	},
	{
		id:            "dv-visualization-review"
		name:          "Revisão de Visualizações: Inventário Periódico de Eficácia Visual"
		nature:        "operational"
		role:          "method"
		reviewCadence: "quarterly"
		definition:    "Inventário periódico que consolida todos os conceitos da lens num snapshot acionável. Para cada período: (1) channel effectiveness — cada chart usa channels ótimos para os dados? Posição para quantitativo? Cor para categórico? (2) chart type — right chart for the question? Any pie charts that should be bars? Dual axes? 3D? (3) sparklines e micro-vis — present em KPI cards e table cells onde trend context é relevante? (4) integrity — y-axes start at 0 for bars? Reference lines for context? Shared scales for small multiples? Annotations for anomalies? (5) labeling — key points labeled? Tooltips on everything? Title tells story? Axis labeled with units? (6) fintech-specific — score gauges, concentration with limits, vintage analysis, waterfall — rendered correctly? (7) accessibility — CVD-safe palette? Redundant encoding? ARIA labels? Grayscale test? (8) small multiples — shared axes? Meaningful order? ≤16 per view?"
		meshManifestation: "Na Mesh: revisão trimestral. Cada chart no produto é auditado contra conceitos desta lens."
		meshImplication: "Quarterly (1.5h): audit every chart in product (likely 10-20 charts at MVP stage). For each chart: (a) what question does it answer? Write it down. If unclear: chart has no purpose — redesign or remove. (b) is chart type optimal for question? Check against selection matrix. If bar chart answers trend question: change to line. If pie chart exists: change to bar (almost always). (c) channel usage: primary variable in highest-ranked channel? Secondary in next? >3 variables: split into small multiples. (d) integrity: bar chart y-axis at 0? Line chart scale labeled? Reference lines for context (target, limit, average)? Same scale for small multiples? (e) labels: title present and informative? Key points labeled? Tooltips on all data points? Annotations for anomalies? (f) micro-vis: every KPI card has sparkline + delta? Table cells with trend data have sparklines? (g) accessibility: grayscale test (screenshot + desaturate). Every series distinguishable? Redundant encoding for color? ARIA labels generated? (h) fintech-specific: score gauge shows zones? Concentration shows limit? Vintage uses shared scales? Waterfall connects? If audit finds zero improvements: either visualization is flawless (unlikely in evolving product) or audit is superficial."
		dependsOn: ["dv-marks-and-channels", "dv-chart-type-selection", "dv-sparklines-and-micro-vis", "dv-visual-integrity", "dv-labels-tooltips-annotations", "dv-fintech-specific-visualizations", "dv-chart-accessibility", "dv-small-multiples"]
		rationale: "Charts accumulate: each new feature adds charts, each redesign modifies charts. Without periodic review: lie factors creep in, pie charts appear, accessibility degrades, labels disappear. Quarterly audit is quality gate for visual integrity."
	},
]

reasoningProtocol: [
	{
		question:  "O gráfico usa channels perceptualmente eficazes para os dados? Posição e comprimento para quantitativo, cor para categórico?"
		reveals:   "Se encoding é ótimo — ou se dados quantitativos são encodados em cor (impreciso) quando poderiam ser em posição (preciso)."
		rationale: "Cleveland/McGill 1984: position > length > angle > area > color para dados quantitativos. Usar channel impreciso quando preciso está disponível é waste de accuracy."
	},
	{
		question:  "O tipo de gráfico responde a pergunta diretamente? Trend = line? Comparison = bar? Distribution = histogram? Correlation = scatter?"
		reveals:   "Se chart type é question-driven — ou se bar chart é usado para tudo, ou chart type é escolhido por estética."
		rationale: "Schwabish 2021: chart follows question. Few 2012: match chart to relationship. Chart bonito que não responde a pergunta é chartjunk."
	},
	{
		question:  "Sparklines estão presentes em todos KPI cards e table cells onde trend context é relevante? Deltas em todos KPI cards?"
		reveals:   "Se micro-vis maximiza informação por pixel — ou se números aparecem isolados sem context temporal."
		rationale: "Tufte 2006: sparklines. Glanceable data 2024+. '1.8%' é dado. '1.8% ↓ + sparkline descendo' é informação."
	},
	{
		question:  "Y-axis começa em 0 para bar charts? Reference lines contextualizam (target, limit)? Scales são compartilhadas em small multiples?"
		reveals:   "Se integridade visual é preservada — ou se charts distorcem percepção e causam decisões baseadas em misperception."
		rationale: "Tufte 1983: lie factor. Responsible visualization 2024+. Em fintech: distorted chart → wrong financial decision."
	},
	{
		question:  "Score gauge, concentration chart e vintage analysis existem com zones, limits e shared scales?"
		reveals:   "Se fintech-specific visualizations comunicam domain context — ou se dados financeiros são apresentados em charts genéricos sem contexto regulatório."
		rationale: "Score sem zone context é número sem significado. Concentração sem limit é bar chart sem referência. Safra sem shared scale é comparação impossível."
	},
	{
		question:  "Charts passam no grayscale test? Toda cor tem encoding redundante (shape, pattern, label)? ARIA labels existem?"
		reveals:   "Se charts são acessíveis para 100% dos usuários — ou se 8% dos usuários homens não conseguem distinguir series e screen readers não reportam nada."
		rationale: "CVD 8% males. WCAG 2.1. Redundant encoding 2023+. Accessibility é requisito, não feature."
	},
	{
		question:  "Small multiples usam shared axes e meaningful order? Ou spaghetti charts tentam mostrar 10+ series no mesmo gráfico?"
		reveals:   "Se comparação de cohorts é eficaz — ou se visual chaos impede pattern detection."
		rationale: "Tufte 1983: small multiples. Na Mesh, 12 safras in small multiples: pattern em 3 segundos. 12 safras overlaid: indecipherable."
	},
]

meshExamples: [
	{
		id:       "ex-concentration-chart-redesign"
		scenario: "Designer propõe pie chart com 15 fatias para mostrar concentração de carteira FIDC por sacado. Gestor FIDC precisa: identificar sacados com concentração acima de 30% (limite regulatório) e comparar tamanhos de exposição."
		analysis: "Pie chart com 15 fatias: (1) angle is perceptually imprecise (Cleveland/McGill: 2x mais erros que length). Fatias de 8% vs 10%: visualmente idênticas em pie. (2) 15 fatias: impossível comparar não-adjacentes. (3) regulatory limit (30%) não é representável em pie — não existe 'reference angle.' (4) fatias pequenas (1-3%): invisíveis. (5) legend required (15 items) → eye ping-pong between legend and chart. Pie chart é a pior opção disponível para esta pergunta."
		recommendation: "(1) Horizontal bar chart: sacados no y-axis (categórico), % da carteira no x-axis (quantitativo, encodado em length — segundo canal mais preciso). Top 10 sacados sorted descending. 'Outros' como barra agrupada no final. (2) Vertical reference line at 30% = limite regulatório. Label: 'limite regulatório: 30%.' Barras que excedem: warning color (semântica de CL lens). (3) Labels: cada barra com valor exato ('12,3%'). Nomes dos sacados no y-axis. (4) Tooltip: hover → 'Sacado ABC Ltda: R$276k (12,3% da carteira). Variação: +1,2pp vs mês anterior.' (5) Summary above: 'Concentração máxima: 12,3% (Sacado ABC). HHI: 450. Limite regulatório: 30%. ✓ Dentro do limite.' (6) Gestor vê em 3 segundos: nenhuma barra excede limite. Todas concentrações comparáveis (length). Exact values readable. (7) Time investment: bar chart component already in DS → configuration only. (8) Comparison: pie chart requires: designer time to arrange 15 slices, legend space, user effort to decode angles. Bar chart requires: sort data, render bars, add reference line. Bar chart é mais rápido de implementar E mais eficaz de ler."
		principlesApplied: ["ax-01", "ax-02", "ax-06"]
		assumptions: [
			"top 10 sacados é suficiente para concentração view — portfolios grandes podem precisar top 20 com scroll",
			"horizontal bar é familiar para gestor FIDC — extremely likely for financial professional",
			"'Outros' como barra agrupada não esconde risk — se sacado 11-15 individualmente small mas coletivamente significant: add threshold",
			"HHI (Herfindahl-Hirschman Index) é compreensível para FIDC — standard concentration metric in finance",
		]
		rationale: "Cleveland/McGill 1984: length (bar) perceptually 2x more accurate than angle (pie). Reference line for regulatory context. Labels for precision. Na Mesh, horizontal bar chart para concentração é the correct answer — pie chart is never the answer for concentration visualization with regulatory limits."
	},
	{
		id:       "ex-truncated-axis-correction"
		scenario: "Inadimplência dashboard FIDC mostra bar chart com y-axis começando em 1.5% em vez de 0%. Change de 1.5% para 1.8% preenche 100% da altura do chart. Gestor vê gráfico e agenda reunião de emergência. Na reunião, descobre que mudança foi 0.3 percentage points — within normal variation."
		analysis: "Lie factor: visual effect / data effect. Chart height represents range 1.5%-1.8% (0.3pp). On scale of 0-100%: 0.3% change. Visual fills 100% of chart. Lie factor ≈ 333x. Gestor percebeu: 'inadimplência triplicou' (visual). Realidade: 'inadimplência subiu 0.3pp, still well below target.' Reunião de emergência: custo de tempo de 5 pessoas × 1 hora = 5 horas. Causa: truncated y-axis."
		recommendation: "(1) Bar chart: y-axis MUST start at 0. Change from 1.5% to 1.8% on 0-3% scale: barra cresce ~10%. Proportional. Honest. Gestor vê: 'small change, within range.' No emergency meeting. (2) If signal is genuinely important (0.3pp matters for portfolio risk): switch to line chart. Line chart encodes slope (change), not area (absolute). Y-axis can start at 1.0% with label: 'eixo inicia em 1.0%.' Slope from 1.5% to 1.8% visible without exaggeration. (3) Add context: reference line at target (2.5%). Annotation: 'target: 2.5%. Current: 1.8%. Buffer: 0.7pp.' Gestor processes: 'subiu 0.3pp but still 0.7pp below target.' Informed, not alarmed. (4) Add comparison in tooltip: 'Fev 2026: 1.8%. Jan 2026: 1.5%. Target: 2.5%. 12-month average: 1.6%. Status: within normal range.' (5) Design system enforcement: BarChart component has prop yAxisMinimum with default 0 and validation: cannot be >0. Override requires boolean forceNonZeroAxis = true (for exceptional cases) logged with justification. (6) Cost/benefit: fix takes 30 minutes (change chart type or fix axis). Benefit: prevents future false alarms. ROI: 1 avoided false alarm = 5 person-hours saved. Payback: immediate."
		principlesApplied: ["ax-01", "ax-06", "dp-01"]
		assumptions: [
			"bar chart y-axis at 0 makes small changes invisible — this is correct behavior (small changes should look small)",
			"line chart is acceptable alternative — yes, line encodes slope not area",
			"gestor will trust corrected chart — may need explanation of why previous chart was misleading",
			"0.3pp change is genuinely within normal range — verify with historical data",
		]
		rationale: "Tufte 1983: lie factor. Responsible visualization 2024+. Na Mesh fintech, truncated axis caused: false alarm → emergency meeting → 5 person-hours wasted → trust erosion in data team. Correct axis: honest representation → informed decision → no wasted time → maintained trust."
	},
	{
		id:       "ex-vintage-analysis-visualization"
		scenario: "FIDC needs to analyze safra performance to understand if newer safras perform better than older ones and whether the scoring model is improving. Current format: table with 12 safras × 12 months = 144 numbers."
		analysis: "144 numbers in table: impossible to spot patterns by scanning. Human working memory: 7±2 items. 144 numbers: cognitive impossibility. Questions the table should answer: (1) are newer safras performing better? (2) at what month does inadimplência stabilize? (3) are there anomalous safras? Table can answer with effort (30+ minutes of comparison). Visualization can answer in seconds."
		recommendation: "Two complementary views with toggle: **View 1 — Small Multiples (default, for precision):** 12 mini line charts, arranged in 3×4 grid. Each: x = months since origination (0-12), y = cumulative inadimplência (%). SAME x-range (0-12) and SAME y-range (0-5%) across ALL multiples. Order: chronological, newest at bottom-right. Gestor scans top-left to bottom-right: if curves get lower → improvement over time. Label: each mini-chart titled with safra (e.g., 'Jan/25'). Last point labeled with current value. **View 2 — Heatmap (toggle, for pattern detection):** Matrix: rows = safras (newest at bottom), columns = months since origination. Color: sequential palette (white = 0%, dark red = 5%+). Patterns visible: diagonal bands = aging effect. Lighter bottom rows = newer safras performing better. Dark spots = anomalous safra-months. **For both views:** (1) Tooltip on any data point: exact value, safra, month, comparison to portfolio average. (2) Annotation: anomalous safras marked with explanation if known. (3) Summary above: 'Safras 2025 outperform 2024 by avg 0.8pp at month 6. Model v2.3 (Sep 2025) showed significant improvement.' (4) Click safra label → drill-down to safra detail (operation list, score distribution, geography). **Implementation:** VintageChart component with mode toggle. Shared data source. Small multiples with linked brushing (hover month 6 on one → highlight month 6 on all)."
		principlesApplied: ["ax-01", "ax-02", "ax-06"]
		assumptions: [
			"12 safras is manageable in 3×4 grid — 24+ safras may need filtering (show last 12 only)",
			"0-5% y-range is appropriate — adjust based on actual data range",
			"FIDC gestor reads heatmaps fluently — high chart literacy assumed for financial professional",
			"linked brushing is implementable in chart library — most modern libraries support (D3, Recharts with customization)",
		]
		rationale: "Tufte 1983: small multiples. Faceted visualization 2022+. Na Mesh, 144-cell table: 30 minutes to spot pattern. Small multiples: 3 seconds. Heatmap: 2 seconds. Visualization transforms data from cognitive burden into perceptual insight."
	},
	{
		id:       "ex-score-gauge-vs-plain-number"
		scenario: "Operation detail page shows 'Score: 65'. Construtora gestor asks: 'is 65 good? Can I approve this?'"
		analysis: "'65' as plain number: zero context. Gestor needs to know: what range is possible (0-100), what zones exist (approval threshold, risk levels), where 65 falls in the distribution. Without this context: gestor either memorizes thresholds (fragile) or asks every time (inefficient). Score without context shifts cognitive burden to the user — the system has the information but doesn't display it."
		recommendation: "(1) Replace plain number with ScoreGauge (bullet chart): horizontal bar showing 65 as marker against zones: 0-40 'Alto Risco' (red), 40-60 'Atenção' (yellow), 60-80 'Bom' (green), 80-100 'Excelente' (dark green). Gestor sees: 65 is in 'Bom' zone, 5 points above 'Atenção.' Approval decision: immediately informed. (2) Below gauge: FeatureImportance bar chart (compact): 'Histórico Pagamento: 40% ↑', 'Receita: 25% →', 'Tempo de Relacionamento: 20% ↑', 'Setor: 15% →.' Gestor sees why: payment history and relationship are strong. (3) Context line: 'Score mínimo para aprovação automática: 60. Esta operação: 65. ✓ Acima do mínimo.' (4) Tooltip on gauge: 'Score calculado por modelo v2.3 em 12/mar/2026. Próxima recalibração: abr/2026. Confiança: 87%.' (5) Comparison: 'Distribuição de scores no portfólio: [mini histogram showing 65 is slightly above median].' (6) Result: from '65' (needs interpretation) to '65 is good, above threshold, driven by payment history' (self-explanatory). Approval time: from 30 seconds (lookup threshold, compare) to 3 seconds (visual assessment). ×20 operations/day = 9 minutes saved daily."
		principlesApplied: ["ax-01", "ax-02", "ax-04"]
		assumptions: [
			"bullet chart is familiar to construtora gestor — may need brief onboarding tooltip on first view",
			"zone boundaries (40, 60, 80) are configurable per construtora — yes, via settings (IP lens: settings IA)",
			"feature importance adds value without overloading — keep to top 4 features, compact bar chart",
			"mini histogram of portfolio distribution is understandable — for construtora: maybe. For FIDC: definitely. For construtora: make optional/collapsible",
		]
		rationale: "Score gauge transforms number into comprehensible assessment. '65' requires external knowledge to interpret. '65 in Bom zone, above 60 threshold' is self-explanatory. In B2B fintech where decisions have financial consequences, self-explanatory visualization > plain number that requires memorized thresholds. TC trust-in-ai-decisions: visual explanation builds trust in scoring model."
	},
]

principleIds: ["ax-01", "ax-02", "ax-04", "ax-06", "dp-01"]

relatedLenses: [
	{
		lensId:   "lens-information-density-design"
		relation: "complementsWith"
		context:  "ID define composição de dashboard, layout de KPI cards, e density por persona. DV define como dados são encodados visualmente dentro dessa composição: sparklines em KPI cards (DV) dentro de card anatomy definida por ID. Charts em seção de dashboard (DV) posicionados conforme composition pattern (ID). ID é o layout; DV é o encoding visual dentro do layout."
	},
	{
		lensId:   "lens-color-as-functional-language"
		relation: "complementsWith"
		context:  "CL define sistema de cores semânticas e palettes de dados (sequential, diverging, categorical). DV consome palettes: heatmap usa sequential de CL, scatter quadrants usam semantic colors de CL, multi-series usa categorical de CL. CL garante accessibility das cores; DV garante que charts as usam corretamente + adicionam redundant encoding (shape, pattern, label). CL é o palette; DV é a application."
	},
	{
		lensId:   "lens-typographic-systems-for-dense-interfaces"
		relation: "complementsWith"
		context:  "TS define escala tipográfica e tabular figures. DV usa para labels de charts: axis labels em TS size-xs, data labels em TS size-sm, chart title em TS size-md. Tabular figures (TS) para números em labels e tooltips — alignment correto. TS é o sistema tipográfico; DV aplica em chart text."
	},
	{
		lensId:   "lens-trust-and-credibility-design"
		relation: "complementsWith"
		context:  "TC define trust in AI decisions e transparency calibration. DV provê visual explanation: score gauge mostra zones (o que score significa), feature importance mostra porquê (quais features contribuíram), safra analysis mostra track record (model performance ao longo do tempo). TC diz 'explain AI decisions'; DV diz 'visualize the explanation'. Chart honesto (visual integrity) é manifestação de transparency."
	},
	{
		lensId:   "lens-design-tokens-and-systematic-composition"
		relation: "complementsWith"
		context:  "DT define tokens para styling de charts (cores de palette, font-sizes para labels, spacing para margins). DV chart components consomem tokens: chart background = --color-surface-primary, axis text = --font-size-xs, grid line = --color-border-subtle. Consistency visual cross-charts via tokens. DT é a infraestrutura; DV é a application."
	},
	{
		lensId:   "lens-multi-sided-platform-ux"
		relation: "complementsWith"
		context:  "MUX define experiência por lado da plataforma. DV calibra chart vocabulary por persona: FIDC (scatter, heatmap, small multiples, histogram), construtora (bar, line, sparkline), fornecedor (numbers, badges, simple line). Chart literacy calibration é per-side-experience aplicado a visualizações."
	},
	{
		lensId:   "lens-data-modeling-for-analytical-power"
		relation: "complementsWith"
		context:  "DM define semantic layer como SSOT para métricas. DV charts consomem métricas da semantic layer: 'inadimplência 1.8%' no chart é a mesma definição da semantic layer (>90 dias). Consistência: chart metric = table metric = report metric = semantic layer metric. DM é source; DV é presentation."
	},
	{
		lensId:   "lens-progressive-disclosure-and-information-architecture"
		relation: "complementsWith"
		context:  "PD define layers de disclosure: overview → context → detail. DV provê visualizações em cada layer: sparkline em overview (KPI card), full chart em context (dashboard section), interactive drill-down chart em detail (operation page). PD é a structure de layers; DV é o visual content em cada layer."
	},
]

limitations: [
	{
		description: "Chart type recommendations assume standard data shapes. Unusual data (extreme outliers, very sparse, highly skewed, heavy-tailed) may require non-standard visualization approaches."
		alternative: "Start with recommended chart type. Validate with actual data. If recommended chart doesn't communicate the pattern clearly (outliers dominate scale, sparse data looks empty, skew hides majority): iterate. Options: log scale for heavy-tailed data, jitter for overplotted scatter, bin width adjustment for sparse histograms. Log exception with reasoning for future reference."
		rationale: "Guidelines are defaults for typical data. Real data is often atypical. Iterate when default doesn't serve."
	},
	{
		description: "Micro-visualizations (sparklines, bullet charts) at very small sizes (60×16px) may be illegible on low-resolution displays or when rendered at sub-pixel precision."
		alternative: "Minimum size constraints in design system: sparkline ≥60×16px, bullet chart ≥100×16px. Test on target devices: construtora's actual monitors (likely 1080p), fornecedor's actual phones (varied quality). If illegible at minimum size: fall back to delta indicator (text-only: '↑8.3%') which has no minimum pixel requirement."
		rationale: "Design for actual devices, not ideal conditions. Graceful degradation: sparkline → delta indicator → plain number."
	},
	{
		description: "Fintech-specific visualizations (vintage analysis, concentration, score gauge) assume domain expertise. New analyst, new construtora user, or auditor may not interpret correctly without guidance."
		alternative: "Inline help per chart: 'ℹ️' icon that reveals: 'Este gráfico mostra [explanation]. Como ler: [guidance]. Cada [element] representa [meaning].' First-time user: onboarding walkthrough highlighting fintech-specific charts with interactive explanation. Help text written by domain expert, not just designer."
		rationale: "Even expert audience has new members. Fintech-specific vis is powerful but requires domain knowledge. Inline help bridges the gap."
	},
	{
		description: "Accessibility for complex visualizations (heatmap, scatter with hundreds of points) is inherently limited — screen readers cannot convey spatial patterns, and redundant encoding for 100+ data points is impractical."
		alternative: "For complex charts: provide accessible alternative — hidden data table (sortable, filterable) that conveys same information in tabular form. ARIA: aria-describedby links to table. Summary text: 'heatmap shows inadimplência by sacado and month. 3 sacados have elevated rates in Q4. See table below for details.' Not every visual nuance translates to text — but key insights must."
		rationale: "100% visual accessibility for complex charts is impossible. Key insight accessibility + alternative data format is achievable and sufficient."
	},
	{
		description: "Chart library standardization (10 chart components in DS) may not cover edge cases — some analyses may need custom visualization (network graph for supply chain, geographic map for regional concentration)."
		alternative: "Standard library covers 90% of needs. For edge cases: evaluate — is custom vis justified by frequency and value? If used >3 times: add to DS. If one-time analysis: custom is acceptable with documentation. Never custom for standard patterns (bar, line, scatter) — always use DS component."
		rationale: "Standard covers standard. Custom for custom. Don't reinvent bar chart. Don't force network graph into standard chart."
	},
]

rationale: "Visualização de dados traduz números em formas visuais que o cérebro processa ordens de magnitude mais rápido que texto. Na Mesh fintech com métricas financeiras, operacionais e de rede, esta lens operacionaliza: marks e channels com eficácia perceptual e preattentive processing (Bertin 1967, Munzner 2014, Cleveland/McGill 1984, channel budget 2023+, Healey 1996), seleção de chart type por pergunta e chart literacy da persona (Schwabish 2021, Few 2012, question-driven 2023+, chart literacy calibration 2024+), sparklines e micro-visualizações para glanceable data em KPI cards e tables (Tufte 2006, Few 2006, micro-visualizations 2023+, glanceable data 2024+), integridade visual contra distorções com lie factor e responsible visualization (Tufte 1983, Few 2012, responsible visualization 2024+), labels/tooltips/annotations como progressive labeling para storytelling visual (Schwabish 2021, progressive labeling 2023+), visualizações fintech-specific como componentes do design system (score gauge, concentration chart, vintage analysis, waterfall, risk scatter, feature importance), acessibilidade com CVD-safe palettes e redundant encoding (WCAG 2.1, redundant encoding 2023+), e small multiples para comparação de cohorts (Tufte 1983, faceted visualization 2022+). Universal na semiótica visual; específica na aplicação a fintech B2B multisided com personas de chart literacy variada."

}
