package lenses

import "github.com/sw6n297mn8-maker/mesh-spec/architecture/artifact-schemas:artifact_schemas"

domainLanguageAndTerminologyDesign: artifact_schemas.#AnalyticalLens & {
id:     "lens-domain-language-and-terminology-design"
name:   "Design de Linguagem de Domínio e Terminologia"

purpose: "Orientar decisões sobre como nomear, definir, governar e evoluir o vocabulário do domínio da Mesh como ativo estratégico."
status: "draft"

trigger: {
	conditions: [
		"a decisão envolve como nomear estados, eventos, scores, categorias, papéis ou conceitos do domínio na plataforma",
		"a decisão envolve escolher entre termos alternativos que carregam conotações diferentes (recebível elegível vs crédito disponível, qualificado vs verificado)",
		"a decisão envolve como vocabulário da plataforma afeta percepção jurídica, regulatória ou de mercado",
		"a decisão envolve como garantir consistência terminológica entre API, eventos, UI, documentação, contratos e comunicação",
		"a decisão envolve como o vocabulário da Mesh pode se tornar vocabulário do mercado se a plataforma vencer",
		"a decisão envolve como agentes IA devem usar terminologia consistente ao gerar código, documentação e interfaces",
		"a decisão envolve como termos do domínio são definidos, governados e evoluídos ao longo do tempo",
	]
	keywords: [
		"terminologia", "terminology", "vocabulário", "vocabulary",
		"nome", "name", "naming", "nomenclatura",
		"glossário", "glossary", "definição", "definition",
		"ubiquitous language", "linguagem ubíqua", "DDD",
		"recebível", "receivable", "crédito", "credit",
		"qualificado", "verificado", "elegível", "aprovado",
		"fornecedor", "supplier", "cedente", "sacado",
		"score", "rating", "classificação", "nota",
		"conotação", "connotation", "percepção",
		"propriedade intelectual", "brand language",
	]
	excludeWhen: [
		"a decisão é sobre percepção de trust e credibilidade visual — usar trust-and-credibility-design",
		"a decisão é sobre documentação como produto (estrutura, freshness) — usar documentation-as-product",
		"a decisão é sobre comunicação com stakeholders (framing, audiência) — usar stakeholder-communication",
		"a decisão é sobre naming de código (camelCase, snake_case) — usar CLAUDE.md conventions",
		"a decisão é sobre design de API (endpoint naming) — usar api-design-as-product",
	]
	rationale: "Bloomberg criou vocabulário que se tornou o vocabulário do mercado financeiro. Cada termo da Mesh em API, evento, interface, contrato e documentação se torna vocabulário da cadeia se a plataforma vencer. 'Recebível elegível' vs 'crédito disponível' muda percepção. 'Qualificado' vs 'verificado' muda expectativa jurídica. Agentes IA que geram código e documentação propagam terminologia — se CLAUDE.md não define: agente escolhe aleatoriamente, inconsistência prolifera. TC cobre percepção de trust; DP cobre estrutura de docs; SC cobre framing de comunicação; API cobre endpoint naming. Esta lens cobre o design deliberado do vocabulário do domínio como ativo estratégico — escolha, definição, consistência e governança de cada termo."
}

concepts: [
	{
		id:         "dl-ubiquitous-language"
		name:       "Linguagem Ubíqua: Um Vocabulário que Todos Compartilham"
		nature:     "theoretical"
		role:       "framework"
		definition: "Evans (2003, Domain-Driven Design): ubiquitous language é o vocabulário compartilhado entre domain experts, desenvolvedores, e sistema. Mesma palavra significa mesma coisa em: conversação, código, documentação, API, UI, contrato. Se domain expert diz 'operação de antecipação' e código diz 'anticipation_transaction' e API diz 'advance_request' e UI diz 'solicitação de crédito': 4 termos para 1 conceito = confusion em toda comunicação. Ubiquitous language: 'antecipação' everywhere — conversação, Anticipation no código, /anticipations na API, 'Antecipação' na UI, 'operação de antecipação' no contrato. Conceito de 'language as bounded context boundary' (Evans 2003): dentro de um bounded context, termos têm significado preciso. 'Operação' no ECL (Economic Commitment Lifecycle) significa antecipação de recebível. 'Operação' no NGR (Network Growth & Reach) significa ação de expansão da rede. Mesmo termo, significados diferentes em contextos diferentes — aceitável SE os contextos são explícitos. O que NÃO é aceitável: mesmo termo com significados diferentes NO MESMO CONTEXTO. Conceito contemporâneo de 'vocabulary as competitive moat' (2024+): quando plataforma define vocabulário de um mercado, ela define como participantes pensam sobre o domínio. Bloomberg definiu 'CUSIP', 'ISIN', 'yield spread' — o mercado usa porque Bloomberg normalizou. Salesforce criou 'CRM' como categoria. Se Mesh define 'Score de Cadeia', 'Recebível Elegível', 'Qualificação de Fornecedor' como termos padrão na construção civil: concorrentes precisam adotar o vocabulário da Mesh ou criar alternativo (barrier). Vocabulário é propriedade intelectual semântica — não patenteável, mas quando mercado internaliza, associação com marca é permanente."
		meshManifestation: "Na Mesh, linguagem ubíqua por bounded context: **ECL (Economic Commitment Lifecycle):** operação de antecipação (não 'transação', não 'deal', não 'operação financeira'). Recebível (não 'crédito', não 'título' — recebível é o direito de receber pagamento por NF emitida). Cedente (papel do fornecedor na operação — juridicamente preciso per art. 286 CC). Sacado (papel da construtora — devedor do recebível). Cessionário (papel do FIDC — adquirente do direito creditório). Deságio (não 'taxa', não 'fee', não 'spread' — deságio é o termo específico de cessão de crédito que descreve a diferença entre valor de face e valor pago). **NGR (Network Growth & Reach):** fornecedor (na relação com a plataforma — não 'cedente', que é papel ECL). Construtora (não 'sacado'). Qualificação (processo ativo de habilitar fornecedor — não 'verificação' que implica só checagem, não 'aprovação' que implica decisão de mérito). **Scoring:** Score de Operação (não 'rating' que implica AAA/BBB, não 'nota' que é ambíguo com nota fiscal, não 'classificação' que é genérico). Zona de Score (Bom, Atenção, Alto Risco — categorias semânticas, não numéricas, para comunicação com non-experts). **Compliance:** Compliance de Fornecedor (não 'status regulatório', não 'situação documental'). Documento Elegível (documento que atende requisitos para operação — não 'documento válido' que implica certificação jurídica que a Mesh não faz)."
		meshImplication: "Ubiquitous language implementation: (1) **glossário canônico no mesh-spec** — /foundations/glossary.md: cada termo com: nome, definição precisa (1-3 sentenças), bounded context onde se aplica, termos que NÃO usar (sinônimos rejeitados com justificativa), justificativa da escolha, data de aprovação, reviewer. Exemplo: 'Antecipação: operação pela qual fornecedor (cedente) transfere direitos sobre recebível a FIDC (cessionário) mediante deságio, nos termos da cessão de crédito (art. 286+ Código Civil). Não usar: crédito (impreciso — crédito implica relação de empréstimo), empréstimo (juridicamente diferente — tributação e regulação distintas), adiantamento (coloquial, ambíguo — pode implicar relação trabalhista). BC: ECL. Approved: 2026-01-15. Reviewed by: founder + legal.' (2) **glossário como SSOT** — dp-single-source-of-truth: cada termo definido em 1 lugar. API, eventos, UI, documentação, contratos: referenciam glossário. Se código usa 'transaction' e glossário diz 'anticipation': código está errado. Agente que gera código: MUST check glossary before naming. (3) **cross-layer consistency** — mesmo conceito usa mesmo termo em TODAS as layers: glossário (antecipação), código (Anticipation class), API (/v1/anticipations endpoint), evento (AnticipationRequested), UI ('Antecipação' como label), contrato ('operação de antecipação de recebível'), email ('sua antecipação foi aprovada'), notificação push ('Antecipação #1234 aprovada'). Zero variação. (4) **per-BC terminology** — fornecedor é 'fornecedor' no NGR (relação com plataforma) e 'cedente' no ECL (papel jurídico na operação). Ambos no glossário com contexts explícitos. Consumidor sabe: 'em qual context estou? NGR = fornecedor. ECL = cedente.' (5) **CLAUDE.md:** 'terminologia: use termos do glossário (mesh-spec/foundations/glossary.md). Antes de nomear class, variable, endpoint, event, UI label: consulte glossário. Se termo não existe: proponha adição com definição, justificativa, e alternativas rejeitadas. Se dúvida entre alternativas: consulte 7 critérios de seleção (dl-term-selection-criteria).' (6) **CI validation (advanced, post-MVP):** lint rule que verifica: class names, API endpoints, event names, UI labels — match glossário terms. 'TransactionRequest' class → warning 'glossário maps this concept to Anticipation. Consider: AnticipationRequest.' Enforced: gradual (warning first, error later). Anti-pattern: 5 termos para 1 conceito — API: supplier, código: vendor, UI: fornecedor, contrato: cedente, evento: provider. Novo developer: 'são a mesma coisa?' Consulta 5 fontes, recebe 5 respostas diferentes. Bugs seguem: lógica para 'vendor' não conecta a query de 'supplier' porque naming sugere entidades diferentes."
		rationale: "Evans 2003: ubiquitous language. Language as BC boundary. Vocabulary as competitive moat 2024+. Na Mesh, glossário canônico + cross-layer consistency + CLAUDE.md instruction: 1 termo per conceito per context, everywhere. Bloomberg definiu vocabulário do mercado. Mesh pode definir vocabulário da construção civil brasileira."
	},
	{
		id:         "dl-term-selection-criteria"
		name:       "Critérios de Seleção de Termos: Por Que Este Termo e Não Aquele"
		nature:     "theoretical"
		role:       "method"
		definition: "Cada escolha terminológica deve ser deliberada, não casual. Conceito de 'term selection framework' (2024+): 7 critérios para avaliar candidatos: **(1) precisão jurídica** — termo alinha com conceito jurídico? 'Cessão de crédito' é preciso; 'transferência' é genérico. Imprecisão jurídica em contrato: risco em litígio. **(2) precisão de domínio** — termo captura o conceito exato? 'Antecipação de recebível' é preciso; 'empréstimo' é errado (implicações tributárias e regulatórias radicalmente diferentes — IOF, enquadramento Bacen, natureza jurídica). **(3) familiaridade do participante** — participante entende sem explicação? 'Deságio' é preciso mas fornecedor PME com ensino médio pode não entender. Solução: UI usa 'taxa de antecipação' com tooltip 'deságio — diferença entre valor de face do recebível e valor recebido antecipadamente.' Contrato: usa 'deságio' (jurídico). Dual-layer: acessível + preciso. **(4) diferenciação competitiva** — termo é único e associável à Mesh? 'Score de Cadeia' (Mesh-specific, novel, memorável) vs 'credit score' (generic, todo banco usa). Termo próprio: defensável como propriedade intelectual semântica. **(5) internacionalização** — traduz bem para es-LATAM? 'Antecipação' → 'anticipación' funciona. 'Deságio' → 'descuento' funciona mas perde especificidade (descuento é genérico em espanhol). Verificar antes de cristalizar. **(6) consistency interna** — coerente com outros termos da plataforma? Se usamos 'operação de antecipação', não usar 'transação de liquidação' — padrão deveria ser 'operação de [tipo]' para todas. **(7) brevidade** — praticável para class names, API endpoints, UI labels, conversation? 'Operação de Antecipação de Recebível de Construção Civil Mediante Cessão de Crédito' é juridicamente perfeito mas impraticável. 'Antecipação' é suficiente no contexto da plataforma."
		meshManifestation: "Na Mesh, term selection aplicado a decisões concretas: **'Antecipação' (escolhido) vs 'Empréstimo' (rejeitado):** (1) precisão jurídica: antecipação = cessão de crédito (art. 286 CC). Empréstimo = mútuo (art. 586 CC). Tributação: IOF diferente. Regulação: empréstimo requer licença bancária; cessão via FIDC opera sob CVM. (2) domínio: antecipação descreve exatamente — fornecedor recebe antecipadamente o que já é dele. (3) familiaridade: construtora e FIDC conhecem. PME precisa de explicação (aceitável com UI acessível). (4) diferenciação: 'empréstimo' é genérico (todo banco faz). 'Antecipação' posiciona como supply chain finance. (5) i18n: 'anticipación' funciona em espanhol. (6) consistency: 'operação de antecipação' — coerente com padrão 'operação de [tipo].' (7) brevidade: 'antecipação' = 12 caracteres. Prático. **'Qualificado' (escolhido) vs 'Verificado' (rejeitado) para fornecedor:** (1) jurídico: 'qualificado' implica que critérios foram definidos E atendidos. 'Verificado' implica apenas que foi checado (pode ter sido checado e reprovado — ambíguo). Se construtora alega 'vocês disseram verificado': verificar ≠ atender. Se 'qualificado': implica atendimento. Mais defensável. (2) diferenciação: 'qualificado' é mais forte — Mesh qualifica (processo ativo com padrão), não apenas verifica (checagem passiva). (3) Risco de 'verificado': construtora interpreta como seal of approval. Default → 'mas vocês verificaram!' Se 'qualificado' com critérios explícitos: 'qualificado conforme critérios X, Y, Z — não constitui garantia de performance.' Defensável. **'Score de Operação' (escolhido) vs 'Nota' (rejeitado) vs 'Rating' (rejeitado):** (1) 'nota' é ambígua em português: nota fiscal, nota de rodapé, nota escolar. (2) 'rating' implica escala de letras (AAA, BBB) — agências de rating. Mesh não é agência. (3) 'score' é numérico (0-100), familiar (credit score, FICO score), sem ambiguidade. 'Score de Operação' é Mesh-specific (score da operação, não da empresa)."
		meshImplication: "Term selection process: (1) **para cada novo conceito:** listar 3-5 candidatos. Avaliar CADA contra 7 critérios explicitamente. Documentar no glossário com rationale: 'Antecipação: chosen for juridical precision (cessão ≠ empréstimo) + domain accuracy (descreve o que acontece) + competitive differentiation (posiciona como supply chain finance). Rejected: empréstimo (legally different, regulatory risk), adiantamento (ambiguous, colloquial), crédito (imprecise, implies loan relationship).' (2) **stakeholder validation:** antes de finalizar termo que aparece em UI ou contrato: validar com domain experts. Construtora gestor: entende 'antecipação' ou confunde com adiantamento? Advogado: 'qualificado' é defensável juridicamente? Fornecedor PME: precisa de tooltip para 'deságio'? Feedback informa: manter termo + adicionar explicação, ou escolher alternativo. (3) **context-appropriate variants:** mesmo conceito pode ter termos diferentes per context. Fornecedor (relação com plataforma, NGR) vs cedente (papel jurídico na operação, ECL). Ambos no glossário com contexts. Consumer code: usa o correto para seu BC. (4) **UI accessibility layer:** quando termo preciso é unfamiliar para audience: UI mostra variante acessível + tooltip com preciso. 'Taxa de antecipação ⓘ' → tooltip: 'deságio: diferença entre valor de face do recebível (R$50.000) e valor que você recebe antecipadamente (R$48.750). O deságio nesta operação é R$1.250 (2,5%).' Preciso + acessível + concreto. (5) **term evolution:** termos podem mudar se domínio evolui ou se evidência mostra que escolha foi subótima. Processo: ADR terminológico (mesmo formato que ADR técnico). Old term: deprecated no glossário com redirect ('verificado → ver qualificado'). Referências: atualizadas. Se termo é externo (em API, contrato): PE lens deprecation ceremony (advance notice, transition, migration). (6) **CLAUDE.md:** 'antes de nomear qualquer conceito do domínio: consulte glossário. Se conceito não existe: proponha com avaliação dos 7 critérios. Nunca invente nome ad hoc para conceito de domínio — ad hoc cria inconsistência que prolifera.' Anti-pattern: developer nomeia class 'CreditFacility' porque é o que bancos chamam. Mas: conceito da Mesh é fundamentalmente diferente de credit facility bancária (não é revolving credit, é cessão de recebível específico). Wrong term importa wrong mental model — every person who reads 'CreditFacility' assumes bank-like behavior que não se aplica (revolving, limit, interest rate). Correct term 'Anticipation': imports correct model (one-time, per-receivable, discount-based)."
		dependsOn: ["dl-ubiquitous-language"]
		rationale: "Term selection framework 2024+. Na Mesh, every term choice has juridical (contrato terms), perceptual (how users think), and competitive (Mesh vocabulary vs generic) consequences. 7 critérios: seleção deliberada. 'Garantido' vs 'confirmado' pode ser litígio vs não."
	},
	{
		id:         "dl-cross-layer-consistency"
		name:       "Consistência Cross-Layer: Mesmo Conceito, Mesmo Termo em Code, API, UI, Docs, Contratos"
		nature:     "operational"
		role:       "property"
		reviewCadence: "quarterly"
		definition: "Ubiquitous language requer: mesmo termo em todas as camadas do sistema. Conceito de 'terminology mapping table' (2024+): para cada domain concept: how it appears in each layer. Tabela: Concept | Code | Database | API | Event | UI (pt-BR) | UI (es, future) | Contract. Mapping table ensures: developer criando endpoint sabe usar 'anticipation' not 'advance' or 'credit.' Designer criando UI sabe usar 'Antecipação' not 'Adiantamento.' Agent gerando evento sabe usar AnticipationRequested not TransactionCreated. Conceito de 'code-language alignment' (DDD 2023+): class names, method names, variable names refletem ubiquitous language. OperationAnticipation (not CreditTransaction). Supplier.qualify() (not Supplier.approve() — approve implica decisão diferente de qualificar). Score.calculateForOperation() (not Score.compute() — compute é genérico, calculateForOperation captura que score é per-operation). Code IS documentation do domínio — se código usa termos errados, developers aprendem conceitos errados e propagam para novos features."
		meshManifestation: "Na Mesh, terminology mapping (key concepts): **Operação de Antecipação:** code: Anticipation. DB: anticipations table. API: /v1/anticipations, /v1/anticipations/{id}. Event: AnticipationRequested, AnticipationApproved, AnticipationSettled, AnticipationCancelled. UI pt-BR: 'Antecipação.' UI es (future): 'Anticipación.' Contract: 'operação de antecipação de recebível.' **Fornecedor (relação):** code: Supplier. DB: suppliers table. API: /v1/suppliers. Event: SupplierQualified, SupplierSuspended, SupplierOnboarded. UI: 'Fornecedor.' Contract: 'fornecedor.' **Cedente (papel jurídico):** code: Assignor (English legal equivalent). DB: anticipations.assignor_id (FK to suppliers). API: response field 'assignor' within anticipation. Event: within Anticipation events (assignor_id). UI: contexto jurídico (documentos de cessão, relatório FIDC). Contract: 'cedente.' **Score de Operação:** code: OperationScore. DB: operation_scores table. API: /v1/anticipations/{id}/score. Event: ScoreCalculated. UI: 'Score.' Contract: 'score de risco da operação.' **Qualificação:** code: Qualification. DB: qualifications table. API: /v1/suppliers/{id}/qualification. Event: QualificationCompleted, QualificationExpired. UI: 'Qualificação.' Contract: 'qualificação do fornecedor.' **Deságio / Taxa de Antecipação:** code: Discount (or Desagio for domain-specificity). DB: anticipations.discount_amount + anticipations.discount_rate. API: discount_amount, discount_rate fields. Event: within Anticipation events. UI fornecedor: 'Taxa de Antecipação' (acessível). UI FIDC: 'Deságio' (preciso). Contract: 'deságio.' **Recebível:** code: Receivable. DB: receivables table. API: /v1/receivables. Event: ReceivableSubmitted, ReceivableConfirmed. UI: 'Recebível' ou 'Nota Fiscal' (acessível para fornecedor). Contract: 'direito creditório' (juridicamente preciso) ou 'recebível' (coloquial aceito)."
		meshImplication: "Cross-layer enforcement: (1) **mapping table in mesh-spec** — /foundations/terminology-mapping.md. Tabela completa: Concept × Layer → Term. Atualizada quando novo conceito é adicionado. Agentes e developers: consultam antes de naming qualquer artefato do domínio. Formato: markdown table, parseable, referenciável. (2) **code review for naming** — PR que introduz novo class, table, endpoint, event: reviewer checa contra mapping table. 'TransactionRequest' class → comment: 'terminology mapping says Anticipation. Please rename to AnticipationRequest.' Not optional — naming is architectural. (3) **event naming convention** — padrão: {Entity}{PastTenseAction}. AnticipationRequested (not AnticipationRequest — event é fato passado). SupplierQualified (not SupplierApproved — qualificação ≠ aprovação). ScoreCalculated (not ScoreComputed). Convention: documented in mesh-spec /foundations/event-naming-convention.md. (4) **API-UI alignment** — API field name: 'score.' UI label: 'Score.' NOT: API 'risk_rating', UI 'Score' (developer building frontend: confused about whether risk_rating = Score). API fields use English terms from mapping table; UI labels use pt-BR terms from mapping table. Same concept, different language, same semantic position. (5) **context-aware terms** — UI para fornecedor PME: 'Taxa de Antecipação' (acessível — fornecedor entende 'taxa'). UI para FIDC gestor: 'Deságio' (preciso — FIDC vive neste vocabulário). Mapping table: inclui per-audience variant. Component: TermWithExplanation renders appropriate variant per audience. (6) **contract-code alignment** — termo jurídico no contrato: 'cedente.' Code: Assignor (English equivalent). Database: assignor_id. Advogado que lê código: reconhece conceitos. Developer que lê contrato: reconhece classes. Alignment bidirectional. (7) **language for i18n** — quando traduzir para espanhol: glossário inclui coluna es-LATAM. 'Antecipação' → 'Anticipación.' 'Fornecedor' → 'Proveedor.' Translation per-term, governada, não ad-hoc. Anti-pattern: API uses 'vendor', UI says 'fornecedor', event says 'supplier', contract says 'cedente', docs say 'provider.' 5 termos, 1 entidade. Novo developer pergunta: 'are these the same thing?' consulta 5 fontes, recebe 5 respostas. Bugs: logic para 'vendor' não conecta a entity 'supplier' porque naming sugere que são coisas diferentes."
		dependsOn: ["dl-ubiquitous-language", "dl-term-selection-criteria"]
		crossDependsOn: [{
			lensId:    "lens-documentation-as-product"
			conceptId: "dp-single-source-of-truth"
			context:   "DP defines SSOT — each information in exactly 1 place. DL terminology mapping is SSOT for domain terms: glossário is the single authoritative source. API naming references glossário. UI naming references glossário. When glossário changes: all layers update. DP provides the SSOT principle; DL provides the terminological SSOT implementation. If term is defined in 3 places (glossário, API docs, design guide): 3 definitions will drift. If defined in 1 (glossário) and referenced by others: 1 definition, zero drift."
		}]
		rationale: "Terminology mapping 2024+. Code-language alignment DDD 2023+. Na Mesh, mapping table garante: AnticipationRequested event, /v1/anticipations API, 'Antecipação' UI, 'operação de antecipação' contract — aligned terms, zero ambiguity across all layers."
	},
	{
		id:         "dl-juridical-implications"
		name:       "Implicações Jurídicas: Termos que Criam ou Limitam Obrigações Legais"
		nature:     "theoretical"
		role:       "heuristic"
		definition: "Em plataforma financeira, terminologia tem consequências jurídicas reais. Conceito de 'terminological liability' (2024+): o termo escolhido pode criar obrigação que a plataforma não pretende assumir. 'Garantia' implica que a plataforma garante algo — e é responsável civilmente se falhar. 'Score' implica opinião baseada em dados — disclaimer necessário para limitar responsabilidade. 'Qualificado' implica que padrão foi atendido — questionável se padrão é apenas documental sem verificação de mérito. 'Aprovado' implica decisão final — mas por quem? Plataforma? Construtora? FIDC? Ambiguidade de actor: liability ambígua. Conceito de 'legal term review' (2024+): todo novo termo que aparece em contrato, API pública, ou comunicação oficial com participantes: DEVE ser revisado por advogado antes de ser adotado e cristalizado. Não é optional 'nice-to-have' — é proteção contra liability inadvertida. Cenário: developer escolhe 'garantido' como status de operação. Termo aparece em dashboard. 6 meses depois: termo migra para contrato template sem review jurídica. Fornecedor não recebe pagamento: 'vocês garantiram!' Litígio: contrato da Mesh usa 'garantido.' Mesh: liability auto-infligida por escolha terminológica casual."
		meshManifestation: "Na Mesh, termos com implicação jurídica: **'Qualificado' (fornecedor):** implica que fornecedor atendeu critérios definidos de qualificação. Obrigação criada: Mesh DEVE definir e aplicar critérios consistentemente. Se status 'qualificado' mas critérios não foram efetivamente checados: liability (fornecedor pode alegar que Mesh garantiu qualidade). Mitigação: (a) documentar critérios explicitamente (docs compliance em dia + score acima de threshold + dados cadastrais validados). (b) disclaimer: 'Qualificação de fornecedor indica atendimento dos critérios documentais e de compliance definidos. Não constitui garantia de idoneidade, solvência ou performance futura do fornecedor.' **'Score' (operação):** implica modelo documentado, versionado, auditável. Disclaimer obrigatório: 'Score de Operação é indicador probabilístico produzido por modelo estatístico v[X] com base em dados disponíveis no momento do cálculo. Não constitui garantia de pagamento, recomendação de investimento ou avaliação de crédito nos termos da legislação vigente. Decisão de investimento é de responsabilidade exclusiva do FIDC e seu gestor.' Em: contrato com FIDC, API docs, UI tooltip. **'Antecipação' (operação):** juridicamente: cessão de crédito (art. 286+ CC). NÃO é empréstimo (art. 586+ CC). Tributação: cessão de crédito tem IOF de 0,0041%/dia; empréstimo tem IOF diferente. Regulação: empréstimo requer licença bancária (Bacen). Cessão via FIDC: regulação CVM. Se Mesh chama de 'empréstimo': regulador pode questionar se tem licença bancária. **'Elegível' (recebível):** implica que recebível atendeu critérios específicos para ser antecipado. Critérios: documentados. Se inelegível: comunicar QUAIS critérios não atendidos (transparência + defensability). **'Aprovado' (operação):** implica decisão formal — por quem e baseado em quê? Na Mesh: 'aprovado pela construtora' (actor) + 'baseado em compliance documental e score de operação' (critério). Status: preciso sobre actor e critério. Não: 'aprovado' genérico (por quem? Pela IA? Pelo sistema? Pela construtora?)."
		meshImplication: "Juridical term management: (1) **legal review para termos públicos** — todo termo que aparece em: contrato, termos de uso, API pública, comunicação oficial, dashboard visible a participantes: revisado por advogado ANTES de adoção. Fluxo: developer/agent propõe termo → founder review inicial → se implicação jurídica: advogado revisa → advogado aprova ou sugere alternativa → termo adotado no glossário com nota 'juridicamente revisado em [data] por [advogado].' (2) **disclaimer infrastructure** — para termos que implicam avaliação ou status de qualidade (score, elegível, qualificado): disclaimer padronizado. Disclaimers: gerenciados como termos do glossário — versionados, SSOT, consistentes entre contrato/API/UI. Score: disclaimer em 3 lugares (contrato, API docs, UI tooltip). Qualificado: disclaimer em 2 (contrato, UI tooltip). (3) **status naming discipline** — status de operação: termos precisos sobre WHO decidiu e WHAT criteria. State machine: cada transição tem actor (construtora, FIDC, sistema, agente) e justificativa (compliance ok, score above threshold, documents validated). Status name reflete: 'aprovada_pela_construtora', 'cessão_formalizada', 'liquidação_confirmada.' Não: 'aprovada' genérico que não diz quem nem por quê. (4) **term liability register** — glossário: coluna 'juridical_risk' (alto/médio/baixo). Alto (garantia, certificado): NUNCA usar sem revisão legal completa. Médio (qualificado, elegível, score): definição precisa + disclaimer obrigatório. Baixo (fornecedor, operação, status): definição clara suficiente. (5) **CLAUDE.md:** 'termos com implicação jurídica (qualificado, aprovado, elegível, score, garantia, certificado): não invente — use termos aprovados do glossário. Se novo termo com potencial implicação jurídica é necessário: flag para revisão legal antes de usar em qualquer artefato.' Anti-pattern: developer cria status 'GARANTIDO' para operação onde pagamento bancário foi confirmado. Status aparece no dashboard. Fornecedor lê: 'pagamento garantido pela Mesh.' Banco falha na liquidação (raro mas possível). Fornecedor não recebe. 'Vocês garantiram!' → litígio. Mesh: 'garantido' era status técnico, não promessa comercial. Juiz: 'vocês usaram a palavra garantido em interface visible ao fornecedor.' Melhor status: 'LIQUIDAÇÃO CONFIRMADA' — factual (banco confirmou), sem promessa de garantia."
		dependsOn: ["dl-ubiquitous-language", "dl-term-selection-criteria"]
		crossDependsOn: [{
			lensId:    "lens-trust-and-credibility-design"
			conceptId: "tc-transparency-calibration"
			context:   "TC defines calibrated transparency — reveal enough for informed decision without overwhelming. DL juridical implications is the terminological dimension of transparency calibration: terms must be transparent about what they mean (score = probabilistic indicator, not guarantee) without creating unintended liability (guarantee = legal obligation). TC says 'calibrate what you reveal'; DL says 'calibrate what terms PROMISE — because in law, terms are implicit promises that can be enforced.'"
		}]
		rationale: "Terminological liability 2024+. Legal term review 2024+. Na Mesh fintech, 'garantido' vs 'confirmado' pode ser diferença entre litígio ganho e perdido. Term selection com revisão jurídica: non-negotiable para termos em contratos e comunicação oficial."
	},
	{
		id:         "dl-vocabulary-as-brand"
		name:       "Vocabulário como Marca: Termos Proprietários que Definem o Mercado"
		nature:     "theoretical"
		role:       "property"
		definition: "Conceito de 'category creation through vocabulary' (2024+): empresa que cria categoria nova define o vocabulário da categoria. Salesforce criou 'CRM' como categoria. HubSpot definiu 'inbound marketing.' Bloomberg definiu terminologia de dados financeiros ('terminal', 'ticker', 'yield spread'). Quem define vocabulário: controla como o mercado pensa. Na Mesh: se 'Score de Cadeia', 'Qualificação de Fornecedor', 'Recebível Elegível', 'Antecipação Inteligente' se tornam termos padrão na construção civil brasileira: (a) concorrentes precisam usar mesmos termos (reforçando associação com Mesh) ou inventar alternativos (confundindo mercado — mais difícil). (b) participantes que internalizam vocabulário Mesh: switching cost semântico (conceitos aprendidos são da Mesh). (c) reguladores que adotam vocabulário: institucionalizam a Mesh. Conceito de 'vocabulary moat' (2024+): não patenteável. Mas: quando mercado internaliza, associação é permanente. 'Googlar.' 'Uber.' 'Zoom call.' Verbo = marca. Goal não é exclusividade legal — é ubiquidade semântica."
		meshManifestation: "Na Mesh, candidate proprietary terms: **'Score de Cadeia'** — score que avalia não apenas a empresa mas a posição na cadeia. Credit score (bancário): avalia empresa isolada. Score de Cadeia: avalia empresa NO CONTEXTO da cadeia (quem compra, quem fornece, histórico da relação, performance operacional). Novel: ninguém usa este termo hoje. Se Mesh vencer: 'qual é o Score de Cadeia dessa empresa?' vira pergunta padrão no setor. **'Recebível Elegível'** — recebível que atende TODOS os critérios para antecipação na Mesh. Não é qualquer recebível — é elegível (passou por scoring, compliance, validação documental). Implica: Mesh tem padrão de qualidade que diferencia. **'Qualificação de Fornecedor'** — processo ativo pelo qual fornecedor é habilitado a operar na cadeia via Mesh. Não é cadastro (passivo — fornecedor preenche form). É qualificação (ativa — Mesh avalia compliance, documenta, score, habilita). **'Antecipação Inteligente'** — antecipação com scoring automatizado por IA, compliance contínuo, precificação baseada em dados reais da cadeia. Diferente de antecipação bancária (baseada em garantias estáticas e score de crédito genérico). 'Inteligente': IA analisa dados específicos da cadeia para cada operação."
		meshImplication: "Vocabulary-as-brand strategy: (1) **identify 4-6 candidate terms** — critérios: únicos ao approach da Mesh, descrevem capabilities que concorrentes não têm, seriam adotados pelo mercado se repetidos consistentemente. 4-6 é o sweet spot: memoráveis, gerenciáveis. 50 termos proprietários: ninguém lembra. (2) **uso consistente** — CADA vez que o conceito aparece externamente: usar o termo proprietário. Marketing: 'Score de Cadeia.' Investor deck: 'Score de Cadeia.' Artigo: 'Score de Cadeia.' Webinar: 'Score de Cadeia.' Nunca: 'nosso score', 'o rating', 'a avaliação' — diluição. Repetição é deliberada: builds association. (3) **definição pública clara e quotable** — 'Score de Cadeia: indicador numérico de 0 a 100 que avalia a qualidade de uma operação financeira no contexto da cadeia de supply chain, considerando histórico de pagamento da relação comprador-fornecedor, compliance documental, performance operacional, e posição na rede de fornecedores.' Definição: publishable em artigo, quotable por jornalista, referenciável por regulador. (4) **educar mercado** — content: artigos ('O que é Score de Cadeia e por que construtoras deveriam exigir'), webinars ('Qualificação de Fornecedor: como garantir cadeia compliance'), eventos do setor, submissions regulatórias. Vocabulário entra no discurso do mercado gradualmente. (5) **não over-trademark** — goal é ubiquidade, não exclusividade legal. Se construtora usa 'Score de Cadeia' em seus próprios docs internos: isso é vitória (termo adotado), não infração. Proteger significado, não ownership. (6) **watch for dilution** — se concorrente usa 'Score de Cadeia' para algo inferior ou diferente: educar mercado sobre definição original. 'Score de Cadeia é conceito criado pela Mesh que avalia [definição]. Outras implementações podem não considerar os mesmos fatores.' Anti-pattern: criar 50 termos proprietários que só equipe interna usa — vocabulary overload, ninguém no mercado adota. 4-6 termos fortes > 50 termos fracos."
		dependsOn: ["dl-ubiquitous-language", "dl-term-selection-criteria"]
		rationale: "Category creation through vocabulary 2024+. Vocabulary moat 2024+. Na Mesh, 4-6 proprietary terms que construção civil adota: switching cost semântico. 'Score de Cadeia' becomes how market thinks about supply chain risk. Associação com Mesh: permanente."
	},
	{
		id:         "dl-audience-language-calibration"
		name:       "Calibração de Linguagem por Audiência: Preciso para Expert, Acessível para Novato"
		nature:     "operational"
		role:       "method"
		reviewCadence: "quarterly"
		definition: "Mesmo conceito, apresentação diferente por audiência. Conceito de 'terminology accessibility layers' (2024+): 3 layers: **(1) expert layer** — termos precisos, técnicos, jurídicos. Para: FIDC gestor, advogado, regulador, auditor. 'Cessão de direitos creditórios com deságio de 2,5% sobre o valor de face, em regime de coobrigação parcial do cedente, com liquidação em D+1.' Cada termo: preciso, denso, sem explicação. **(2) professional layer** — termos do domínio, sem jargão jurídico excessivo. Para: construtora gestor, equipe operacional. 'Antecipação de recebível com taxa de 2,5%. Fornecedor qualificado com compliance em dia. Score: 65 (Bom).' **(3) accessible layer** — termos simples, explicações inline, exemplos concretos. Para: fornecedor PME (possivelmente com ensino médio), stakeholder não-financeiro. 'Você recebe R$48.750 amanhã. A taxa é 2,5% (ou seja, R$1.250 de diferença entre o valor da nota de R$50.000 e o que você recebe).' Same information. Three packagings. Conceito de 'term-explanation pairing' (2024+): quando usando termo preciso com non-expert: pair com explicação contextual. 'Deságio (a diferença entre o valor da nota e o valor que você recebe).' Termo: preservado (precisão + vocabulary building). Explicação: acessibilidade. Over time: fornecedor PME que vê 'deságio' 20 vezes com explicação: aprende o termo. Vocabulary is education."
		meshManifestation: "Na Mesh, calibração: **Fornecedor PME (accessible):** 'Você recebe R$48.750' (not 'valor líquido do cedente após aplicação do deságio'). 'Taxa de antecipação: 2,5%' (not 'deságio: CDI+3,7pp'). 'Documentos em dia ✓' (not 'compliance documental satisfatório'). 'Score: Bom ⓘ' (tooltip: 'Score de Operação — indica a qualidade desta operação baseada em dados da cadeia. Bom significa risco moderado.'). 'Previsão de depósito: amanhã, 14/03' (not 'settlement em D+1 bd'). **Construtora gestor (professional):** 'Fornecedores qualificados: 35 de 40.' 'Score de operação: 65 (Bom).' 'Compliance: 92% dos fornecedores em dia.' 'Antecipação: aprovada, settlement D+1.' Termos técnicos usados — explicados no primeiro encontro, não em cada uso. **FIDC gestor (expert):** 'Carteira: R$2,3M lastro. PD média: 1,8%. LGD estimada: 45%. Concentração: HHI 450, top sacado 12%. Deságio médio: CDI+3,7pp. Safra 2025-Q4: performing, inadimplência 30d 0,8%, within 2pp of model prediction.' Full jargão — FIDC gestor reads this fluently. Removing jargão here would be condescending and slow."
		meshImplication: "Calibration implementation: (1) **glossário inclui audience variants** — cada termo com implicação de audience: expert version, professional version, accessible version. Not every term needs all 3 — many are universal ('operação': everyone understands). Only where expert term is unfamiliar: create accessible variant. 'Deságio: expert=deságio. Professional=taxa de antecipação. Accessible=diferença entre valor da nota e valor recebido.' (2) **UI component TermWithExplanation** — renders term + optional tooltip per audience level. Props: value (term), explanation (text), audience (from user context). If audience=expert: 'Deságio' only. If accessible: 'Taxa de antecipação ⓘ' with tooltip 'deságio: diferença entre...' (3) **per-persona default audience** — fornecedor user → accessible by default. Construtora → professional. FIDC → expert. Configurable: construtora gestor who prefers expert level: can switch in settings. Fornecedor owner who is financially sophisticated: can switch to professional. (4) **first-encounter explanation** — when term appears for first time for this user: explanation shown automatically (not just on hover). Subsequent encounters: tooltip on hover only. Track: which terms this user has already encountered. After 5 encounters: no tooltip (user has learned). (5) **accessible ≠ imprecise** — critical rule. 'Você recebe R$48.750': acessível E preciso (valor exato). 'Você recebe uma parte do valor': acessível mas IMPRECISO. Accessibility: simplify language, never simplify accuracy. Number is still exact. Date is still specific. (6) **CLAUDE.md:** 'user-facing text: calibrar terminologia para persona. Fornecedor: accessible (palavras simples, explicações inline, valores concretos). FIDC: expert (jargão técnico, siglas, sem explicações). Construtora: professional (termos do domínio, sem jargão excessivo). Na dúvida: err toward accessible (explicar é melhor que confundir).' Anti-pattern: jargão de FIDC na interface do fornecedor — 'PD: 3,2%, LGD: 45%, EAD: R$48.750, EL: R$705.' Fornecedor PME: 'o que é PD? LGD? EAD? EL?' Ou: oversimplified para FIDC — 'tudo ok 👍.' FIDC gestor: 'I need PD, LGD, concentração, vintage analysis — not emojis.'"
		dependsOn: ["dl-ubiquitous-language", "dl-cross-layer-consistency"]
		crossDependsOn: [{
			lensId:    "lens-stakeholder-communication"
			conceptId: "sc-audience-specific-framing"
			context:   "SC defines audience-specific framing for communication. DL extends to terminology: same concept framed with different terms per audience. SC says 'frame message for audience'; DL says 'choose terms appropriate to audience — deságio for expert, taxa de antecipação for professional, diferença entre nota e valor recebido for accessible.' SC is the framing principle; DL is the vocabulary implementation within that framing."
		}]
		rationale: "Terminology accessibility layers 2024+. Term-explanation pairing 2024+. Na Mesh, 'deságio' for FIDC, 'taxa de antecipação' for construtora, 'diferença entre nota e valor recebido' for fornecedor. Same concept, calibrated packaging. User learns precise term over time through repeated pairing."
	},
	{
		id:         "dl-terminology-governance"
		name:       "Governança de Terminologia: Como Termos São Criados, Modificados e Aposentados"
		nature:     "operational"
		role:       "method"
		reviewCadence: "quarterly"
		definition: "Vocabulário é ativo vivo — novos conceitos surgem, significados evoluem, termos se tornam obsoletos. Conceito de 'terminology lifecycle' (2024+): termos têm lifecycle governado, similar a ADRs para decisões técnicas e PE para evolução de APIs: **(1) proposal** — novo conceito precisa de nome. 3-5 candidates avaliados por 7 critérios. Proposta inclui: termo, definição, justificativa, alternativas rejeitadas com razão, implicação jurídica (se applicable). **(2) review** — domain experts + legal (se juridical_risk ≥ medium) + founder review. Aprovação, iteração, ou rejeição com alternativa. **(3) adoption** — termo adicionado ao glossário com todos os campos. Mapping cross-layer definido. CLAUDE.md atualizado (se impacta agent behavior). Componentes e docs: referenciados. **(4) evolution** — se significado precisa mudar (mercado evolui, regulação muda, feedback de participantes): ADR terminológico. Old definition: archived no glossário (não deletada — histórico preservado). New definition: published. Referências: atualizadas. Communication: para participantes se termo aparece em contratos/API. **(5) deprecation** — se termo é substituído: mark deprecated no glossário com redirect. 'verificado → use qualificado (since 2026-03).' Se externo (API, contrato): PE deprecation ceremony (advance notice, transition period, migration)."
		meshManifestation: "Na Mesh, governance artefatos: **Glossário** — /foundations/glossary.md no mesh-spec. Structured entries: { id: 'term-antecipacao', term_ptbr: 'Antecipação', term_en: 'Anticipation', definition: '...', bc_context: 'ECL', approved_date: '2026-01-15', reviewed_by: 'founder + legal', juridical_risk: 'high', audience_variants: { expert: 'cessão de direitos creditórios', professional: 'antecipação de recebível', accessible: 'receber antes o valor da nota' }, mapping: { code: 'Anticipation', database: 'anticipations', api: '/v1/anticipations', event: 'Anticipation{Action}', ui_ptbr: 'Antecipação', ui_es: 'Anticipación', contract: 'operação de antecipação de recebível' }, rejected_alternatives: ['empréstimo (legally different)', 'adiantamento (ambiguous)', 'crédito (imprecise)'], rationale: 'juridical precision + domain accuracy + competitive differentiation' }."
		meshImplication: "Governance implementation: (1) **PR process para novos termos** — mesmo rigor que code PR: branch, review, approval, merge. Não: developer inventa nome, ships em feature, ninguém revisa, 6 meses depois está em contrato. PR description: '## New Term Proposal\nTerm: Qualificação\nDefinition: ...\n7-Criteria Evaluation: ...\nJuridical Risk: medium\nReviewer: @founder + @legal.' (2) **CI terminology lint (post-MVP, advanced)** — custom rule: class names, event names, API endpoint names checked against glossário mapping. 'VendorApproved' event → warning: 'glossário maps fornecedor to Supplier and approval to Qualification. Consider: SupplierQualified per glossary.' Not blocking initially (warning) → promoted to error as glossário matures. (3) **terminology in agent onboarding** — CLAUDE.md: 'Before naming any domain concept (class, variable, endpoint, event, UI label, status): consult /foundations/glossary.md. If concept exists: use mapped term for the layer you're working in (code=English, UI=Portuguese). If concept doesn't exist: propose new entry with definition + 7-criteria evaluation in PR.' (4) **external term changes → PE ceremony** — se termo muda que afeta participantes (API field renamed, contract term changed): PE lens applies. Deprecation notice 30 days (within version) or 12 months (API version). Migration guide. Re-acceptance for contract. Same rigor as API breaking change — because terminology change IS a breaking change for consumers who built processes around the old term. (5) **quarterly terminology review** — 45 min: (a) any concepts in codebase without glossário entry? grep for class names not in glossary. (b) pick 3 concepts: verify term consistency across code/API/event/UI/contract. (c) any new terms this quarter with juridical risk: were they reviewed by legal? (d) any ad-hoc naming in recent agent PRs? flag for correction. (e) glossário entries: any definitions stale or outdated? Anti-pattern: glossário exists but nobody consults — new features use ad-hoc terms (developer names it whatever comes to mind, agent generates whatever seems reasonable), glossário becomes stale reference that new team members ignore, inconsistency returns to pre-glossário levels. Prevention chain: CLAUDE.md instruction → PR review checklist → CI lint → quarterly audit. Each layer: catches what previous missed."
		dependsOn: ["dl-ubiquitous-language", "dl-term-selection-criteria", "dl-cross-layer-consistency", "dl-juridical-implications"]
		rationale: "Terminology lifecycle 2024+. Na Mesh, glossário as governed artifact: terms are created, reviewed, adopted, evolved, and deprecated with same rigor as code and API changes. Because: terms that appear in contracts and APIs have same longevity and legal impact as code. Code bug: fix and deploy. Term bug in contract: legal exposure."
	},
	{
		id:         "dl-bilingual-terminology"
		name:       "Terminologia Bilíngue: Português nos Negócios, Inglês no Código"
		nature:     "operational"
		role:       "heuristic"
		reviewCadence: "annual"
		definition: "Na Mesh brasileira com codebase em inglês: domain concepts existem em 2 idiomas. Português: linguagem do negócio, contratos, UI, participantes, reguladores. Inglês: linguagem do código, API, eventos, documentação técnica, international standards. Conceito de 'bilingual mapping' (2024+): cada termo do glossário tem: pt-BR (business language) e en (code language). Mapeamento explícito, revisado, nunca casual. 'Antecipação' (pt-BR) = 'Anticipation' (en). 'Fornecedor' = 'Supplier.' 'Recebível' = 'Receivable.' 'Deságio' = 'Desagio' (preserved — no English equivalent captures exact meaning. 'Discount' is close but generic. Desagio is preserved as-is in code with documentation). Quando tradução é imprecisa ou inexistente: preservar original com nota explicativa. 'Desagio: Portuguese financial term for the difference between the face value of a receivable and the amount paid to the assignor (cedente) in an anticipation operation. Approximately translates to 'discount' but carries specific legal meaning in Brazilian cessão de crédito (credit assignment) context. Used as-is in code because no English term captures the precise meaning.'"
		meshManifestation: "Na Mesh, bilingual mapping categories: **Direct translations (1:1 equivalence):** antecipação → Anticipation. Fornecedor → Supplier. Construtora → Constructor (or Buyer in financial context). Recebível → Receivable. Operação → Operation. Qualificação → Qualification. Score → Score (same in both — loanword universally accepted). Compliance → Compliance (same). **Close translations (approximate, documented):** Cedente → Assignor (close — English legal equivalent for credit assignment. Documented: 'Assignor is the English legal equivalent of cedente in cessão de crédito context.'). Sacado → Debtor or Obligor (close — debtor is who owes the debt. Documented: 'Debtor is the party obligated to pay the receivable. In Mesh context: the construtora/buyer.'). **Preserved (no equivalent):** Deságio → Desagio (preserved as-is. Documented extensively). FIDC → FIDC (Brazilian-specific legal entity type with no equivalent. Documented: 'Fundo de Investimento em Direitos Creditórios — Brazilian regulated investment vehicle for credit rights.'). **Convention:** code, variables, class names, method names: English from glossário mapping. Comments and documentation: English with pt-BR terms in parentheses for domain concepts ('The anticipation (antecipação) is created when...'). CLAUDE.md itself: English with pt-BR for domain concepts. UI strings: pt-BR exclusively. API documentation: English with pt-BR glossary appendix. Contracts: pt-BR exclusively (legal requirement for Brazilian contracts)."
		meshImplication: "Bilingual implementation: (1) **glossário has both columns** — term_ptbr + term_en + translation_notes. Every entry: both languages. Translation_notes: for close or preserved terms, explanation of why and mapping nuances. (2) **code in English** — class names, variables, methods: English terms from glossário mapping. Anticipation, Supplier, Receivable, OperationScore, Qualification. Not: Antecipacao, Fornecedor, Recebivel (Portuguese in code: non-standard in international software convention, harder for non-Portuguese-speaking contributors, mixing languages in code is confusing). Exception: domain terms without English equivalent: preserve Portuguese (Desagio, FIDC). These: documented with English explanation in class-level comment. class Desagio { /** Portuguese financial term: the discount applied... */ }. (3) **comments and docs in English** — technical documentation: English. Domain explanations that bridge both languages: 'An Anticipation (antecipação) is the operation by which a Supplier (fornecedor), acting as Assignor (cedente), transfers the rights to a Receivable to a FIDC (cessionário) at a Desagio (deságio, i.e., discount from face value).' First occurrence: both languages. Subsequent: English only. (4) **API in English** — endpoints: /v1/anticipations. Fields: supplier_id, discount_amount, assignor, settlement_date. API documentation: English with glossary that maps to pt-BR for Brazilian developers. (5) **UI in pt-BR** — all user-facing labels, messages, statuses: Portuguese. 'Antecipação', 'Fornecedor', 'Score', 'Qualificação.' (6) **CLAUDE.md:** 'code: English terms from glossary. If domain term has no English equivalent: preserve Portuguese with documentation. UI strings: Portuguese from glossary. API: English. Comments: English with pt-BR for domain terms on first use. Always check glossary for correct translation — never invent translation ad-hoc.' Anti-pattern 1: mixed-language code — 'class Fornecedor { val antecipacoes: List<Antecipacao> }.' Portuguese class names: non-standard, exclude future international contributors, confuse non-Portuguese tooling. Anti-pattern 2: forced English that loses precision — 'LoanRequest' when concept is 'Anticipation.' Loan and anticipation are legally, fiscally, and regulatorily different things. Wrong term imports wrong mental model."
		dependsOn: ["dl-ubiquitous-language", "dl-cross-layer-consistency"]
		rationale: "Bilingual mapping 2024+. Na Mesh, pt-BR for business (where precision matters for participants, lawyers, regulators), English for code (where international convention matters for developers and tooling). Glossário bridges both: explicit mapping, reviewed, consistent. Preserved terms (Desagio, FIDC): honest about untranslatability rather than forcing inaccurate translation."
	},
	{
		id:            "dl-terminology-review"
		name:          "Revisão de Terminologia: Inventário Periódico de Consistência e Precisão"
		nature:        "operational"
		role:          "method"
		reviewCadence: "quarterly"
		definition:    "Inventário periódico que consolida todos os conceitos: (1) glossário — current? All active concepts have entry? Definitions accurate and not stale? (2) cross-layer — same term in code, API, event, UI, contract for each concept? Any mismatches? (3) juridical — terms with legal implication: reviewed by lawyer in last 12 months? Disclaimers in place and current? (4) brand vocabulary — proprietary terms used consistently in recent external communications? (5) audience calibration — fornecedor sees accessible terms? FIDC sees expert? Any jargão leaking to wrong audience? (6) bilingual — mapping current? New terms this quarter have both pt-BR and en? (7) agent compliance — agents using glossário terms in recent PRs? Any ad-hoc naming slipping through?"
		meshManifestation: "Na Mesh: revisão trimestral. Glossário freshness + codebase naming audit + cross-layer spot check."
		meshImplication: "Quarterly (45min): (a) glossário freshness — any concept used in codebase without glossário entry? Search: class names, event names in code. Compare with glossário. Any missing: add. (b) cross-layer spot check — pick 3 concepts. Verify: code term, API term, event name, UI label — all match mapping table. If mismatch: create PR to fix. (c) juridical review status — any new user-facing terms added this quarter? Any with juridical risk (medium/high)? Reviewed by legal? If not: schedule review. (d) brand vocabulary — 'Score de Cadeia' and other proprietary terms: used consistently in recent blog posts, investor materials, presentations? Any dilution (using generic 'score' instead of 'Score de Cadeia')? (e) agent naming compliance — review 5 recent PRs from agent: all naming follows glossary? Any ad-hoc terms ('TransactionProcessor' when glossary says 'AnticipationProcessor')? Flag for correction. (f) bilingual check — new terms this quarter: both pt-BR and en columns in glossary? Translation notes for approximations? (g) audience leakage — spot-check: is any FIDC jargão (PD, LGD, HHI) visible in fornecedor interface? Is fornecedor simplification ('tudo ok') visible in FIDC interface?"
		dependsOn: ["dl-ubiquitous-language", "dl-term-selection-criteria", "dl-cross-layer-consistency", "dl-juridical-implications", "dl-vocabulary-as-brand", "dl-audience-language-calibration", "dl-terminology-governance", "dl-bilingual-terminology"]
		rationale: "Terminology drifts organically: new agent session creates 'VendorApproval' class (glossary says SupplierQualification), new UI screen uses 'rating' (glossary says 'score'), contract template adds 'garantia' without legal review. Quarterly audit: catches drift before it compounds into systemic inconsistency."
	},
]

reasoningProtocol: [
	{question: "O glossário canônico existe no mesh-spec com cada termo definido, mapeado cross-layer, e revisado?", reveals: "Se terminologia é governada — ou se cada developer/agent inventa nomes ad hoc.", rationale: "Evans 2003: ubiquitous language. Glossário como SSOT: 1 termo per conceito per context."},
	{question: "Para cada novo termo: 7 critérios foram avaliados (precisão jurídica, domínio, familiaridade, diferenciação, i18n, consistency, brevidade)?", reveals: "Se seleção é deliberada — ou se primeiro nome que veio à mente foi usado.", rationale: "Term selection framework 2024+. 'Garantido' vs 'confirmado' pode ser litígio."},
	{question: "Mesmo conceito usa mesmo termo em code, API, evento, UI e contrato? Mapping table existe e é consultada?", reveals: "Se comunicação é unambígua — ou se 5 termos para 1 conceito confunde developers, agents e participantes.", rationale: "Terminology mapping 2024+. Code-language alignment DDD. 5 terms = confusion. 1 term per layer = clarity."},
	{question: "Termos com implicação jurídica (qualificado, aprovado, elegível, score, garantia) foram revisados por advogado?", reveals: "Se liability terminológica é gerenciada — ou se developer criou obrigação jurídica inadvertida.", rationale: "Terminological liability 2024+. 'Garantido' in dashboard = legal promise."},
	{question: "4-6 termos proprietários (Score de Cadeia, etc.) são usados consistentemente em toda comunicação de mercado?", reveals: "Se vocabulary moat está sendo construído — ou se oportunidade de category creation é desperdiçada.", rationale: "Vocabulary moat 2024+. Bloomberg defined financial vocabulary. Mesh can define supply chain finance."},
	{question: "Linguagem é calibrada por audiência? Fornecedor vê accessible, FIDC vê expert, construtora vê professional?", reveals: "Se cada audiência entende — ou se jargão de FIDC aparece para fornecedor PME.", rationale: "Accessibility layers 2024+. Same concept, calibrated packaging per audience."},
	{question: "Código usa English terms do glossário? Domain terms sem tradução (deságio, FIDC) são preservados com documentação?", reveals: "Se bilingual mapping é consistente — ou se código mistura idiomas aleatoriamente.", rationale: "Bilingual mapping 2024+. pt-BR for business, English for code. Glossário bridges both."},
]

meshExamples: [
	{
		id:       "ex-antecipacao-vs-emprestimo"
		scenario: "Marketing team propõe chamar o produto de 'Empréstimo Rápido para Fornecedores' porque 'empréstimo' é mais familiar que 'antecipação' para fornecedor PME."
		analysis: "Familiar: sim, PME conhece 'empréstimo.' Mas: (1) juridicamente: antecipação é cessão de crédito (art. 286 CC), não empréstimo (art. 586 CC). Tributação diferente (IOF). Regulação diferente (empréstimo = Bacen; cessão via FIDC = CVM). (2) Se Mesh chama de 'empréstimo' e regulador questiona: 'se é empréstimo, precisa de licença bancária.' Mesh opera via FIDC, não tem licença bancária. Risco: enquadramento regulatório incorreto. (3) Se construtora ou fornecedor processa Mesh alegando 'empréstimo abusivo': termo foi Mesh que escolheu. Self-inflicted legal exposure."
		recommendation: "(1) Rejeitar 'empréstimo.' Manter 'antecipação de recebível' como termo oficial em todos os canais. (2) Para PME: usar linguagem acessível SEM usar 'empréstimo.' 'Receba antes: antecipe o valor da sua nota fiscal.' O conceito de 'receber antes' é familiar sem invocar 'empréstimo.' (3) Tooltip: 'Antecipação é diferente de empréstimo. Você não contrai dívida — você antecipa o recebimento de um valor que já é seu (nota fiscal emitida e confirmada pelo comprador). A taxa é o custo de receber antes do prazo.' (4) Educar: 'antecipação' é mais favorável para fornecedor (não é dívida, é aceleração de recebimento que já é dele). Marketing pode usar: 'Receba antes. Sem empréstimo.' — posiciona antecipação como superior a empréstimo. (5) Glossário: 'Antecipação: operação de cessão de direitos creditórios. NÃO é empréstimo. Justificativa: [jurídica: art. 286 vs 586 CC] + [regulatória: CVM vs Bacen] + [tributária: IOF diferente]. Audience accessible: receba antes, antecipe o valor da nota.' (6) Se marketing insiste: escalar para advogado. Risk assessment formal: uso de 'empréstimo' é risco regulatório concreto e mensurável."
		principlesApplied: ["ax-01", "ax-06"]
		assumptions: ["regulador questionaria 'empréstimo' — risco real dado que FIDC opera sob CVM, não Bacen", "fornecedor PME aceita 'antecipação' com explicação — validate com user research, may need A/B testing", "'receba antes' é familiar o suficiente — simpler than 'antecipação' and legally correct"]
		rationale: "Term selection: juridical precision + regulatory accuracy > familiarity. 'Empréstimo': familiar mas legally wrong, regulatorily dangerous, and positions product as commodity (banks do loans). 'Antecipação' with accessible explanation: precise, safe, and differentiating."
	},
	{
		id:       "ex-qualificado-vs-verificado"
		scenario: "Agent cria status 'VERIFICADO' para fornecedores que passam compliance check. Construtora lê dashboard: 'Fornecedor ABC — Verificado ✓'. Interpretação: 'Mesh verificou este fornecedor e ele está bom.' 6 meses depois: fornecedor ABC defaults em operação de R$200k. Construtora para Mesh: 'mas vocês verificaram ele!'"
		analysis: "'Verificado' means 'checked' — mas não especifica: contra quais critérios, com qual profundidade, com qual garantia. Construtora interpreta 'verificado ✓' como seal of approval. Quando fornecedor defaults: 'Mesh verificou' vira argumento em disputa. Se Mesh não pode provar critérios rigorosos de verificação: liability. 'Qualificado' é melhor: implica critérios específicos foram definidos E atendidos. Critérios são documentáveis. 'Qualificado conforme critérios X, Y, Z' é defensável. 'Verificado' sem especificar contra o quê: indefensável."
		recommendation: "(1) Mudar status de 'VERIFICADO' para 'QUALIFICADO' com definição explícita: 'Fornecedor qualificado: atendeu os seguintes critérios: (a) documentos de compliance em dia (certidão negativa federal, FGTS, INSS). (b) Score de Operação acima do threshold configurado pela construtora. (c) dados cadastrais validados (CNPJ ativo, QSA sem restrições).' (2) Disclaimer ao lado de 'Qualificado' na UI: ⓘ 'Qualificação indica atendimento de critérios documentais e de compliance. Não constitui garantia de idoneidade, solvência ou performance futura. [Ver critérios].' (3) Glossário: 'Qualificado: fornecedor que atendeu critérios documentais, de compliance e de score definidos pela construtora contratante. Não usar: verificado (ambíguo — verificar ≠ atender), aprovado (implica decisão de mérito pela plataforma), certificado (implica autoridade certificadora que Mesh não é).' (4) Contrato: 'A plataforma qualifica fornecedores segundo critérios documentais e de compliance definidos e configuráveis pela construtora contratante. A qualificação é baseada em informações fornecidas pelo fornecedor e verificações automatizadas, não constituindo garantia de idoneidade, solvência, ou performance futura do fornecedor.' (5) Migration: rename verified→qualified em database (ALTER COLUMN), API (field rename — PE breaking change → deprecation), events (new event name), UI (label change). (6) Legal review: advogado revisa definição e disclaimer antes de deploy."
		principlesApplied: ["ax-01", "ax-06"]
		assumptions: ["'qualificado' é defensável juridicamente com critérios documentados — validate com advogado", "construtora aceita que qualificação ≠ garantia — disclaimer must be visible and clear", "rename é worth the breaking change — sim: juridical risk de 'verificado' > migration cost"]
		rationale: "Terminological liability 2024+. 'Verificado': creates ambiguous liability (checked but against what standard?). 'Qualificado' with documented criteria and explicit disclaimer: precise, defensible, honest about scope. Term change: worth migration cost to avoid future litigation risk."
	},
	{
		id:       "ex-cross-layer-inconsistency"
		scenario: "Codebase audit revela: code uses 'Vendor' class, API uses 'supplier' in endpoints, event uses 'SupplierRegistered', UI says 'Fornecedor', contract says 'cedente', and documentation says 'provider.' Developer building new feature asks: 'when I create an endpoint for this entity, which term do I use?'"
		analysis: "6 termos para 1 entidade (in general context). Developer confusion: which is canonical? Each choice was made by different person at different time with different reasoning. No glossary was consulted (didn't exist at time). Consequence: developer spends 30 minutes deciding, picks 'vendor' (because that's what existing code uses), and propagates the least-correct term to yet another layer."
		recommendation: "(1) Create glossary entry: 'Fornecedor (pt-BR) / Supplier (en): entidade que fornece bens ou serviços na cadeia de supply chain. Context: relationship with platform (NGR bounded context). Code: Supplier. DB: suppliers. API: /v1/suppliers, supplier_id. Event: Supplier{Action}. UI: Fornecedor. Note: in legal/financial context, when acting as assignor in anticipation operation (ECL bounded context): Cedente (pt-BR) / Assignor (en). Not to use: vendor (English ambiguity — can mean vending machine company), provider (too generic — could be service provider, cloud provider), prestador (Portuguese formal alternative but uncommon in construção civil).' (2) Migration: rename 'Vendor' class → 'Supplier' (IDE refactoring: safe, 30 min). Update 'provider' → 'supplier' in documentation (search-replace: 15 min). Events and API: already use correct terms. Contract: 'cedente' is correct for legal context — no change. (3) Effort: 4-8 hours total for rename + doc update + review. (4) Prevention: glossary + mapping table + CLAUDE.md instruction. Every new feature: developer/agent consults glossary before naming. Code review: checks naming against mapping table. (5) Answer to developer's question: 'Use Supplier for code and API (per glossary English mapping). The UI label is Fornecedor. In legal documents, the same entity is called Cedente when acting as assignor in an anticipation.'"
		principlesApplied: ["ax-01", "ax-06"]
		assumptions: ["Vendor→Supplier rename is non-breaking internally — yes, IDE refactoring handles all references", "6 terms is realistic for ungoverned codebase — common in startups without terminology governance", "4-8 hours is sufficient — for code rename + doc update in medium codebase"]
		rationale: "Cross-layer consistency + terminology mapping. 6 terms → 2 per context (Supplier for code/API, Fornecedor for UI, Cedente for legal). Developer: clear answer from glossary. Agent: clear instruction from CLAUDE.md. Zero ambiguity."
	},
	{
		id:       "ex-score-de-cadeia-brand"
		scenario: "Mesh develops unique scoring approach that considers supply chain context (relationship history, operational performance, network position) in addition to traditional credit factors. Marketing needs a name that differentiates from generic 'credit score' and could become market standard."
		analysis: "Options evaluated: (a) 'Credit Score' — generic, every bank and fintech uses. Zero differentiation. No association with Mesh. Participant hears 'credit score': thinks Serasa/SPC. Not what Mesh does. (b) 'Risk Rating' — generic, used by rating agencies (Moody's, S&P). Implies letter scale (AAA, BBB). Mesh uses numeric 0-100. Confusing overlap. (c) 'Supply Chain Score' — descriptive, accurate in English. But: generic enough for any competitor to claim. No Portuguese resonance (market language is Portuguese). (d) 'Score de Cadeia' — Portuguese (market language for Brazilian construção civil), Mesh-specific (nobody uses this term today), implies chain/network context (cadeia = chain/network), memorable (short, distinctive), novel (first-mover on this term)."
		recommendation: "(1) Adopt 'Score de Cadeia' as proprietary term. Public definition: 'Score de Cadeia: indicador numérico de 0 a 100 que avalia a qualidade de uma operação financeira no contexto da cadeia de supply chain, considerando: histórico de pagamento da relação comprador-fornecedor, compliance documental contínuo, performance operacional, e posição na rede de fornecedores. Diferente de score de crédito bancário (que avalia empresa isolada), o Score de Cadeia avalia a empresa no contexto das suas relações comerciais — porque na supply chain, o risco é relacional, não apenas individual.' (2) Usage plan: API: score field within anticipation (in context, 'score' suffices — qualified by endpoint). UI: 'Score de Cadeia: 65 (Bom).' Marketing: 'Score de Cadeia — a nova referência de risco na construção civil.' Investor materials: 'proprietary Supply Chain Score (Score de Cadeia).' Press: 'Score de Cadeia™.' (3) Educate market: article series 'O que é Score de Cadeia e por que ele é mais preciso que score de crédito tradicional.' Conference presentation at CBIC or similar construção civil event. Regulatory submission to CVM mentioning 'Score de Cadeia' as methodology. (4) Consistency: EVERY external mention of scoring concept: 'Score de Cadeia.' Not 'nosso score,' not 'a avaliação de risco,' not 'o indicador.' Specific term, every time. (5) Track adoption: when construtora gestor says 'qual é o Score de Cadeia desse fornecedor?' without Mesh prompting → term adopted. When construção civil trade publication uses term without definition → market vocabulary. (6) International: 'Supply Chain Score' or 'Chain Score' in English-language materials. Both map back to 'Score de Cadeia' in glossário."
		principlesApplied: ["ax-01", "ax-04"]
		assumptions: ["'Score de Cadeia' is memorable and differentiated — validate with market feedback (test with 10 construtora gestors)", "construção civil market will adopt the term — requires consistent usage over 12-24 months + real value of the concept", "regulatory bodies would reference the term — if Mesh becomes significant enough to influence regulation", "English equivalent works — 'Supply Chain Score' is descriptive enough for international context"]
		rationale: "Category creation through vocabulary 2024+. 'Score de Cadeia': novel term for novel concept. Nobody uses it today. If Mesh succeeds and the term is adopted: permanent association. Competitors: must use Mesh's term (reinforcing association) or invent alternative (confusing market — harder). Vocabulary moat: not patentable but virtually permanent once internalized by market."
	},
]

principleIds: ["ax-01", "ax-04", "ax-06", "dp-01"]

relatedLenses: [
	{lensId: "lens-documentation-as-product", relation: "complementsWith", context: "DP defines SSOT and glossary as documentation infrastructure. DL provides the terminological content: glossary entries with definitions, mappings, audience variants, juridical risk levels. DP is the documentation framework; DL is the vocabulary content that lives in it."},
	{lensId: "lens-trust-and-credibility-design", relation: "complementsWith", context: "TC builds trust through transparency and reliability. DL juridical implications ensures terms don't create unintended promises. 'Qualificado' with criteria + disclaimer: transparent about what it means and doesn't mean. TC is trust framework; DL is terminological trust — words that participants can rely on without being misled."},
	{lensId: "lens-stakeholder-communication", relation: "complementsWith", context: "SC defines audience-specific framing for communication. DL extends to terminology: same concept framed with different vocabulary per audience. SC says 'frame for audience'; DL says 'choose specific terms per audience — deságio for expert, taxa for professional, diferença for accessible.' SC is strategy; DL is vocabulary implementation."},
	{lensId: "lens-api-design-as-product", relation: "complementsWith", context: "API defines endpoint and field naming conventions. DL provides the correct English terms for domain concepts per glossary mapping. API says 'name endpoints clearly and consistently'; DL says 'use Supplier not Vendor, Anticipation not Transaction — per glossary.' API is naming convention; DL is naming content."},
	{lensId: "lens-multi-sided-platform-ux", relation: "complementsWith", context: "MUX defines per-side experience design. DL adds per-side terminology. Fornecedor sees accessible terms. FIDC sees expert terms. MUX designs the experience; DL designs the language within that experience."},
	{lensId: "lens-platform-evolution-and-backwards-compatibility", relation: "feedsInto", context: "PE defines how to evolve without breaking consumers. DL: term changes in API/events are breaking changes — PE's deprecation ceremony applies. Rename 'verified' to 'qualified' in API field: PE process (12-month notice, migration guide, version transition). Same rigor for terminology evolution as for API evolution."},
	{lensId: "lens-internationalization-and-localization-architecture", relation: "complementsWith", context: "IL defines multi-language architecture. DL provides the bilingual mapping content (pt-BR ↔ en) for all domain terms. When adding es-LATAM: DL mapping includes Spanish column for each term. IL is the i18n architecture; DL is the vocabulary content per language."},
]

limitations: [
	{description: "Glossary governance adds process overhead — every new term requires 7-criteria evaluation, review, documentation.", alternative: "Scale governance to risk. Internal-only code naming: lightweight (agent proposes in PR, founder approves in review, 5 minutes). Terms in contracts or public API: full ceremony with legal review. Most terms are low-risk internal: lightweight process. Few are high-risk external: full ceremony.", rationale: "Internal code naming: lightweight review. Contract-facing term: full governance. 90% of terms need 5 minutes; 10% need 1 hour."},
	{description: "Proprietary vocabulary ('Score de Cadeia') may not be adopted by market if Mesh doesn't reach sufficient scale.", alternative: "Use proprietary terms consistently regardless of current scale. Cost: zero extra beyond internal consistency (which is valuable independently). Upside: if Mesh succeeds, terms are established. Downside: if Mesh fails, terms were at least internally consistent. Asymmetric bet: upside is large, downside is zero.", rationale: "Zero extra cost beyond consistency. Upside: market adoption. Downside: none."},
	{description: "Bilingual mapping (pt-BR business / en code) creates translation burden and potential for mismatch.", alternative: "Glossary as single source with both columns reviewed together. Preserve untranslatable terms (Desagio, FIDC) rather than forcing inaccurate translation. Consistency > linguistic purity. When mapping is uncertain: preserve original with documentation.", rationale: "Some terms don't translate precisely. Preserving with documentation is more honest and less error-prone than forcing approximate translation."},
	{description: "Legal review of terms adds time and cost to terminology decisions.", alternative: "Legal review only for terms that appear externally: contracts, terms of use, API documentation, official communications, marketing materials. Internal-only terms (code variable names, internal docs): no legal review needed. Priority ranking: contracts > API > UI > marketing > code. Most new terms: internal. Few: external.", rationale: "Legal review by external exposure risk. Contract terms: always. Code variable names: never."},
	{description: "Maintaining 3 audience layers (expert/professional/accessible) for terminology adds content management overhead.", alternative: "3 layers only where expert term is genuinely unfamiliar to accessible audience. Many domain terms are universally understood: 'operação' (everyone knows), 'fornecedor' (everyone knows), 'status' (everyone knows). Only terms like 'deságio', 'coobrigação', 'HHI' need 3 layers. Selective, not universal: ~20% of terms need audience variants; 80% are universal.", rationale: "Selective calibration > universal 3-layer overhead. Most terms work for all audiences. Few need adaptation."},
]

rationale: "A Bloomberg criou vocabulário que se tornou o vocabulário do mercado financeiro. Na Mesh, cada termo que aparece em API, evento, interface, contrato e documentação se torna o vocabulário da construção civil se a plataforma vencer. Esta lens operacionaliza: linguagem ubíqua com glossário canônico e cross-context consistency (Evans 2003, vocabulary as competitive moat 2024+), critérios de seleção de termos com 7 dimensões incluindo precisão jurídica e diferenciação competitiva (term selection framework 2024+), consistência cross-layer com mapping table que garante 1 termo per conceito per layer (terminology mapping 2024+, code-language alignment DDD 2023+), implicações jurídicas de terminologia com legal review e disclaimers padronizados (terminological liability 2024+, legal term review 2024+), vocabulário como marca com 4-6 termos proprietários (category creation through vocabulary 2024+, vocabulary moat 2024+), calibração de linguagem por audiência com 3 layers de acessibilidade (terminology accessibility layers 2024+, term-explanation pairing 2024+), governança de terminologia com lifecycle formal de termos (terminology lifecycle 2024+), e mapeamento bilíngue pt-BR/en com preservação de termos intraduzíveis (bilingual mapping 2024+). Vocabulário é propriedade intelectual semântica — se a Mesh definir 'Score de Cadeia', 'Recebível Elegível', 'Qualificação de Fornecedor' como termos do mercado: concorrentes operam no território linguístico da Mesh."

}
